CONFIG_MCUX_COMPONENT_middleware.wireless.ble_hci_transport_rpmsg=y
CONFIG_MCUX_COMPONENT_component.power_manager_framework=n

CONFIG_MCUX_COMPONENT_middleware.wireless.ble_fsci_source_channel_sounding=y
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_host_CS=y
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_host_CS_component_lib=y