/*
    * Copyright 2024 NXP
    *
    * SPDX-License-Identifier: BSD-3-Clause
*/

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v15.0
processor: MC56F82748
package_id: MC56F82748VLH
mcu_data: ksdk2_0
processor_version: 0.16.3
pin_labels:
- {pin_num: '46', pin_signal: GPIOE1/PWM_0A, label: PWM_AT, identifier: PWM_AT}
- {pin_num: '45', pin_signal: GPIOE0/PWM_0B, label: PWM_AB, identifier: PWM_AB}
- {pin_num: '48', pin_signal: GPIOE3/PWM_1A, label: PWM_BT, identifier: PWM_BT}
- {pin_num: '47', pin_signal: GPIOE2/PWM_1B, label: PWM_BB, identifier: PWM_BB}
- {pin_num: '52', pin_signal: GPIOE5/PWM_2A/XB_IN3, label: PWM_CT, identifier: PWM_CT}
- {pin_num: '51', pin_signal: GPIOE4/PWM_2B/XB_IN2, label: PWM_CB, identifier: PWM_CB}
- {pin_num: '25', pin_signal: GPIOB1/ANB1/CMPB_IN0/DACB_O, label: I_A_adc_a, identifier: I_A;I_A_adc_a}
- {pin_num: '27', pin_signal: GPIOB2/ANB2/VREFHB/CMPC_IN3, label: I_C_adc_a, identifier: I_C;I_C_adc_a}
- {pin_num: '13', pin_signal: GPIOA0/ANA0/CMPA_IN3/CMPC_O, label: I_A_adc_b, identifier: I_A;I_A_adc_b}
- {pin_num: '14', pin_signal: GPIOA1/ANA1/CMPA_IN0, label: I_B_adc_b, identifier: I_B;I_B_adc_b}
- {pin_num: '24', pin_signal: GPIOB0/ANB0/CMPB_IN3, label: V_dcb, identifier: V_dcb}
- {pin_num: '58', pin_signal: GPIOF6/PWM_3X/XB_IN2, label: SW1, identifier: SW1}
- {pin_num: '64', pin_signal: TDI/GPIOD0, label: LED_Y, identifier: LED;LED_Y}
- {pin_num: '62', pin_signal: TDO/GPIOD1, label: LED_G, identifier: LED_G}
- {pin_num: '36', pin_signal: GPIOF0/XB_IN6/SCLK1, label: DRV_EN, identifier: DRV_EN}
- {pin_num: '6', pin_signal: GPIOF8/RXD0/XB_OUT10/CMPD_O/PWM_2X, label: DRV_INT, identifier: DRV_INT}
- {pin_num: '32', pin_signal: GPIOC7/SS0_B/TXD0/XB_IN8, label: DRV_SS, identifier: DRV_SS}
- {pin_num: '21', pin_signal: GPIOB4/ANB4/CMPC_IN1, label: LED_USER, identifier: LED_USER}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_sim.h"
#include "fsl_gpio.h"
#include "fsl_xbara.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    PWM_Pins();
    ADC_Pins();
    Misc_Pins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
PWM_Pins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '5', peripheral: PWMA, signal: 'FAULT, 0', pin_signal: GPIOC2/TXD0/XB_OUT11/XB_IN2/CLKO0}
  - {pin_num: '46', peripheral: PWMA, signal: 'A, 0', pin_signal: GPIOE1/PWM_0A, direction: OUTPUT}
  - {pin_num: '45', peripheral: PWMA, signal: 'B, 0', pin_signal: GPIOE0/PWM_0B, direction: OUTPUT}
  - {pin_num: '48', peripheral: PWMA, signal: 'A, 1', pin_signal: GPIOE3/PWM_1A, direction: OUTPUT}
  - {pin_num: '47', peripheral: PWMA, signal: 'B, 1', pin_signal: GPIOE2/PWM_1B, direction: OUTPUT}
  - {pin_num: '52', peripheral: PWMA, signal: 'A, 2', pin_signal: GPIOE5/PWM_2A/XB_IN3, direction: OUTPUT}
  - {pin_num: '51', peripheral: PWMA, signal: 'B, 2', pin_signal: GPIOE4/PWM_2B/XB_IN2, direction: OUTPUT}
  - {pin_num: '33', peripheral: QSPI0, signal: MISO, pin_signal: GPIOC8/MISO0/RXD0/XB_IN9/XB_OUT6}
  - {pin_num: '35', peripheral: QSPI0, signal: MOSI, pin_signal: GPIOC10/MOSI0/XB_IN5/MISO0/XB_OUT9}
  - {pin_num: '32', peripheral: QSPI0, signal: SS, pin_signal: GPIOC7/SS0_B/TXD0/XB_IN8, direction: OUTPUT}
  - {pin_num: '34', peripheral: QSPI0, signal: SCLK, pin_signal: GPIOC9/SCLK0/XB_IN4/TXD0/XB_OUT8}
  - {pin_num: '36', peripheral: GPIOF, signal: 'GPIO, 0', pin_signal: GPIOF0/XB_IN6/SCLK1, direction: OUTPUT, drive_strength: high, pull_enable: disable}
  - {pin_num: '6', peripheral: GPIOF, signal: 'GPIO, 8', pin_signal: GPIOF8/RXD0/XB_OUT10/CMPD_O/PWM_2X, direction: INPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : PWM_Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void PWM_Pins(void)
{
    /* GPIOC IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOC);
    /* GPIOE IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOE);
    /* GPIOF IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOF);
    /* Enable peripheral functionality on pin GPIOC2 (pin 5) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin2, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC2 (pin 5) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C2_XB_IN2);
    /* Enable peripheral functionality on pin GPIOC7 (pin 32) */
    GPIO_PinSetPeripheralMode(PWM_PINS_DRV_SS_GPIO, PWM_PINS_DRV_SS_PIN_MASK, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC7 (pin 32) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C7_SS0_B);
    /* Enable peripheral functionality on pin GPIOC8 (pin 33) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin8, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC8 (pin 33) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C8_MISO0);
    /* Enable peripheral functionality on pin GPIOC9 (pin 34) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin9, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC9 (pin 34) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C9_SCLK0);
    /* Enable peripheral functionality on pin GPIOC10 (pin 35) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin10, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC10 (pin 35) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C10_MOSI0);
    /* Enable peripheral functionality on pin GPIOE0 (pin 45) */
    GPIO_PinSetPeripheralMode(PWM_PINS_PWM_AB_GPIO, PWM_PINS_PWM_AB_PIN_MASK, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOE1 (pin 46) */
    GPIO_PinSetPeripheralMode(PWM_PINS_PWM_AT_GPIO, PWM_PINS_PWM_AT_PIN_MASK, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOE2 (pin 47) */
    GPIO_PinSetPeripheralMode(PWM_PINS_PWM_BB_GPIO, PWM_PINS_PWM_BB_PIN_MASK, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOE3 (pin 48) */
    GPIO_PinSetPeripheralMode(PWM_PINS_PWM_BT_GPIO, PWM_PINS_PWM_BT_PIN_MASK, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOE4 (pin 51) */
    GPIO_PinSetPeripheralMode(PWM_PINS_PWM_CB_GPIO, PWM_PINS_PWM_CB_PIN_MASK, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE4 (pin 51) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E4_PWM_2B);
    /* Enable peripheral functionality on pin GPIOE5 (pin 52) */
    GPIO_PinSetPeripheralMode(PWM_PINS_PWM_CT_GPIO, PWM_PINS_PWM_CT_PIN_MASK, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE5 (pin 52) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E5_PWM_2A);
    /* GPIO functionality on pin GPIOF0 (pin 36) */
    GPIO_PinSetPeripheralMode(PWM_PINS_DRV_EN_GPIO, PWM_PINS_DRV_EN_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOF8 (pin 6) */
    GPIO_PinSetPeripheralMode(PWM_PINS_DRV_INT_GPIO, PWM_PINS_DRV_INT_PIN_MASK, kGPIO_ModeGpio);

    /* Initialize GPIO functionality on pin GPIOF8 (pin 6)  */
    GPIO_PinSetDirection(PWM_PINS_DRV_INT_GPIO, PWM_PINS_DRV_INT_PIN_MASK, kGPIO_DigitalInput);

    /* Pin configuration on GPIOF0 (pin 36) */
    /* Strength control configuration: High drive strength is configured */
    GPIO_PinSetDriveStrength(PWM_PINS_DRV_EN_GPIO, PWM_PINS_DRV_EN_PIN_MASK, kGPIO_DriveStrengthHigh);

    /* Initialize GPIO functionality on pin GPIOF0 (pin 36)  */
    GPIO_PinWrite(PWM_PINS_DRV_EN_GPIO, PWM_PINS_DRV_EN_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(PWM_PINS_DRV_EN_GPIO, PWM_PINS_DRV_EN_PIN_MASK, kGPIO_DigitalOutput);

    GPIOF->PUR = ((GPIOF->PUR &
                   /* Mask bits to zero which are setting */
                   (~(GPIO_PUR_PU_0_MASK)))

                  /* Pull Resistor Enable Bits: Pull resistor is disabled. */
                  | GPIO_PUR_PU(PUR_PU_0_DISABLED));
    /* XB_IN2 output assigned to XBARA_IN2 input is connected
     * to XBARA_OUT29 output assigned to PWM_FAULT0 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputXbIn2, kXBARA_OutputPwmFault0);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
ADC_Pins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '25', peripheral: ADC, signal: 'ANB, 1', pin_signal: GPIOB1/ANB1/CMPB_IN0/DACB_O, identifier: I_A_adc_a}
  - {pin_num: '27', peripheral: ADC, signal: 'ANB, 2', pin_signal: GPIOB2/ANB2/VREFHB/CMPC_IN3, identifier: I_C_adc_a}
  - {pin_num: '13', peripheral: ADC, signal: 'ANA, 0', pin_signal: GPIOA0/ANA0/CMPA_IN3/CMPC_O, identifier: I_A_adc_b}
  - {pin_num: '14', peripheral: ADC, signal: 'ANA, 1', pin_signal: GPIOA1/ANA1/CMPA_IN0, identifier: I_B_adc_b}
  - {pin_num: '24', peripheral: ADC, signal: 'ANB, 0', pin_signal: GPIOB0/ANB0/CMPB_IN3}
  - {peripheral: ADC, signal: 'SYNC, A', pin_signal: PWM0_OUT_TRIG0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : ADC_Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void ADC_Pins(void)
{
    /* GPIOA IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOA);
    /* GPIOB IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOB);
    /* Enable peripheral functionality on pin GPIOA0 (pin 13) */
    GPIO_PinSetPeripheralMode(ADC_PINS_I_A_adc_b_GPIO, ADC_PINS_I_A_adc_b_PIN_MASK, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOA0 (pin 13) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_A0_ANA0_and_CMPA_IN3);
    /* Enable peripheral functionality on pin GPIOA1 (pin 14) */
    GPIO_PinSetPeripheralMode(ADC_PINS_I_B_adc_b_GPIO, ADC_PINS_I_B_adc_b_PIN_MASK, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB0 (pin 24) */
    GPIO_PinSetPeripheralMode(ADC_PINS_V_dcb_GPIO, ADC_PINS_V_dcb_PIN_MASK, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB1 (pin 25) */
    GPIO_PinSetPeripheralMode(ADC_PINS_I_A_adc_a_GPIO, ADC_PINS_I_A_adc_a_PIN_MASK, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOB1 (pin 25) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_B1_ANB1_and_CMPB_IN0);
    /* Enable peripheral functionality on pin GPIOB2 (pin 27) */
    GPIO_PinSetPeripheralMode(ADC_PINS_I_C_adc_a_GPIO, ADC_PINS_I_C_adc_a_PIN_MASK, kGPIO_ModePeripheral);
    /* PWM0_OUT_TRIG0 output assigned to XBARA_IN18 input is connected
     * to XBARA_OUT12 output assigned to ADCA_SYNC */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputPwm0OutTrig0, kXBARA_OutputAdcaSync);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
Misc_Pins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '41', peripheral: QSCI1, signal: TXD, pin_signal: GPIOF4/TXD1/XB_OUT8/PWM_0X/PWM_FAULT6}
  - {pin_num: '42', peripheral: QSCI1, signal: RXD, pin_signal: GPIOF5/RXD1/XB_OUT9/PWM_1X/PWM_FAULT7}
  - {pin_num: '58', peripheral: GPIOF, signal: 'GPIO, 6', pin_signal: GPIOF6/PWM_3X/XB_IN2, direction: INPUT, gpio_interrupt: gpioIrqFallingEdge}
  - {pin_num: '21', peripheral: GPIOB, signal: 'GPIO, 4', pin_signal: GPIOB4/ANB4/CMPC_IN1, direction: OUTPUT, gpio_init_state: 'true', pull_enable: disable}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : Misc_Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void Misc_Pins(void)
{
    /* GPIOB IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOB);
    /* GPIOF IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOF);
    /* GPIO functionality on pin GPIOB4 (pin 21) */
    GPIO_PinSetPeripheralMode(MISC_PINS_LED_USER_GPIO, MISC_PINS_LED_USER_PIN_MASK, kGPIO_ModeGpio);
    /* Enable peripheral functionality on pin GPIOF4 (pin 41) */
    GPIO_PinSetPeripheralMode(GPIOF, kGPIO_Pin4, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOF4 (pin 41) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_F4_TXD1);
    /* Enable peripheral functionality on pin GPIOF5 (pin 42) */
    GPIO_PinSetPeripheralMode(GPIOF, kGPIO_Pin5, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOF5 (pin 42) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_F5_RXD1);
    /* GPIO functionality on pin GPIOF6 (pin 58) */
    GPIO_PinSetPeripheralMode(MISC_PINS_SW1_GPIO, MISC_PINS_SW1_PIN_MASK, kGPIO_ModeGpio);

    /* Initialize GPIO functionality on pin GPIOF6 (pin 58)  */
    GPIO_PinSetDirection(MISC_PINS_SW1_GPIO, MISC_PINS_SW1_PIN_MASK, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOB4 (pin 21)  */
    GPIO_PinWrite(MISC_PINS_LED_USER_GPIO, MISC_PINS_LED_USER_PIN_MASK, kGPIO_OutputHigh);
    GPIO_PinSetDirection(MISC_PINS_LED_USER_GPIO, MISC_PINS_LED_USER_PIN_MASK, kGPIO_DigitalOutput);

    /* Interrupt configuration on GPIOF6 (pin 58): Interrupt on falling edge */
    GPIO_PinSetInterruptConfig(MISC_PINS_SW1_GPIO, MISC_PINS_SW1_PIN_MASK, kGPIO_InterruptFallingEdge);

    /* Internal Peripheral Select */
    /* Select SCI1_RXD Input.: Select SCI1_RXD Input, GPIOC12 or GPIOF5. */
    SIM_SetInternalPeriInput(SIM, kSIM_SCI1_RXDInputIndex, kSIM_SCI1_RXDInput_GPIOC12_GPIOF5);


    GPIOB->PUR = ((GPIOB->PUR &
                   /* Mask bits to zero which are setting */
                   (~(GPIO_PUR_PU_4_MASK)))

                  /* Pull Resistor Enable Bits: Pull resistor is disabled. */
                  | GPIO_PUR_PU(PUR_PU_4_DISABLED));
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
