
CONFIG_MCUX_PRJSEG_middleware.freertos-kernel.generated_config=y

CONFIG_MCUX_COMPONENT_middleware.lwip=y
CONFIG_MCUX_COMPONENT_middleware.freemodbus.tcp=y

CONFIG_MCUX_PRJSEG_module.board.pinmux_project_core_folder=n
# end of Board project basic segments
CONFIG_MCUX_COMPONENT_component.phyrtl8211f=y
CONFIG_MCUX_COMPONENT_driver.netc=y
CONFIG_MCUX_COMPONENT_driver.msgintr=y
CONFIG_MCUX_COMPONENT_middleware.lwip.netc_ethernetif=y
CONFIG_MCUX_COMPONENT_component.rgpio_adapter=y
CONFIG_MCUX_COMPONENT_component.silicon_id=n
CONFIG_NETC_PORT_USE_INCLUDES=y

