#
# Copyright 2024 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
CONFIG_MCUX_PRJSEG_middleware.multicore.rpmsg-lite.generated_config=n
CONFIG_MCUX_COMPONENT_middleware.multicore.mcmgr=n
CONFIG_RL_USE_MCMGR_IPC_ISR_HANDLER=n
CONFIG_RL_USE_DEFERRED_RX_CALLBACK=n
CONFIG_MCUX_COMPONENT_utility.incbin=n
CONFIG_USE_TCM_AS_RPMSG_SHMEM=y
CONFIG_RPMSG_M71_M33S=y
#CONFIG_RPMSG_M33S_M71=y
#CONFIG_RPMSG_M33S_M70=y
#CONFIG_RPMSG_M70_M71=y
#CONFIG_RPMSG_M70_M33S=y
#CONFIG_RPMSG_M71_M70=y

