# Copyright 2024-2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_COMPONENT_component.phyyt8521=y
CONFIG_MCUX_COMPONENT_driver.msgintr=y
CONFIG_MCUX_COMPONENT_driver.netc=y
CONFIG_MCUX_COMPONENT_middleware.lwip.netc_ethernetif=y
CONFIG_ETH_MAX_RX_PKTS_AT_ONCE=8
CONFIG_NETC_RXBD_NUM=8
CONFIG_NETC_RXBUFF_NUM="16"
CONFIG_TCP_WND="5840"
