#
# Copyright 2024 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_folder=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_core_folder=n
CONFIG_USE_TCM_AS_RPMSG_SHMEM=y
