#components
CONFIG_MCUX_COMPONENT_middleware.mcuboot.bootutil=y
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_folder=y
CONFIG_MCUX_COMPONENT_utility.assert=y
CONFIG_MCUX_COMPONENT_utility.assert_lite=n

# MCXN547|MCXN947 board specific
CONFIG_MCUX_COMPONENT_middleware.mcuboot.tinycrypt=n
CONFIG_MCUX_COMPONENT_middleware.mcuboot.mcxn_custom_cfg.main_flash_only=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.port.config=n
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.port.only_accelerator_config=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.port.psa_crypto_config=n
CONFIG_MCUX_COMPONENT_component.els_pkc=y
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.els_pkc=y
CONFIG_MCUX_COMPONENT_middleware.mcuboot.nxp_encrypted_xip=y