# zigbee freertos-kernel config
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.cm33_non_trustzone=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.extension=y

CONFIG_configTOTAL_HEAP_SIZE=122880
# CONFIG_configMINIMAL_STACK_SIZE=500
CONFIG_configMINIMAL_STACK_SIZE=256
# CONFIG_configTIMER_TASK_STACK_DEPTH="256"
CONFIG_configTICK_RATE_HZ=1000
CONFIG_configMAX_PRIORITIES=10
CONFIG_configENABLE_BACKWARD_COMPATIBILITY=n
CONFIG_configRECORD_STACK_HIGH_ADDRESS=y
CONFIG_configUSE_TIMERS=y
CONFIG_configTIMER_QUEUE_LENGTH=10

# edgefast freertos-kernel config
CONFIG_configSUPPORT_STATIC_ALLOCATION=y

# wifi freertos-kernel config
CONFIG_configUSE_IDLE_HOOK=y
CONFIG_configUSE_TICK_HOOK=y
CONFIG_configCHECK_FOR_STACK_OVERFLOW=y
CONFIG_configUSE_MALLOC_FAILED_HOOK=y
CONFIG_configUSE_DAEMON_TASK_STARTUP_HOOK=n
CONFIG_configUSE_TRACE_FACILITY=y
CONFIG_configUSE_STATS_FORMATTING_FUNCTIONS=y
CONFIG_configUSE_APPLICATION_TASK_TAG=y
CONFIG_configINCLUDE_FREERTOS_TASK_C_ADDITIONS_H=y