# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_PRJSEG_module.board.pinmux_project_folder=y

CONFIG_MCUX_COMPONENT_driver.dma=n
CONFIG_MCUX_COMPONENT_driver.dmamux=n
CONFIG_MCUX_COMPONENT_driver.edma=n
CONFIG_MCUX_COMPONENT_driver.lpuart_dma=n