# Add additional configuration
mcux_add_macro(
    CC "-DHIGH_SPEED_SDIO_CLOCK\
       -DFSL_SDK_ENABLE_DRIVER_CACHE_CONTROL=1\
       -DFSL_FEATURE_PHYKSZ8081_USE_RMII50M_MODE\
       -DENET_RXBUFF_NUM=25"
)
