
CONFIG_MCUX_COMPONENT_component.serial_manager=y
CONFIG_MCUX_COMPONENT_component.serial_manager_usb_cdc=y
CONFIG_MCUX_COMPONENT_driver.reset=y
CONFIG_USB_DEVICE_CONFIG_EHCI=1
CONFIG_USB_DEVICE_CONFIG_KHCI=0
