# Custom configuration for encrypted XIP evaluation
# boards: evkmimxrt1160, evkbmimxrt1170

CONFIG_MCUX_COMPONENT_middleware.mcuboot.serial_recovery=n
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.caam=n
CONFIG_MCUX_COMPONENT_driver.otfad=y
CONFIG_MCUX_COMPONENT_middleware.mcuboot.nxp_encrypted_xip=y
CONFIG_BOOT_CUSTOM_DEVICE_SETUP=y
CONFIG_BOOT_MODE_ENCRYPTED_XIP_OVERWRITE=y
CONFIG_BOOT_FLASH_ACT_APP_ADDRESS=0x30040000
CONFIG_BOOT_FLASH_CAND_APP_ADDRESS=0x30240000
CONFIG_BOOT_FLASH_SLOT0_ENC_CFG_ADDRESS=0x30440000
CONFIG_BOOT_FLASH_SLOT1_ENC_CFG_ADDRESS=0x30441000