# Custom configuration for encrypted XIP evaluation
# boards: evkmimxrt1160, evkbmimxrt1170

CONFIG_BOOT_CUSTOM_DEVICE_SETUP=y
CONFIG_BOOT_MODE_OVERWRITE_ONLY=y
CONFIG_BOOT_FLASH_ACT_APP_ADDRESS=0x30040000
CONFIG_BOOT_FLASH_CAND_APP_ADDRESS=0x30240000