
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_LV_LABEL_TEXT_SELECTION=n
CONFIG_LV_LABEL_LONG_TXT_HINT=n
CONFIG_LV_MEM_SIZE_KILOBYTES=48
CONFIG_LVGL_SUPPORT_VDB_COUNT=1
CONFIG_MCUX_COMPONENT_driver.edma4=y
CONFIG_MCUX_COMPONENT_driver.edma_soc=y
CONFIG_MCUX_COMPONENT_driver.dmamux=y
