#
# Copyright 2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

#select profile
CONFIG_MCUX_COMPONENT_middleware.tfm.profile_medium=y

#include pin_mux board component
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=y

CONFIG_MCUX_COMPONENT_middleware.tfm.lpuart=y

# enable west flash of tfm example
CONFIG_FLASH_BASE_ADDRESS=0x00048000

#config blob placement address for ns part
CONFIG_BLOB_AREA=0x000C4000