CONFIG_MCUX_COMPONENT_component.audio_sai_edma_adapter=y
CONFIG_MCUX_COMPONENT_component.lpi2c_adapter=y
CONFIG_MCUX_COMPONENT_driver.lpi2c=y
CONFIG_MCUX_COMPONENT_driver.sai=y
CONFIG_MCUX_COMPONENT_driver.wm8962=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=y
