#
# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
#choose tf-m ns-configurations
CONFIG_MCUX_COMPONENT_middleware.tfm.ns=y

#select profile
CONFIG_MCUX_COMPONENT_middleware.tfm.profile_medium=y

# choose startup files related configs
CONFIG_MCUX_COMPONENT_device.startup=n
CONFIG_MCUX_COMPONENT_device.system=y

# enabled mbedtls3x lib for CSR related operations
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.port.tfm=y

# Enable builtin CRC driver module 
CONFIG_MCUX_COMPONENT_driver.crc=y