/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*! @name PORTD0 (number 47), SW1/PTD0
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SW1_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_SW1_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SW1_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_SW1_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_SW1_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name PORTE4 (number 63), SW2/PTE4
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_SW2_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_SW2_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_SW2_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_SW2_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_SW2_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void);

#define PORT_DFER_DFE_5_MASK 0x20u /*!<@brief Digital Filter Enable Mask for item 5. */

/*! @name PORTE5 (number 64), J18[A37]/J18[B33]/D3/PTE5
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_GREEN_GPIO GPIOE               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_GREEN_GPIO_PIN_MASK (1U << 5U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED_GREEN_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_LED_GREEN_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_LED_GREEN_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORTF1 (number 68), J18[A38]/J18[B34]/D4/PTF1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_RED_GPIO GPIOF               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_RED_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED_RED_PORT PORTF               /*!<@brief PORT peripheral base pointer */
#define BOARD_LED_RED_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_LED_RED_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*! @name PORTD1 (number 48), J18[B23]/D5/PTD1/GPIO3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_ORANGE_GPIO GPIOD               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_ORANGE_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED_ORANGE_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_LED_ORANGE_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_LED_ORANGE_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name PORTC1 (number 20), J18[B35]/D6/PTC1/GPIO4/CMP1P1
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_LED_YELLOW_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_LED_YELLOW_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_LED_YELLOW_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_LED_YELLOW_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_LED_YELLOW_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void);

#define PORT_DFER_DFE_0_MASK 0x01u /*!<@brief Digital Filter Enable Mask for item 0. */

/*! @name PORTE0 (number 55), J18[A8]/J10[15]/U7[3]/S1[14]/J11[4]/U14[21]/PTE0/I2C0_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_ACCEL_SDA_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_ACCEL_SDA_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_ACCEL_SDA_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORTD7 (number 54), J18[A7]/J10[16]/U7[5]/S1[13]/J11[3]/U14[20]/PTD7/I2C0_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_ACCEL_SCL_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_ACCEL_SCL_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_ACCEL_SCL_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORTF7 (number 74), J18[A33]/J18[A37]/J18[A64]/J10[22]/S1[12]/PTF7/CLKOUT
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_ACCEL_EN_GPIO GPIOF               /*!<@brief GPIO peripheral base pointer */
#define BOARD_ACCEL_EN_GPIO_PIN_MASK (1U << 7U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_ACCEL_EN_PORT PORTF               /*!<@brief PORT peripheral base pointer */
#define BOARD_ACCEL_EN_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_ACCEL_EN_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitACCELPins(void);

/*!
 * @brief
 * UART1 IRDA Select: Pad RX input (PTD[2] or PTI[0], as selected in Pinmux control) selected for RX input of
 * UART1 and UART1 TX signal is not used for modulation.
 */
#define MISC_CTL_UART1IRSEL_0b0 0x00u

/*! @name PORTI0 (number 91), J18[A43]/J10[12]/J11[17]/PTI0/SCI1_RXD
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_DEBUG_UART_RX_PORT PORTI               /*!<@brief PORT peripheral base pointer */
#define BOARD_DEBUG_UART_RX_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_DEBUG_UART_RX_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTI1 (number 92), J18[A44]/J10[13]/J11[18]/PTI1/SCI1_TXD
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_DEBUG_UART_TX_PORT PORTI               /*!<@brief PORT peripheral base pointer */
#define BOARD_DEBUG_UART_TX_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_DEBUG_UART_TX_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/*! @name PORTE2 (number 57), X1[3]/EXTAL_8MHz_KM38
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_XTAL_8MHz_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_XTAL_8MHz_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_XTAL_8MHz_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*! @name PORTE3 (number 58), X1[1]/XTAL_8MHz_KM38
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_EXTAL_8MHz_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_EXTAL_8MHz_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_EXTAL_8MHz_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name EXTAL32K (number 26), Y1[2]/EXTAL_32K_KM38
  @{ */
/* @} */

/*! @name XTAL32K (number 25), Y1[1]/XTAL_32K_KM38
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitOSCPins(void);

#define PORT_DFER_DFE_0_MASK 0x01u /*!<@brief Digital Filter Enable Mask for item 0. */

/*! @name PORTE0 (number 55), J18[A8]/J10[15]/U7[3]/S1[14]/J11[4]/U14[21]/PTE0/I2C0_SDA
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_EEPROM_SDA_PORT PORTE               /*!<@brief PORT peripheral base pointer */
#define BOARD_EEPROM_SDA_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_EEPROM_SDA_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*! @name PORTD7 (number 54), J18[A7]/J10[16]/U7[5]/S1[13]/J11[3]/U14[20]/PTD7/I2C0_SCL
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_EEPROM_SCL_PORT PORTD               /*!<@brief PORT peripheral base pointer */
#define BOARD_EEPROM_SCL_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_EEPROM_SCL_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                  /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitEEPROMPins(void);

/*!
 * @brief
 * UART0 IRDA Select: UART0 selected for IRDA modulation.
 * UART0 TX modulated by XBAR_OUT[14] and UART0 RX input connected to XBAR_OUT[13].
 */
#define MISC_CTL_UART0IRSEL_0b1 0x01u
/*!
 * @brief UART Modulation Type: TypeB (ANDed) Modulation selected for IRDA */
#define MISC_CTL_UARTMODTYPE_0b1 0x01u

/*! @name PORTC3 (number 22), J18[A41]/S1[15]/PTC3
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_IR_RX_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_IR_RX_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_IR_RX_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTC2 (number 21), J18[A42]/S1[16]/PTC2
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_IR_TX_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_IR_TX_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_IR_TX_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitINFRA_REDPins(void);

/*! @name PORTG1 (number 76), J8[1]/PTG1/AD10
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_ADC_POT_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_ADC_POT_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_ADC_POT_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPOTENTIOMETERPins(void);

/*! @name PORTF0 (number 67), J9[1]/PTF0/AD7
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_ADC_TEMP_PORT PORTF               /*!<@brief PORT peripheral base pointer */
#define BOARD_ADC_TEMP_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_ADC_TEMP_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitTEMP_SENSORPins(void);

/*! @name PORTC4 (number 23), J18[D44]/DS[1]/LCD43
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD43_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD43_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_LCD43_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTB6 (number 17), J18[D32]/DS1[2]/LCD37
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD37_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD37_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_LCD37_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTB5 (number 16), J18[D28]/DS1[3]/LCD36
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD36_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD36_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_LCD36_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTB4 (number 15), J18[D27]/DS1[4]/LCD35
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD35_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD35_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_LCD35_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTB3 (number 14), J18[C80]/DS1[5]/LCD34
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD34_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD34_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_LCD34_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTB2 (number 13), J18[D80]/DS1[6]/LCD33
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD33_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD33_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_LCD33_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTB1 (number 12), J18[D79]/DS1[7]/LCD32
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD32_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD32_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_LCD32_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTB0 (number 9), J18[D78]/DS1[8]/LCD31
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD31_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD31_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_LCD31_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTA5 (number 6), J18[D64]/DS1[9]/LCD28
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD28_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD28_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_LCD28_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTA4 (number 5), J18[D63]/DS1[10]/LCD27
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD27_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD27_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_LCD27_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTA3 (number 4), J18[C64]/DS1[11]/LCD26
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD26_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD26_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_LCD26_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTA2 (number 3), J18[C63]/DS1[12]/LCD25
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD25_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD25_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_LCD25_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTA1 (number 2), J18[C62]/DS1[13]/LCD24
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD24_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD24_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_LCD24_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTA0 (number 1), J18[D54]/DS1[14]/LCD23
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD23_PORT PORTA               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD23_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_LCD23_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTI3 (number 94), J18[D53]/DS1[15]/LCD22
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD22_PORT PORTI               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD22_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_LCD22_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTI2 (number 93), J18[D52]/DS1[16]/LCD21
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD21_PORT PORTI               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD21_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_LCD21_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTH5 (number 88), J18[C57]/DS1[17]/LCD20
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD20_PORT PORTH               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD20_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_LCD20_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTH4 (number 87), J18[C56]/DS1[18]/LCD19
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD19_PORT PORTH               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD19_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_LCD19_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTH3 (number 86), J18[C55]/DS1[19]/LCD18
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD18_PORT PORTH               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD18_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_LCD18_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTH2 (number 85), J18[C54]/DS1[20]/LCD17
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD17_PORT PORTH               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD17_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_LCD17_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTH1 (number 84), J18[C53]/DS1[21]/LCD16
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD16_PORT PORTH               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD16_PIN 1U                   /*!<@brief PORT pin number */
#define BOARD_LCD16_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTH0 (number 83), J18[C52]/DS1[22]/LCD15
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD15_PORT PORTH               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD15_PIN 0U                   /*!<@brief PORT pin number */
#define BOARD_LCD15_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTG7 (number 82), J18[C51]/DS1[23]/LCD14
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD14_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD14_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_LCD14_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTG6 (number 81), J18[C50]/DS1[24]/LCD13
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD13_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD13_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_LCD13_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTG5 (number 80), J18[D48]/DS1[25]/LCD12
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD12_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD12_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_LCD12_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTG4 (number 79), J18[D47]/DS1[26]/LCD11
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD11_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD11_PIN 4U                   /*!<@brief PORT pin number */
#define BOARD_LCD11_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTG3 (number 78), J18[D46]/DS1[27]/LCD10
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD10_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD10_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_LCD10_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                             /* @} */

/*! @name PORTG2 (number 77), J18[D45]/DS1[28]/LCD9
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_LCD9_PORT PORTG               /*!<@brief PORT peripheral base pointer */
#define BOARD_LCD9_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_LCD9_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLCDPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
