# drivers
CONFIG_MCUX_COMPONENT_device.CMSIS=y
CONFIG_MCUX_COMPONENT_device.startup=y
CONFIG_MCUX_COMPONENT_driver.common=y

# board files
CONFIG_MCUX_HAS_PRJSEG_project.use_hw_app=n
CONFIG_MCUX_HAS_PRJSEG_module.board.pinmux_sel=n
CONFIG_MCUX_PRJSEG_module.board.use_board_clock=n
CONFIG_MCUX_PRJSEG_module.board.boardfile=n
CONFIG_MCUX_PRJSEG_module.board.console_lite=n
CONFIG_MCUX_PRJSEG_module.board.suite=n
CONFIG_MCUX_PRJSEG_module.board.wireless.core_linker_script=y

# placeholder for later use
# CONFIG_MCUX_PRJSEG_module.board.wireless.board=y
# CONFIG_MCUX_PRJSEG_module.board.wireless.hw_app=y

# OS
CONFIG_MCUX_COMPONENT_component.osa=y
CONFIG_MCUX_COMPONENT_component.osa_threadx=y

# multicore
CONFIG_MCUX_COMPONENT_component.rpmsg_adapter=y
CONFIG_MCUX_COMPONENT_middleware.multicore.mcmgr=y
CONFIG_MCUX_PRJSEG_middleware.multicore.rpmsg-lite.generated_config=n
CONFIG_HAL_RPMSG_SELECT_ROLE=y

# wireless
CONFIG_MCUX_COMPONENT_middleware.wireless.framework=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.platform.ics=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.platform.sensors=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.platform.lowpower=y
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_controller_threadx=y
CONFIG_MCUX_COMPONENT_middleware.wireless.xcvr=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.sfc=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.platform.ble=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.platform.sensors=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.dbg.nbu_debug=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.platform.dbg=y
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_host_interface=y
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_hci_transport_rpmsg=y
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_controller_nbu_asm=y
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_controller_hadm=y
CONFIG_MCUX_COMPONENT_middleware.wireless.nbu_all_hosted_lib=y
# Fault handlers for debug
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.dbg.fault_handlers=y
