# board
CONFIG_MCUX_HAS_PRJSEG_project.use_hw_app=n
CONFIG_MCUX_HAS_PRJSEG_module.board.pinmux_sel=n
CONFIG_MCUX_PRJSEG_module.board.use_board_clock=n
CONFIG_MCUX_PRJSEG_module.board.boardfile=n
CONFIG_MCUX_PRJSEG_module.board.console_lite=n
CONFIG_MCUX_PRJSEG_module.board.suite=y
CONFIG_MCUX_PRJSEG_module.board.wireless.linker_script_ble=n
CONFIG_MCUX_PRJSEG_module.board.wireless.core_linker_script=n
CONFIG_MCUX_PRJSEG_module.board.wireless.core_linker_script_ble=y

# drivers
CONFIG_MCUX_COMPONENT_driver.common=y
CONFIG_MCUX_COMPONENT_device.CMSIS=y
CONFIG_MCUX_COMPONENT_device.startup=y

# components
CONFIG_MCUX_COMPONENT_component.osa_threadx=y
CONFIG_MCUX_COMPONENT_component.component.rpmsg_adapter=y

# multicore
CONFIG_MCUX_PRJSEG_middleware.multicore.rpmsg-lite.generated_config=n
CONFIG_HAL_RPMSG_SELECT_ROLE=y
CONFIG_MCUX_COMPONENT_middleware.multicore.mcmgr=y

# connectivity framework
CONFIG_MCUX_COMPONENT_middleware.wireless.framework=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.fsci=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.sfc=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.nvm=n
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.platform.ics=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.platform.lowpower=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.platform.sensors=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.seclib_rng_port.sw=y

# Bluetooth LE controller
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_controller_nbu_app_base=y
CONFIG_MCUX_COMPONENT_middleware.wireless.controller_api=n
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_controller_hadm=y

# Bluetooth LE host
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_gatt_db=y
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_gatt_service_discovery=y
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_hci_transport_rpmsg=n
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_fsci_interface=y
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_ncp_fsci_source=y
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_host_OPT_component_lib=y
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_ncp_common=y
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_host_interface=y