CONFIG_MCUX_COMPONENT_component.mflash_onchip=y
CONFIG_MCUX_COMPONENT_component.debug_coredump_backend.mflash=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.cm33_non_trustzone=y
CONFIG_MFLASH_COREDUMP_REGION_START_ADDR=0xA0000
CONFIG_MFLASH_COREDUMP_REGION_SIZE=0x2000
CONFIG_MCUX_COMPONENT_driver.cmc=y
