# coex_wifi_edgefast applications
set(CONFIG_WIFI           1)
set(CONFIG_WPA_SUPPLICANT 1)

# coex defines
target_compile_definitions(${MCUX_SDK_PROJECT_NAME}
    PRIVATE
    CONFIG_COEX_ENABLE_WIFI_MENU=${CONFIG_WIFI}
    CONFIG_WIFI_BLE_COEX_APP=${CONFIG_WIFI}
    CONFIG_COEX_ENABLE_BLE_MENU=0
    CONFIG_COEX_ENABLE_MENU=1
    CONFIG_WPA_SUPP_MBEDTLS=${CONFIG_WPA_SUPPLICANT}
)
