# Copyright 2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_DEPENDENCY_COMPONENT_component.hal_clock_DEPEND_ANYOF_OPTION_2=y
CONFIG_MCUX_DEPENDENCY_COMPONENT_component.hal_power_DEPEND_ANYOF_OPTION_2=y
CONFIG_MCUX_DEPENDENCY_COMPONENT_component.hal_pinctrl_DEPEND_ANYOF_OPTION_2=y
# common setting for system manager component segments, sm option5 now is for IMX943 CM7 CORE0.
CONFIG_MCUX_DEPENDENCY_COMPONENT_component.sm_clock_DEPEND_ANYOF_OPTION_5=y
CONFIG_MCUX_DEPENDENCY_COMPONENT_component.sm_pinctrl_DEPEND_ANYOF_OPTION_5=y
CONFIG_MCUX_DEPENDENCY_COMPONENT_component.sm_power_DEPEND_ANYOF_OPTION_5=y
CONFIG_MCUX_DEPENDENCY_COMPONENT_component.sm_reset_DEPEND_ANYOF_OPTION_3=y
# end of core basic segments
