CONFIG_CLOCK_CONTROL=y
CONFIG_FLASH=y
CONFIG_MCUX_COMPONENT_component.memfault_sdk=y
CONFIG_MCUX_COMPONENT_component.memfault_sdk.ports.mcuxsdk=y
CONFIG_MCUX_COMPONENT_component.gen_hal=y
CONFIG_MCUX_COMPONENT_utility.assert=n
CONFIG_MCUX_COMPONENT_utility.assert_lite=n
