# Copyright 2025 NXP
# SPDX-License-Identifier: BSD-3-Clause

# Board config
CONFIG_MCUX_PRJSEG_module.board.boardfile=n
CONFIG_MCUX_PRJSEG_module.board.wireless.board=y
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.wireless.hw_app=y
CONFIG_MCUX_PRJSEG_module.board.wireless.app_services=y

# Component config
CONFIG_MCUX_COMPONENT_component.mem_manager_light=y
CONFIG_MCUX_COMPONENT_component.reset_adapter=y
CONFIG_MCUX_DEPENDENCY_COMPONENT_component.timer_manager_DEPEND_component.timer_manager_ctimer=y

# Link layer configuration
CONFIG_MCUX_COMPONENT_middleware.wireless.snps_ll=y
CONFIG_MCUX_COMPONENT_middleware.wireless.snps_ll_controller_api=y

# Host stack configuration. Disable channel sounding in host stack. Feature not available on MCXW23.
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_fsci_source_channel_sounding=n 
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_host_CS=n
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_host_CS_component_lib=n

# Disable generic lowpower framework.
CONFIG_MCUX_PRJSEG_module.board.wireless.board.lowpower=n
