/*
 * Copyright 2023,2025 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: TEE v8.0
processor: MCXN947T
package_id: MCXN947TVDF
mcu_data: ksdk2_0
processor_version: 0.2412.70
board: FRDM-MCXN947T
toolOptions:
  _output_type_: c_code
  _legacy_source_names_: 'yes'
  _resilient_code_reg_writes_: 'no'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "tzm_config.h"

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/* SAU region boundaries */
#define BOARD_INITTEE_SAU_REGION_0_BASE 0
#define BOARD_INITTEE_SAU_REGION_0_END 0x0FFFFFFFU
#define BOARD_INITTEE_SAU_REGION_1_BASE 0x20000000U
#define BOARD_INITTEE_SAU_REGION_1_END 0xDFFFFFFFU
#define BOARD_INITTEE_SAU_REGION_2_BASE 0x1001FE00U
#define BOARD_INITTEE_SAU_REGION_2_END 0x1001FFFFU

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
functional_group:
- called_from_default_init: 'true'
- id_prefix: 'BOARD_INITTEE_'
- prefix_user_defined: 'false'
- name: 'BOARD_InitTEE'
- description: ''
- ahbsc_rwx:
  - interrupts:
    - masking: {Non-masked: {id: [ADC0_IRQn, ADC1_IRQn, BSP32_IRQn, CAN0_IRQn, CAN1_IRQn, CDOG0_IRQn, CDOG1_IRQn, CMC0_IRQn, CTI0_IRQn, CTIMER0_IRQn, CTIMER1_IRQn,
          CTIMER2_IRQn, CTIMER3_IRQn, CTIMER4_IRQn, DAC0_IRQn, DAC1_IRQn, DAC2_IRQn, EDMA_0_CH0_IRQn, EDMA_0_CH10_IRQn, EDMA_0_CH11_IRQn, EDMA_0_CH12_IRQn, EDMA_0_CH13_IRQn,
          EDMA_0_CH14_IRQn, EDMA_0_CH15_IRQn, EDMA_0_CH1_IRQn, EDMA_0_CH2_IRQn, EDMA_0_CH3_IRQn, EDMA_0_CH4_IRQn, EDMA_0_CH5_IRQn, EDMA_0_CH6_IRQn, EDMA_0_CH7_IRQn,
          EDMA_0_CH8_IRQn, EDMA_0_CH9_IRQn, EDMA_1_CH0_IRQn, EDMA_1_CH10_IRQn, EDMA_1_CH11_IRQn, EDMA_1_CH12_IRQn, EDMA_1_CH13_IRQn, EDMA_1_CH14_IRQn, EDMA_1_CH153_IRQn,
          EDMA_1_CH1_IRQn, EDMA_1_CH2_IRQn, EDMA_1_CH3_IRQn, EDMA_1_CH4_IRQn, EDMA_1_CH5_IRQn, EDMA_1_CH6_IRQn, EDMA_1_CH7_IRQn, EDMA_1_CH8_IRQn, EDMA_1_CH9_IRQn,
          ELS_ERR_IRQn, ELS_IRQn, EMVSIM0_IRQn, EMVSIM1_IRQn, ERM_MULTI_BIT_ERROR_IRQn, ERM_SINGLE_BIT_ERROR_IRQn, ETB0_IRQn, ETHERNET_IRQn, ETHERNET_MACLP_IRQn,
          ETHERNET_PMT_IRQn, EWM0_IRQn, FLEXIO_IRQn, FLEXPWM0_FAULT_IRQn, FLEXPWM0_RELOAD_ERROR_IRQn, FLEXPWM0_SUBMODULE0_IRQn, FLEXPWM0_SUBMODULE1_IRQn, FLEXPWM0_SUBMODULE2_IRQn,
          FLEXPWM0_SUBMODULE3_IRQn, FLEXPWM1_FAULT_IRQn, FLEXPWM1_RELOAD_ERROR_IRQn, FLEXPWM1_SUBMODULE0_IRQn, FLEXPWM1_SUBMODULE1_IRQn, FLEXPWM1_SUBMODULE2_IRQn,
          FLEXPWM1_SUBMODULE3_IRQn, FLEXSPI0_IRQn, FMU0_IRQn, Freqme_IRQn, GDET_IRQn, GPIO00_IRQn, GPIO01_IRQn, GPIO10_IRQn, GPIO11_IRQn, GPIO20_IRQn, GPIO21_IRQn,
          GPIO30_IRQn, GPIO31_IRQn, GPIO40_IRQn, GPIO41_IRQn, GPIO50_IRQn, GPIO51_IRQn, HSCMP0_IRQn, HSCMP1_IRQn, HSCMP2_IRQn, I3C0_IRQn, I3C1_IRQn, ITRC0_IRQn, LPTMR0_IRQn,
          LPTMR1_IRQn, LP_FLEXCOMM0_IRQn, LP_FLEXCOMM1_IRQn, LP_FLEXCOMM2_IRQn, LP_FLEXCOMM3_IRQn, LP_FLEXCOMM4_IRQn, LP_FLEXCOMM5_IRQn, LP_FLEXCOMM6_IRQn, LP_FLEXCOMM7_IRQn,
          LP_FLEXCOMM8_IRQn, LP_FLEXCOMM9_IRQn, MAILBOX_IRQn, MRT0_IRQn, NPU_IRQn, OR_IRQn, OS_EVENT_IRQn, PDM_EVENT_IRQn, PINT0_IRQn, PKC_ERR_IRQn, PKC_IRQn, PLU_IRQn,
          PORT_EFT_IRQn, PQ_IRQn, PUF_IRQn, QDC0_COMPARE_IRQn, QDC0_HOME_IRQn, QDC0_IDX_IRQn, QDC0_WDG_SAB_IRQn, QDC1_COMPARE_IRQn, QDC1_HOME_IRQn, QDC1_IDX_IRQn,
          QDC1_WDG_SAB_IRQn, RTC_IRQn, SAI0_IRQn, SAI1_IRQn, SCG_IRQn, SCT0_IRQn, SEC_HYPERVISOR_CALL_IRQn, SEC_VIO_IRQn, SINC_FILTER_IRQn, SMARTDMA_IRQn, SPC_IRQn,
          TSI_END_OF_SCAN_IRQn, TSI_OUT_OF_SCAN_IRQn, USB0_DCD_IRQn, USB0_FS_IRQn, USB1_HS_IRQn, USB1_HS_PHY_IRQn, USDHC0_IRQn, UTICK0_IRQn, VBAT0_IRQn, WUU_IRQn,
          WWDT0_IRQn, WWDT1_IRQn]}}
    - security: {Secure: {id: [ADC0_IRQn, ADC1_IRQn, BSP32_IRQn, CAN0_IRQn, CAN1_IRQn, CDOG0_IRQn, CDOG1_IRQn, CMC0_IRQn, CTI0_IRQn, CTIMER0_IRQn, CTIMER1_IRQn,
          CTIMER2_IRQn, CTIMER3_IRQn, CTIMER4_IRQn, DAC0_IRQn, DAC1_IRQn, DAC2_IRQn, EDMA_0_CH0_IRQn, EDMA_0_CH10_IRQn, EDMA_0_CH11_IRQn, EDMA_0_CH12_IRQn, EDMA_0_CH13_IRQn,
          EDMA_0_CH14_IRQn, EDMA_0_CH15_IRQn, EDMA_0_CH1_IRQn, EDMA_0_CH2_IRQn, EDMA_0_CH3_IRQn, EDMA_0_CH4_IRQn, EDMA_0_CH5_IRQn, EDMA_0_CH6_IRQn, EDMA_0_CH7_IRQn,
          EDMA_0_CH8_IRQn, EDMA_0_CH9_IRQn, EDMA_1_CH0_IRQn, EDMA_1_CH10_IRQn, EDMA_1_CH11_IRQn, EDMA_1_CH12_IRQn, EDMA_1_CH13_IRQn, EDMA_1_CH14_IRQn, EDMA_1_CH153_IRQn,
          EDMA_1_CH1_IRQn, EDMA_1_CH2_IRQn, EDMA_1_CH3_IRQn, EDMA_1_CH4_IRQn, EDMA_1_CH5_IRQn, EDMA_1_CH6_IRQn, EDMA_1_CH7_IRQn, EDMA_1_CH8_IRQn, EDMA_1_CH9_IRQn,
          ELS_ERR_IRQn, ELS_IRQn, EMVSIM0_IRQn, EMVSIM1_IRQn, ERM_MULTI_BIT_ERROR_IRQn, ERM_SINGLE_BIT_ERROR_IRQn, ETB0_IRQn, ETHERNET_IRQn, ETHERNET_MACLP_IRQn,
          ETHERNET_PMT_IRQn, EWM0_IRQn, FLEXIO_IRQn, FLEXPWM0_FAULT_IRQn, FLEXPWM0_RELOAD_ERROR_IRQn, FLEXPWM0_SUBMODULE0_IRQn, FLEXPWM0_SUBMODULE1_IRQn, FLEXPWM0_SUBMODULE2_IRQn,
          FLEXPWM0_SUBMODULE3_IRQn, FLEXPWM1_FAULT_IRQn, FLEXPWM1_RELOAD_ERROR_IRQn, FLEXPWM1_SUBMODULE0_IRQn, FLEXPWM1_SUBMODULE1_IRQn, FLEXPWM1_SUBMODULE2_IRQn,
          FLEXPWM1_SUBMODULE3_IRQn, FLEXSPI0_IRQn, FMU0_IRQn, Freqme_IRQn, GDET_IRQn, GPIO00_IRQn, GPIO01_IRQn, GPIO10_IRQn, GPIO11_IRQn, GPIO20_IRQn, GPIO21_IRQn,
          GPIO30_IRQn, GPIO31_IRQn, GPIO40_IRQn, GPIO41_IRQn, GPIO50_IRQn, GPIO51_IRQn, HSCMP0_IRQn, HSCMP1_IRQn, HSCMP2_IRQn, I3C0_IRQn, I3C1_IRQn, ITRC0_IRQn, LPTMR0_IRQn,
          LPTMR1_IRQn, LP_FLEXCOMM0_IRQn, LP_FLEXCOMM1_IRQn, LP_FLEXCOMM2_IRQn, LP_FLEXCOMM3_IRQn, LP_FLEXCOMM4_IRQn, LP_FLEXCOMM5_IRQn, LP_FLEXCOMM6_IRQn, LP_FLEXCOMM7_IRQn,
          LP_FLEXCOMM8_IRQn, LP_FLEXCOMM9_IRQn, MAILBOX_IRQn, MRT0_IRQn, NPU_IRQn, OR_IRQn, OS_EVENT_IRQn, PDM_EVENT_IRQn, PINT0_IRQn, PKC_ERR_IRQn, PKC_IRQn, PLU_IRQn,
          PORT_EFT_IRQn, PQ_IRQn, PUF_IRQn, QDC0_COMPARE_IRQn, QDC0_HOME_IRQn, QDC0_IDX_IRQn, QDC0_WDG_SAB_IRQn, QDC1_COMPARE_IRQn, QDC1_HOME_IRQn, QDC1_IDX_IRQn,
          QDC1_WDG_SAB_IRQn, RTC_IRQn, SAI0_IRQn, SAI1_IRQn, SCG_IRQn, SCT0_IRQn, SEC_HYPERVISOR_CALL_IRQn, SEC_VIO_IRQn, SINC_FILTER_IRQn, SMARTDMA_IRQn, SPC_IRQn,
          TSI_END_OF_SCAN_IRQn, TSI_OUT_OF_SCAN_IRQn, USB0_DCD_IRQn, USB0_FS_IRQn, USB1_HS_IRQn, USB1_HS_PHY_IRQn, USDHC0_IRQn, UTICK0_IRQn, VBAT0_IRQn, WUU_IRQn,
          WWDT0_IRQn, WWDT1_IRQn]}}
  - ports:
    - GPIO0: {pin_security: {id: '0', security: s_priv}, pin_security: {id: '1', security: s_priv}, pin_security: {id: '10', security: s_priv}, pin_security: {
        id: '11', security: s_priv}, pin_security: {id: '12', security: s_priv}, pin_security: {id: '13', security: s_priv}, pin_security: {id: '14', security: s_priv},
      pin_security: {id: '15', security: s_priv}, pin_security: {id: '16', security: s_priv}, pin_security: {id: '17', security: s_priv}, pin_security: {id: '18',
        security: s_priv}, pin_security: {id: '19', security: s_priv}, pin_security: {id: '2', security: s_priv}, pin_security: {id: '20', security: s_priv}, pin_security: {
        id: '21', security: s_priv}, pin_security: {id: '22', security: s_priv}, pin_security: {id: '23', security: s_priv}, pin_security: {id: '24', security: s_priv},
      pin_security: {id: '25', security: s_priv}, pin_security: {id: '26', security: s_priv}, pin_security: {id: '27', security: s_priv}, pin_security: {id: '28',
        security: s_priv}, pin_security: {id: '29', security: s_priv}, pin_security: {id: '3', security: s_priv}, pin_security: {id: '30', security: s_priv}, pin_security: {
        id: '31', security: s_priv}, pin_security: {id: '4', security: s_priv}, pin_security: {id: '5', security: s_priv}, pin_security: {id: '6', security: s_priv},
      pin_security: {id: '7', security: s_priv}, pin_security: {id: '8', security: s_priv}, pin_security: {id: '9', security: s_priv}, pin_interrupt_security: {id: '0',
        security: s_priv}, pin_interrupt_security: {id: '1', security: s_priv}}
    - GPIO1: {pin_security: {id: '0', security: s_priv}, pin_security: {id: '1', security: s_priv}, pin_security: {id: '10', security: s_priv}, pin_security: {
        id: '11', security: s_priv}, pin_security: {id: '12', security: s_priv}, pin_security: {id: '13', security: s_priv}, pin_security: {id: '14', security: s_priv},
      pin_security: {id: '15', security: s_priv}, pin_security: {id: '16', security: s_priv}, pin_security: {id: '17', security: s_priv}, pin_security: {id: '18',
        security: s_priv}, pin_security: {id: '19', security: s_priv}, pin_security: {id: '2', security: s_priv}, pin_security: {id: '20', security: s_priv}, pin_security: {
        id: '21', security: s_priv}, pin_security: {id: '22', security: s_priv}, pin_security: {id: '23', security: s_priv}, pin_security: {id: '3', security: s_priv},
      pin_security: {id: '30', security: s_priv}, pin_security: {id: '31', security: s_priv}, pin_security: {id: '4', security: s_priv}, pin_security: {id: '5', security: s_priv},
      pin_security: {id: '6', security: s_priv}, pin_security: {id: '7', security: s_priv}, pin_security: {id: '8', security: s_priv}, pin_security: {id: '9', security: s_priv},
      pin_interrupt_security: {id: '0', security: s_priv}, pin_interrupt_security: {id: '1', security: s_priv}}
    - GPIO2: {pin_security: {id: '0', security: s_priv}, pin_security: {id: '1', security: s_priv}, pin_security: {id: '10', security: s_priv}, pin_security: {
        id: '11', security: s_priv}, pin_security: {id: '2', security: s_priv}, pin_security: {id: '3', security: s_priv}, pin_security: {id: '4', security: s_priv},
      pin_security: {id: '5', security: s_priv}, pin_security: {id: '6', security: s_priv}, pin_security: {id: '7', security: s_priv}, pin_security: {id: '8', security: s_priv},
      pin_security: {id: '9', security: s_priv}, pin_interrupt_security: {id: '0', security: s_priv}, pin_interrupt_security: {id: '1', security: s_priv}}
    - GPIO3: {pin_security: {id: '0', security: s_priv}, pin_security: {id: '1', security: s_priv}, pin_security: {id: '10', security: s_priv}, pin_security: {
        id: '11', security: s_priv}, pin_security: {id: '12', security: s_priv}, pin_security: {id: '13', security: s_priv}, pin_security: {id: '14', security: s_priv},
      pin_security: {id: '15', security: s_priv}, pin_security: {id: '16', security: s_priv}, pin_security: {id: '17', security: s_priv}, pin_security: {id: '18',
        security: s_priv}, pin_security: {id: '19', security: s_priv}, pin_security: {id: '2', security: s_priv}, pin_security: {id: '20', security: s_priv}, pin_security: {
        id: '21', security: s_priv}, pin_security: {id: '22', security: s_priv}, pin_security: {id: '23', security: s_priv}, pin_security: {id: '3', security: s_priv},
      pin_security: {id: '4', security: s_priv}, pin_security: {id: '5', security: s_priv}, pin_security: {id: '6', security: s_priv}, pin_security: {id: '7', security: s_priv},
      pin_security: {id: '8', security: s_priv}, pin_security: {id: '9', security: s_priv}, pin_interrupt_security: {id: '0', security: s_priv}, pin_interrupt_security: {
        id: '1', security: s_priv}}
    - GPIO4: {pin_security: {id: '0', security: s_priv}, pin_security: {id: '1', security: s_priv}, pin_security: {id: '12', security: s_priv}, pin_security: {
        id: '13', security: s_priv}, pin_security: {id: '14', security: s_priv}, pin_security: {id: '15', security: s_priv}, pin_security: {id: '16', security: s_priv},
      pin_security: {id: '17', security: s_priv}, pin_security: {id: '18', security: s_priv}, pin_security: {id: '19', security: s_priv}, pin_security: {id: '2',
        security: s_priv}, pin_security: {id: '20', security: s_priv}, pin_security: {id: '21', security: s_priv}, pin_security: {id: '22', security: s_priv}, pin_security: {
        id: '23', security: s_priv}, pin_security: {id: '3', security: s_priv}, pin_security: {id: '4', security: s_priv}, pin_security: {id: '5', security: s_priv},
      pin_security: {id: '6', security: s_priv}, pin_security: {id: '7', security: s_priv}, pin_interrupt_security: {id: '0', security: s_priv}, pin_interrupt_security: {
        id: '1', security: s_priv}}
    - GPIO5: {pin_security: {id: '0', security: s_priv}, pin_security: {id: '1', security: s_priv}, pin_security: {id: '2', security: s_priv}, pin_security: {id: '3',
        security: s_priv}, pin_security: {id: '4', security: s_priv}, pin_security: {id: '5', security: s_priv}, pin_security: {id: '6', security: s_priv}, pin_security: {
        id: '7', security: s_priv}, pin_security: {id: '8', security: s_priv}, pin_security: {id: '9', security: s_priv}, pin_interrupt_security: {id: '0', security: s_priv},
      pin_interrupt_security: {id: '1', security: s_priv}}
    - pio0: {Non-masked: {id: ['0', '1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28',
          '29', '3', '30', '31', '4', '5', '6', '7', '8', '9']}}
    - pio1: {Non-masked: {id: ['0', '1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '3', '30', '31', '4', '5', '6',
          '7', '8', '9']}}
  - triggers:
    - 0: {triggers_input: {id: input_0, selected: 'false', writable: 'true'}, triggers_input: {id: input_1, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_2, selected: 'false', writable: 'true'}, triggers_input: {id: input_3, selected: 'false', writable: 'true'}, triggers_input: {id: input_4, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_5, selected: 'false', writable: 'true'}, triggers_input: {id: input_6, selected: 'false', writable: 'true'},
      triggers_input: {id: input_7, selected: 'false', writable: 'true'}, triggers_input: {id: input_8, selected: 'false', writable: 'true'}, triggers_input: {id: input_9,
        selected: 'false', writable: 'true'}, triggers_input: {id: input_10, selected: 'false', writable: 'true'}, triggers_input: {id: input_11, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_12, selected: 'false', writable: 'true'}, triggers_input: {id: input_13, selected: 'false', writable: 'true'},
      triggers_input: {id: input_14, selected: 'false', writable: 'true'}, triggers_input: {id: input_15, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_16, selected: 'false', writable: 'true'}, triggers_input: {id: input_17, selected: 'false', writable: 'true'}, triggers_input: {id: input_19, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_20, selected: 'false', writable: 'true'}, triggers_input: {id: input_21, selected: 'false', writable: 'true'},
      triggers_input: {id: input_22, selected: 'false', writable: 'true'}, triggers_input: {id: input_23, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_24, selected: 'false', writable: 'true'}, triggers_input: {id: input_25, selected: 'false', writable: 'true'}, triggers_input: {id: input_26, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_27, selected: 'false', writable: 'true'}, triggers_input: {id: input_28, selected: 'false', writable: 'true'},
      triggers_input: {id: input_29, selected: 'false', writable: 'true'}, triggers_input: {id: input_30, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_31, selected: 'false', writable: 'true'}, triggers_input: {id: input_32, selected: 'false', writable: 'true'}, triggers_input: {id: input_33, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_34, selected: 'false', writable: 'true'}, triggers_input: {id: input_35, selected: 'false', writable: 'true'},
      triggers_input: {id: input_36, selected: 'false', writable: 'true'}, triggers_input: {id: input_37, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_46, selected: 'false', writable: 'true'}, triggers_input: {id: input_47, selected: 'false', writable: 'true'}}
    - 1: {triggers_input: {id: input_0, selected: 'false', writable: 'true'}, triggers_input: {id: input_1, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_2, selected: 'false', writable: 'true'}, triggers_input: {id: input_3, selected: 'false', writable: 'true'}, triggers_input: {id: input_4, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_5, selected: 'false', writable: 'true'}, triggers_input: {id: input_6, selected: 'false', writable: 'true'},
      triggers_input: {id: input_7, selected: 'false', writable: 'true'}, triggers_input: {id: input_8, selected: 'false', writable: 'true'}, triggers_input: {id: input_9,
        selected: 'false', writable: 'true'}, triggers_input: {id: input_10, selected: 'false', writable: 'true'}, triggers_input: {id: input_11, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_12, selected: 'false', writable: 'true'}, triggers_input: {id: input_13, selected: 'false', writable: 'true'},
      triggers_input: {id: input_14, selected: 'false', writable: 'true'}, triggers_input: {id: input_15, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_16, selected: 'false', writable: 'true'}, triggers_input: {id: input_17, selected: 'false', writable: 'true'}, triggers_input: {id: input_19, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_20, selected: 'false', writable: 'true'}, triggers_input: {id: input_21, selected: 'false', writable: 'true'},
      triggers_input: {id: input_22, selected: 'false', writable: 'true'}, triggers_input: {id: input_23, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_24, selected: 'false', writable: 'true'}, triggers_input: {id: input_25, selected: 'false', writable: 'true'}, triggers_input: {id: input_26, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_27, selected: 'false', writable: 'true'}, triggers_input: {id: input_28, selected: 'false', writable: 'true'},
      triggers_input: {id: input_29, selected: 'false', writable: 'true'}, triggers_input: {id: input_30, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_31, selected: 'false', writable: 'true'}, triggers_input: {id: input_32, selected: 'false', writable: 'true'}, triggers_input: {id: input_33, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_34, selected: 'false', writable: 'true'}, triggers_input: {id: input_35, selected: 'false', writable: 'true'},
      triggers_input: {id: input_36, selected: 'false', writable: 'true'}, triggers_input: {id: input_37, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_46, selected: 'false', writable: 'true'}, triggers_input: {id: input_47, selected: 'false', writable: 'true'}}
    - 2: {triggers_input: {id: input_0, selected: 'false', writable: 'true'}, triggers_input: {id: input_1, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_2, selected: 'false', writable: 'true'}, triggers_input: {id: input_3, selected: 'false', writable: 'true'}, triggers_input: {id: input_4, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_5, selected: 'false', writable: 'true'}, triggers_input: {id: input_6, selected: 'false', writable: 'true'},
      triggers_input: {id: input_7, selected: 'false', writable: 'true'}, triggers_input: {id: input_8, selected: 'false', writable: 'true'}, triggers_input: {id: input_9,
        selected: 'false', writable: 'true'}, triggers_input: {id: input_10, selected: 'false', writable: 'true'}, triggers_input: {id: input_11, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_12, selected: 'false', writable: 'true'}, triggers_input: {id: input_13, selected: 'false', writable: 'true'},
      triggers_input: {id: input_14, selected: 'false', writable: 'true'}, triggers_input: {id: input_15, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_16, selected: 'false', writable: 'true'}, triggers_input: {id: input_17, selected: 'false', writable: 'true'}, triggers_input: {id: input_19, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_20, selected: 'false', writable: 'true'}, triggers_input: {id: input_21, selected: 'false', writable: 'true'},
      triggers_input: {id: input_22, selected: 'false', writable: 'true'}, triggers_input: {id: input_23, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_24, selected: 'false', writable: 'true'}, triggers_input: {id: input_25, selected: 'false', writable: 'true'}, triggers_input: {id: input_26, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_27, selected: 'false', writable: 'true'}, triggers_input: {id: input_28, selected: 'false', writable: 'true'},
      triggers_input: {id: input_29, selected: 'false', writable: 'true'}, triggers_input: {id: input_30, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_31, selected: 'false', writable: 'true'}, triggers_input: {id: input_32, selected: 'false', writable: 'true'}, triggers_input: {id: input_33, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_34, selected: 'false', writable: 'true'}, triggers_input: {id: input_35, selected: 'false', writable: 'true'},
      triggers_input: {id: input_36, selected: 'false', writable: 'true'}, triggers_input: {id: input_37, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_46, selected: 'false', writable: 'true'}, triggers_input: {id: input_47, selected: 'false', writable: 'true'}}
    - 3: {triggers_input: {id: input_0, selected: 'false', writable: 'true'}, triggers_input: {id: input_1, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_2, selected: 'false', writable: 'true'}, triggers_input: {id: input_3, selected: 'false', writable: 'true'}, triggers_input: {id: input_4, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_5, selected: 'false', writable: 'true'}, triggers_input: {id: input_6, selected: 'false', writable: 'true'},
      triggers_input: {id: input_7, selected: 'false', writable: 'true'}, triggers_input: {id: input_8, selected: 'false', writable: 'true'}, triggers_input: {id: input_9,
        selected: 'false', writable: 'true'}, triggers_input: {id: input_10, selected: 'false', writable: 'true'}, triggers_input: {id: input_11, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_12, selected: 'false', writable: 'true'}, triggers_input: {id: input_13, selected: 'false', writable: 'true'},
      triggers_input: {id: input_14, selected: 'false', writable: 'true'}, triggers_input: {id: input_15, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_16, selected: 'false', writable: 'true'}, triggers_input: {id: input_17, selected: 'false', writable: 'true'}, triggers_input: {id: input_19, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_20, selected: 'false', writable: 'true'}, triggers_input: {id: input_21, selected: 'false', writable: 'true'},
      triggers_input: {id: input_22, selected: 'false', writable: 'true'}, triggers_input: {id: input_23, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_24, selected: 'false', writable: 'true'}, triggers_input: {id: input_25, selected: 'false', writable: 'true'}, triggers_input: {id: input_26, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_27, selected: 'false', writable: 'true'}, triggers_input: {id: input_28, selected: 'false', writable: 'true'},
      triggers_input: {id: input_29, selected: 'false', writable: 'true'}, triggers_input: {id: input_30, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_31, selected: 'false', writable: 'true'}, triggers_input: {id: input_32, selected: 'false', writable: 'true'}, triggers_input: {id: input_33, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_34, selected: 'false', writable: 'true'}, triggers_input: {id: input_35, selected: 'false', writable: 'true'},
      triggers_input: {id: input_36, selected: 'false', writable: 'true'}, triggers_input: {id: input_37, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_46, selected: 'false', writable: 'true'}, triggers_input: {id: input_47, selected: 'false', writable: 'true'}}
    - 4: {triggers_input: {id: input_0, selected: 'false', writable: 'true'}, triggers_input: {id: input_1, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_2, selected: 'false', writable: 'true'}, triggers_input: {id: input_3, selected: 'false', writable: 'true'}, triggers_input: {id: input_4, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_5, selected: 'false', writable: 'true'}, triggers_input: {id: input_6, selected: 'false', writable: 'true'},
      triggers_input: {id: input_7, selected: 'false', writable: 'true'}, triggers_input: {id: input_8, selected: 'false', writable: 'true'}, triggers_input: {id: input_9,
        selected: 'false', writable: 'true'}, triggers_input: {id: input_10, selected: 'false', writable: 'true'}, triggers_input: {id: input_11, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_12, selected: 'false', writable: 'true'}, triggers_input: {id: input_13, selected: 'false', writable: 'true'},
      triggers_input: {id: input_14, selected: 'false', writable: 'true'}, triggers_input: {id: input_15, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_16, selected: 'false', writable: 'true'}, triggers_input: {id: input_17, selected: 'false', writable: 'true'}, triggers_input: {id: input_19, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_20, selected: 'false', writable: 'true'}, triggers_input: {id: input_21, selected: 'false', writable: 'true'},
      triggers_input: {id: input_22, selected: 'false', writable: 'true'}, triggers_input: {id: input_23, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_24, selected: 'false', writable: 'true'}, triggers_input: {id: input_25, selected: 'false', writable: 'true'}, triggers_input: {id: input_26, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_27, selected: 'false', writable: 'true'}, triggers_input: {id: input_28, selected: 'false', writable: 'true'},
      triggers_input: {id: input_29, selected: 'false', writable: 'true'}, triggers_input: {id: input_30, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_31, selected: 'false', writable: 'true'}, triggers_input: {id: input_32, selected: 'false', writable: 'true'}, triggers_input: {id: input_33, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_34, selected: 'false', writable: 'true'}, triggers_input: {id: input_35, selected: 'false', writable: 'true'},
      triggers_input: {id: input_36, selected: 'false', writable: 'true'}, triggers_input: {id: input_37, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_46, selected: 'false', writable: 'true'}, triggers_input: {id: input_47, selected: 'false', writable: 'true'}}
    - 5: {triggers_input: {id: input_0, selected: 'false', writable: 'true'}, triggers_input: {id: input_1, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_2, selected: 'false', writable: 'true'}, triggers_input: {id: input_3, selected: 'false', writable: 'true'}, triggers_input: {id: input_4, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_5, selected: 'false', writable: 'true'}, triggers_input: {id: input_6, selected: 'false', writable: 'true'},
      triggers_input: {id: input_7, selected: 'false', writable: 'true'}, triggers_input: {id: input_8, selected: 'false', writable: 'true'}, triggers_input: {id: input_9,
        selected: 'false', writable: 'true'}, triggers_input: {id: input_10, selected: 'false', writable: 'true'}, triggers_input: {id: input_11, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_12, selected: 'false', writable: 'true'}, triggers_input: {id: input_13, selected: 'false', writable: 'true'},
      triggers_input: {id: input_14, selected: 'false', writable: 'true'}, triggers_input: {id: input_15, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_16, selected: 'false', writable: 'true'}, triggers_input: {id: input_17, selected: 'false', writable: 'true'}, triggers_input: {id: input_19, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_20, selected: 'false', writable: 'true'}, triggers_input: {id: input_21, selected: 'false', writable: 'true'},
      triggers_input: {id: input_22, selected: 'false', writable: 'true'}, triggers_input: {id: input_23, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_24, selected: 'false', writable: 'true'}, triggers_input: {id: input_25, selected: 'false', writable: 'true'}, triggers_input: {id: input_26, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_27, selected: 'false', writable: 'true'}, triggers_input: {id: input_28, selected: 'false', writable: 'true'},
      triggers_input: {id: input_29, selected: 'false', writable: 'true'}, triggers_input: {id: input_30, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_31, selected: 'false', writable: 'true'}, triggers_input: {id: input_32, selected: 'false', writable: 'true'}, triggers_input: {id: input_33, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_34, selected: 'false', writable: 'true'}, triggers_input: {id: input_35, selected: 'false', writable: 'true'},
      triggers_input: {id: input_36, selected: 'false', writable: 'true'}, triggers_input: {id: input_37, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_46, selected: 'false', writable: 'true'}, triggers_input: {id: input_47, selected: 'false', writable: 'true'}}
    - 6: {triggers_input: {id: input_0, selected: 'false', writable: 'true'}, triggers_input: {id: input_1, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_2, selected: 'false', writable: 'true'}, triggers_input: {id: input_3, selected: 'false', writable: 'true'}, triggers_input: {id: input_4, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_5, selected: 'false', writable: 'true'}, triggers_input: {id: input_6, selected: 'false', writable: 'true'},
      triggers_input: {id: input_7, selected: 'false', writable: 'true'}, triggers_input: {id: input_8, selected: 'false', writable: 'true'}, triggers_input: {id: input_9,
        selected: 'false', writable: 'true'}, triggers_input: {id: input_10, selected: 'false', writable: 'true'}, triggers_input: {id: input_11, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_12, selected: 'false', writable: 'true'}, triggers_input: {id: input_13, selected: 'false', writable: 'true'},
      triggers_input: {id: input_14, selected: 'false', writable: 'true'}, triggers_input: {id: input_15, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_16, selected: 'false', writable: 'true'}, triggers_input: {id: input_17, selected: 'false', writable: 'true'}, triggers_input: {id: input_19, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_20, selected: 'false', writable: 'true'}, triggers_input: {id: input_21, selected: 'false', writable: 'true'},
      triggers_input: {id: input_22, selected: 'false', writable: 'true'}, triggers_input: {id: input_23, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_24, selected: 'false', writable: 'true'}, triggers_input: {id: input_25, selected: 'false', writable: 'true'}, triggers_input: {id: input_26, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_27, selected: 'false', writable: 'true'}, triggers_input: {id: input_28, selected: 'false', writable: 'true'},
      triggers_input: {id: input_29, selected: 'false', writable: 'true'}, triggers_input: {id: input_30, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_31, selected: 'false', writable: 'true'}, triggers_input: {id: input_32, selected: 'false', writable: 'true'}, triggers_input: {id: input_33, selected: 'false',
        writable: 'true'}, triggers_input: {id: input_34, selected: 'false', writable: 'true'}, triggers_input: {id: input_35, selected: 'false', writable: 'true'},
      triggers_input: {id: input_36, selected: 'false', writable: 'true'}, triggers_input: {id: input_37, selected: 'false', writable: 'true'}, triggers_input: {
        id: input_46, selected: 'false', writable: 'true'}, triggers_input: {id: input_47, selected: 'false', writable: 'true'}}
  - regions: [{memory: PROGRAM_FLASH0, security: s_priv, start: '0x00000000', size: '0x00020000'}, {memory: PROGRAM_FLASH0, security: ns_user, start: '0x00020000',
      size: '0x000E0000'}, {memory: PROGRAM_FLASH1, security: ns_user, start: '0x00000000', size: '0x00100000'}, {memory: FlashBank_IFR0, security: ns_user, start: '0x00000000',
      size: '0x00010000'}, {memory: FlashBank_IFR1, security: ns_user, start: '0x00000000', size: '0x00004000'}, {memory: BootROM, security: ns_user, start: '0x00000000',
      size: '0x00040000'}, {memory: SRAMX, security: ns_user, start: '0x00000000', size: '0x00018000'}, {memory: SRAMA, security: s_priv, start: '0x00000000', size: '0x00008000'},
    {memory: SRAMB, security: ns_user, start: '0x00000000', size: '0x00008000'}, {memory: SRAMC, security: ns_user, start: '0x00000000', size: '0x00010000'}, {memory: SRAMD,
      security: ns_user, start: '0x00000000', size: '0x00010000'}, {memory: SRAME, security: ns_user, start: '0x00000000', size: '0x00010000'}, {memory: SRAMF, security: ns_user,
      start: '0x00000000', size: '0x0000C000'}, {memory: SRAMF, security: s_priv, start: '0x0000C000', size: '0x00004000'}, {memory: SRAMG, security: s_priv, start: '0x00000000',
      size: '0x00010000'}, {memory: SRAMH, security: s_priv, start: '0x00000000', size: '0x00008000'}, {memory: FlexSPI0_0, security: ns_user, start: '0x00000000',
      size: '0x10000000'}, {memory: FlexSPI0_1, security: ns_user, start: '0x00000000', size: '0x10000000'}]
  - masters: {ns_user: {id: [COOLFLUXI, DMA3_0, DMA3_1, ETHERNET, NPUO, PKC, PQ, USB_FS, USB_HS, USDHC]}, s_priv: {id: [CPU1, SMARTDMA]}}
  - peripherals: {ns_user: {id: [ADC0, ADC1, AHBSC, AHBSC_ALIAS1, AHBSC_ALIAS2, AHBSC_ALIAS3, BSP32_0, CACHE64_POLSEL0, CAN0_RULE0, CAN0_RULE1, CAN0_RULE2, CAN0_RULE3,
        CAN1_RULE0, CAN1_RULE1, CAN1_RULE2, CAN1_RULE3, CDOG0, CDOG1, CMP0, CMP1, CMP2, CMX_PERFMON0, CMX_PERFMON1, CRC0, CTIMER0, CTIMER1, CTIMER2, CTIMER3, CTIMER4,
        DAC0, DAC1, DAC2, DM0, DMA0_MP, DMA0_TEE_ALIAS0, DMA0_TEE_ALIAS1, DMA0_TEE_ALIAS10, DMA0_TEE_ALIAS11, DMA0_TEE_ALIAS12, DMA0_TEE_ALIAS13, DMA0_TEE_ALIAS14,
        DMA0_TEE_ALIAS15, DMA0_TEE_ALIAS2, DMA0_TEE_ALIAS3, DMA0_TEE_ALIAS4, DMA0_TEE_ALIAS5, DMA0_TEE_ALIAS6, DMA0_TEE_ALIAS7, DMA0_TEE_ALIAS8, DMA0_TEE_ALIAS9,
        DMA1_MP, DMA1_TEE_ALIAS0, DMA1_TEE_ALIAS1, DMA1_TEE_ALIAS10, DMA1_TEE_ALIAS11, DMA1_TEE_ALIAS12, DMA1_TEE_ALIAS13, DMA1_TEE_ALIAS14, DMA1_TEE_ALIAS15, DMA1_TEE_ALIAS2,
        DMA1_TEE_ALIAS3, DMA1_TEE_ALIAS4, DMA1_TEE_ALIAS5, DMA1_TEE_ALIAS6, DMA1_TEE_ALIAS7, DMA1_TEE_ALIAS8, DMA1_TEE_ALIAS9, EIM0, ELS, ELS_ALIAS1, ELS_ALIAS2,
        ELS_ALIAS3, EMVSIM0, EMVSIM1, ENET0, ERM0, EVTG0, EWM0, FLEXIO0, FLEXSPI0, FMU0, FREQME0, GDET1, GPIO0, GPIO0_ALIAS1, GPIO1, GPIO1_ALIAS1, GPIO2, GPIO2_ALIAS1,
        GPIO3, GPIO3_ALIAS1, GPIO4, GPIO4_ALIAS1, GPIO5, GPIO5_ALIAS1, I3C0, I3C1, INPUTMUX0, INTM0, ITRC0, LPTMR0, LPTMR1, LP_FLEXCOMM0, LP_FLEXCOMM1, LP_FLEXCOMM2,
        LP_FLEXCOMM3, LP_FLEXCOMM4, LP_FLEXCOMM5, LP_FLEXCOMM6, LP_FLEXCOMM7, LP_FLEXCOMM8, LP_FLEXCOMM9, MBC, MRT0, NPU, NPX0, OPAMP0, OPAMP1, OPAMP2, OSTIMER0,
        OTPC0, PDM, PINT0, PKC0, PKC_RAM, PLU0, PORT0, PORT1, PORT2, PORT3, PORT4, PORT5, POWERQUAD, PUF, PUF_ALIAS1, PUF_ALIAS2, PUF_ALIAS3, PWM0, PWM1, QDC0, QDC1,
        RTC0, SAI0, SAI1, SCG0, SCT0, SEMA42_0, SFA, SINC0, SPC0, TDET0, TRO0, TSI0, USBDCD0, USBFS0, USBHS1__USBC, USBPHY, USB_RAM, USDHC0, UTICK0, VBAT0, VREF0,
        WUU0, WWDT0, WWDT1]}, s_priv: {id: [MAILBOX, SMARTDMA0, SYSCON0]}}
  - mbcs:
    - mbc:
      - checker_id: 'MBC0'
      - using_global_templates: 'false'
      - slaves: [{id: PROGRAM_FLASH0_mbc, base_region: {start: '0x00000000', size: '0x00100000'}, domains: [{security: s, template: Template_1}]}, {id: PROGRAM_FLASH1_mbc,
          base_region: {start: '0x00000000', size: '0x00100000'}, domains: [{security: ns, template: Template_1}]}, {id: FlashBank_IFR0_mbc, base_region: {start: '0x00000000',
            size: '0x00010000'}, domains: [{security: ns, template: Template_1}]}, {id: FlashBank_IFR1_mbc, base_region: {start: '0x00000000', size: '0x00004000'},
          domains: [{security: ns, template: Template_1}]}]
      - access_templates:
        - template:
          - id: 'Template_1'
          - accesses: {ns_user: '101', ns_priv: '101', s_user: '101', s_priv: '101'}
        - template:
          - id: 'Template_2'
          - locked: 'false'
          - accesses: {ns_user: '000', ns_priv: '000', s_user: '000', s_priv: '000'}
        - template:
          - id: 'Template_3'
          - locked: 'false'
          - accesses: {ns_user: '000', ns_priv: '000', s_user: '000', s_priv: '000'}
        - template:
          - id: 'Template_4'
          - locked: 'false'
          - accesses: {ns_user: '000', ns_priv: '000', s_user: '000', s_priv: '000'}
        - template:
          - id: 'Template_5'
          - locked: 'false'
          - accesses: {ns_user: '000', ns_priv: '000', s_user: '000', s_priv: '000'}
        - template:
          - id: 'Template_6'
          - locked: 'false'
          - accesses: {ns_user: '000', ns_priv: '000', s_user: '000', s_priv: '000'}
        - template:
          - id: 'Template_7'
          - locked: 'false'
          - accesses: {ns_user: '000', ns_priv: '000', s_user: '000', s_priv: '000'}
        - template:
          - id: 'Template_8'
          - locked: 'false'
          - accesses: {ns_user: '000', ns_priv: '000', s_user: '000', s_priv: '000'}
- saus:
  - sau:
    - enabled: 'true'
    - all_non_secure: 'false'
    - generate_code_for_disabled_regions: 'false'
    - regions: [{index: '0', enabled: 'true', security: ns, start: '0x00000000', size: '0x10000000'}, {index: '1', enabled: 'true', security: ns, start: '0x20000000',
        size: '0xC0000000'}, {index: '2', enabled: 'true', security: nsc, start: '0x1001FE00', size: '0x00000200'}, {index: '3', enabled: 'false', security: ns, start: '0x00000000',
        size: '0x00000020'}, {index: '4', enabled: 'false', security: ns, start: '0x00000000', size: '0x00000020'}, {index: '5', enabled: 'false', security: ns, start: '0x00000000',
        size: '0x00000020'}, {index: '6', enabled: 'false', security: ns, start: '0x00000000', size: '0x00000020'}, {index: '7', enabled: 'false', security: ns, start: '0x00000000',
        size: '0x00000020'}]
- global_options:
  - no:
    - id: [_trigger_sources_, GPIO0_PCNS, GPIO0_ICNS, GPIO0_PCNP, GPIO0_ICNP, GPIO1_PCNS, GPIO1_ICNS, GPIO1_PCNP, GPIO1_ICNP, GPIO2_PCNS, GPIO2_ICNS, GPIO2_PCNP,
      GPIO2_ICNP, GPIO3_PCNS, GPIO3_ICNS, GPIO3_PCNP, GPIO3_ICNP, GPIO4_PCNS, GPIO4_ICNS, GPIO4_PCNP, GPIO4_ICNP, GPIO5_PCNS, GPIO5_ICNS, GPIO5_PCNP, GPIO5_ICNP,
      AIRCR_PRIS, AIRCR_BFHFNMINS, AIRCR_SYSRESETREQS, SCR_SLEEPDEEPS, SHCSR_SECUREFAULTENA, NSACR_CP2, NSACR_CP3, NSACR_CP4, NSACR_CP5, NSACR_CP6, NSACR_CP7, CPPWR_SU0,
      CPPWR_SUS0, CPPWR_SU1, CPPWR_SUS1, CPPWR_SU2, CPPWR_SUS2, CPPWR_SU3, CPPWR_SUS3, CPPWR_SU4, CPPWR_SUS4, CPPWR_SU5, CPPWR_SUS5, CPPWR_SU6, CPPWR_SUS6, CPPWR_SU7,
      CPPWR_SUS7, CPPWR_SU10, CPPWR_SUS10, CPPWR_SU11, CPPWR_SUS11, SEC_GPIO_MASK0_LOCK, SEC_GPIO_MASK1_LOCK, SEC_CPU1_INT_MASK0_LOCK, SEC_CPU1_INT_MASK1_LOCK, SEC_CPU1_INT_MASK2_LOCK,
      SEC_CPU1_INT_MASK3_LOCK, SEC_CPU1_INT_MASK4_LOCK, MASTER_SEC_LEVEL_LOCK, CPU0_LOCK_NS_VTOR, CPU0_LOCK_NS_MPU, CPU0_LOCK_S_VTAIRCR, CPU0_LOCK_S_MPU, CPU0_LOCK_SAU,
      CM33_LOCK_REG_LOCK, CPU1_LOCK_NS_VTOR, CPU1_LOCK_NS_MPU, AHB_MISC_CTRL_REG_IDAU_ALL_NS, AHB_MISC_CTRL_REG_DISABLE_VIOLATION_ABORT, AHB_MISC_CTRL_REG_ENABLE_NS_PRIV_CHECK,
      AHB_MISC_CTRL_REG_ENABLE_S_PRIV_CHECK, AHB_MISC_CTRL_REG_WRITE_LOCK]
  - 0:
    - id: [CPACR_CP0, CPACR_CP1, CPACR_CP2, CPACR_CP3, CPACR_CP4, CPACR_CP5, CPACR_CP6, CPACR_CP7]
  - 3:
    - id: [CPACR_CP10, CPACR_CP11]
  - yes:
    - id: [NSACR_CP0, NSACR_CP1, NSACR_CP10, NSACR_CP11, AHB_MISC_CTRL_REG_DISABLE_MASTER_STRICT_MODE, AHB_MISC_CTRL_REG_ENABLE_SECURE_CHECKING]
- user_memory_regions: []
- mpus:
  - mpu:
    - enabled: 'false'
    - id: 's'
    - priv_default_map: 'false'
    - handler_enabled: 'false'
    - generate_code_for_disabled_regions: 'false'
    - attributes: [{index: '0', id: '0', memory_type: device, device: nGnRE, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false', read_allocation: 'false',
            write_allocation: 'false', transientness: 'false'}, {id: outer, cacheable: 'false', write_back: 'false', read_allocation: 'false', write_allocation: 'false',
            transientness: 'false'}]}, {index: '1', id: '1', memory_type: device, device: nGnRE, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false',
            read_allocation: 'false', write_allocation: 'false', transientness: 'false'}, {id: outer, cacheable: 'false', write_back: 'false', read_allocation: 'false',
            write_allocation: 'false', transientness: 'false'}]}, {index: '2', id: '2', memory_type: device, device: nGnRE, regions_properties: [{id: inner, cacheable: 'false',
            write_back: 'false', read_allocation: 'false', write_allocation: 'false', transientness: 'false'}, {id: outer, cacheable: 'false', write_back: 'false',
            read_allocation: 'false', write_allocation: 'false', transientness: 'false'}]}, {index: '3', id: '3', memory_type: device, device: nGnRE, regions_properties: [
          {id: inner, cacheable: 'false', write_back: 'false', read_allocation: 'false', write_allocation: 'false', transientness: 'false'}, {id: outer, cacheable: 'false',
            write_back: 'false', read_allocation: 'false', write_allocation: 'false', transientness: 'false'}]}, {index: '4', id: '4', memory_type: device, device: nGnRE,
        regions_properties: [{id: inner, cacheable: 'false', write_back: 'false', read_allocation: 'false', write_allocation: 'false', transientness: 'false'}, {
            id: outer, cacheable: 'false', write_back: 'false', read_allocation: 'false', write_allocation: 'false', transientness: 'false'}]}, {index: '5', id: '5',
        memory_type: device, device: nGnRE, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false', read_allocation: 'false', write_allocation: 'false',
            transientness: 'false'}, {id: outer, cacheable: 'false', write_back: 'false', read_allocation: 'false', write_allocation: 'false', transientness: 'false'}]},
      {index: '6', id: '6', memory_type: device, device: nGnRE, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false', read_allocation: 'false',
            write_allocation: 'false', transientness: 'false'}, {id: outer, cacheable: 'false', write_back: 'false', read_allocation: 'false', write_allocation: 'false',
            transientness: 'false'}]}, {index: '7', id: '7', memory_type: device, device: nGnRE, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false',
            read_allocation: 'false', write_allocation: 'false', transientness: 'false'}, {id: outer, cacheable: 'false', write_back: 'false', read_allocation: 'false',
            write_allocation: 'false', transientness: 'false'}]}]
    - regions: [{executable: 'false', read_only: 'false', shareability: non_shareable, attributes_index: '0', index: '0', enabled: 'false', security: priv, start: '0x00000000',
        size: '0x00000020'}, {executable: 'false', read_only: 'false', shareability: non_shareable, attributes_index: '0', index: '1', enabled: 'false', security: priv,
        start: '0x00000000', size: '0x00000020'}, {executable: 'false', read_only: 'false', shareability: non_shareable, attributes_index: '0', index: '2', enabled: 'false',
        security: priv, start: '0x00000000', size: '0x00000020'}, {executable: 'false', read_only: 'false', shareability: non_shareable, attributes_index: '0', index: '3',
        enabled: 'false', security: priv, start: '0x00000000', size: '0x00000020'}, {executable: 'false', read_only: 'false', shareability: non_shareable, attributes_index: '0',
        index: '4', enabled: 'false', security: priv, start: '0x00000000', size: '0x00000020'}, {executable: 'false', read_only: 'false', shareability: non_shareable,
        attributes_index: '0', index: '5', enabled: 'false', security: priv, start: '0x00000000', size: '0x00000020'}, {executable: 'false', read_only: 'false', shareability: non_shareable,
        attributes_index: '0', index: '6', enabled: 'false', security: priv, start: '0x00000000', size: '0x00000020'}, {executable: 'false', read_only: 'false', shareability: non_shareable,
        attributes_index: '0', index: '7', enabled: 'false', security: priv, start: '0x00000000', size: '0x00000020'}]
  - mpu:
    - enabled: 'false'
    - id: 'ns'
    - priv_default_map: 'false'
    - handler_enabled: 'false'
    - generate_code_for_disabled_regions: 'false'
    - attributes: [{index: '0', id: '0', memory_type: device, device: nGnRE, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false', read_allocation: 'false',
            write_allocation: 'false', transientness: 'false'}, {id: outer, cacheable: 'false', write_back: 'false', read_allocation: 'false', write_allocation: 'false',
            transientness: 'false'}]}, {index: '1', id: '1', memory_type: device, device: nGnRE, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false',
            read_allocation: 'false', write_allocation: 'false', transientness: 'false'}, {id: outer, cacheable: 'false', write_back: 'false', read_allocation: 'false',
            write_allocation: 'false', transientness: 'false'}]}, {index: '2', id: '2', memory_type: device, device: nGnRE, regions_properties: [{id: inner, cacheable: 'false',
            write_back: 'false', read_allocation: 'false', write_allocation: 'false', transientness: 'false'}, {id: outer, cacheable: 'false', write_back: 'false',
            read_allocation: 'false', write_allocation: 'false', transientness: 'false'}]}, {index: '3', id: '3', memory_type: device, device: nGnRE, regions_properties: [
          {id: inner, cacheable: 'false', write_back: 'false', read_allocation: 'false', write_allocation: 'false', transientness: 'false'}, {id: outer, cacheable: 'false',
            write_back: 'false', read_allocation: 'false', write_allocation: 'false', transientness: 'false'}]}, {index: '4', id: '4', memory_type: device, device: nGnRE,
        regions_properties: [{id: inner, cacheable: 'false', write_back: 'false', read_allocation: 'false', write_allocation: 'false', transientness: 'false'}, {
            id: outer, cacheable: 'false', write_back: 'false', read_allocation: 'false', write_allocation: 'false', transientness: 'false'}]}, {index: '5', id: '5',
        memory_type: device, device: nGnRE, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false', read_allocation: 'false', write_allocation: 'false',
            transientness: 'false'}, {id: outer, cacheable: 'false', write_back: 'false', read_allocation: 'false', write_allocation: 'false', transientness: 'false'}]},
      {index: '6', id: '6', memory_type: device, device: nGnRE, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false', read_allocation: 'false',
            write_allocation: 'false', transientness: 'false'}, {id: outer, cacheable: 'false', write_back: 'false', read_allocation: 'false', write_allocation: 'false',
            transientness: 'false'}]}, {index: '7', id: '7', memory_type: device, device: nGnRE, regions_properties: [{id: inner, cacheable: 'false', write_back: 'false',
            read_allocation: 'false', write_allocation: 'false', transientness: 'false'}, {id: outer, cacheable: 'false', write_back: 'false', read_allocation: 'false',
            write_allocation: 'false', transientness: 'false'}]}]
    - regions: [{executable: 'false', read_only: 'false', shareability: non_shareable, attributes_index: '0', index: '0', enabled: 'false', security: priv, start: '0x00000000',
        size: '0x00000020'}, {executable: 'false', read_only: 'false', shareability: non_shareable, attributes_index: '0', index: '1', enabled: 'false', security: priv,
        start: '0x00000000', size: '0x00000020'}, {executable: 'false', read_only: 'false', shareability: non_shareable, attributes_index: '0', index: '2', enabled: 'false',
        security: priv, start: '0x00000000', size: '0x00000020'}, {executable: 'false', read_only: 'false', shareability: non_shareable, attributes_index: '0', index: '3',
        enabled: 'false', security: priv, start: '0x00000000', size: '0x00000020'}, {executable: 'false', read_only: 'false', shareability: non_shareable, attributes_index: '0',
        index: '4', enabled: 'false', security: priv, start: '0x00000000', size: '0x00000020'}, {executable: 'false', read_only: 'false', shareability: non_shareable,
        attributes_index: '0', index: '5', enabled: 'false', security: priv, start: '0x00000000', size: '0x00000020'}, {executable: 'false', read_only: 'false', shareability: non_shareable,
        attributes_index: '0', index: '6', enabled: 'false', security: priv, start: '0x00000000', size: '0x00000020'}, {executable: 'false', read_only: 'false', shareability: non_shareable,
        attributes_index: '0', index: '7', enabled: 'false', security: priv, start: '0x00000000', size: '0x00000020'}]
- access_templates: {template: {id: Template_1, locked: 'false', accesses: {ns_user: '101', ns_priv: '101', s_user: '101', s_priv: '101'}}, template: {id: Template_2,
    locked: 'false', accesses: {ns_user: '000', ns_priv: '000', s_user: '000', s_priv: '000'}}, template: {id: Template_3, locked: 'false', accesses: {ns_user: '000',
      ns_priv: '000', s_user: '000', s_priv: '000'}}, template: {id: Template_4, locked: 'false', accesses: {ns_user: '000', ns_priv: '000', s_user: '000', s_priv: '000'}},
  template: {id: Template_5, locked: 'false', accesses: {ns_user: '000', ns_priv: '000', s_user: '000', s_priv: '000'}}, template: {id: Template_6, locked: 'false',
    accesses: {ns_user: '000', ns_priv: '000', s_user: '000', s_priv: '000'}}, template: {id: Template_7, locked: 'false', accesses: {ns_user: '000', ns_priv: '000',
      s_user: '000', s_priv: '000'}}, template: {id: Template_8, locked: 'false', accesses: {ns_user: '000', ns_priv: '000', s_user: '000', s_priv: '000'}}}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitTEE
 * Description   : 
 *
 * END ****************************************************************************************************************/

/***********************************************************************************************************************
 * BOARD_INITTEE_BOARD_InitTrustZone function
 **********************************************************************************************************************/
void BOARD_INITTEE_BOARD_InitTrustZone()
{
    /* SAU configuration */
    
    /* Set SAU Control register: Disable SAU and All Secure */
    SAU->CTRL = 0;
    
    /* Set SAU region number */
    SAU->RNR = 0;
    /* Region base address */
    SAU->RBAR = BOARD_INITTEE_SAU_REGION_0_BASE & SAU_RBAR_BADDR_Msk;
    /* Region end address */
    SAU->RLAR = (BOARD_INITTEE_SAU_REGION_0_END & SAU_RLAR_LADDR_Msk)
        | ((0U << SAU_RLAR_NSC_Pos) & SAU_RLAR_NSC_Msk)
        | ((1U << SAU_RLAR_ENABLE_Pos) & SAU_RLAR_ENABLE_Msk);
    
    /* Set SAU region number */
    SAU->RNR = 1;
    /* Region base address */
    SAU->RBAR = BOARD_INITTEE_SAU_REGION_1_BASE & SAU_RBAR_BADDR_Msk;
    /* Region end address */
    SAU->RLAR = (BOARD_INITTEE_SAU_REGION_1_END & SAU_RLAR_LADDR_Msk)
        | ((0U << SAU_RLAR_NSC_Pos) & SAU_RLAR_NSC_Msk)
        | ((1U << SAU_RLAR_ENABLE_Pos) & SAU_RLAR_ENABLE_Msk);
    
    /* Set SAU region number */
    SAU->RNR = 2;
    /* Region base address */
    SAU->RBAR = BOARD_INITTEE_SAU_REGION_2_BASE & SAU_RBAR_BADDR_Msk;
    /* Region end address */
    SAU->RLAR = (BOARD_INITTEE_SAU_REGION_2_END & SAU_RLAR_LADDR_Msk)
        | ((1U << SAU_RLAR_NSC_Pos) & SAU_RLAR_NSC_Msk)
        | ((1U << SAU_RLAR_ENABLE_Pos) & SAU_RLAR_ENABLE_Msk);
    
    /* Force memory writes before continuing */
    __DSB();
    /* Flush and refill pipeline with updated permissions */
    __ISB();
    
    /* Set SAU Control register: Enable SAU and All Secure (applied only if disabled) */
    SAU->CTRL = ((0U << SAU_CTRL_ALLNS_Pos) & SAU_CTRL_ALLNS_Msk)
        | ((1U << SAU_CTRL_ENABLE_Pos) & SAU_CTRL_ENABLE_Msk);
    
    /* AHB configuration */

    /*--------------------------------------------------------------------
     - AHB Security Level Configurations
     -------------------------------------------------------------------*/
    /* Configuration of AHB Secure Controller
       Possible values for every memory sector or peripheral rule:
        0    Non-secure, User access allowed.
        1    Non-secure, Privileged access allowed.
        2    Secure, User access allowed.
        3    Secure, Privileged access allowed.
    */

    /* Security level configuration of MPC checker */
    AHBSC->FLASH00_MEM_RULE[0] = 0x00003333U;
    AHBSC->FLASH00_MEM_RULE[1] = 0;
    AHBSC->FLASH00_MEM_RULE[2] = 0;
    AHBSC->FLASH00_MEM_RULE[3] = 0;
    AHBSC->FLASH01_MEM_RULE[0] = 0;
    AHBSC->FLASH01_MEM_RULE[1] = 0;
    AHBSC->FLASH01_MEM_RULE[2] = 0;
    AHBSC->FLASH01_MEM_RULE[3] = 0;
    AHBSC->FLASH02_MEM_RULE = 0;
    AHBSC->FLASH03_MEM_RULE = 0;
    AHBSC->ROM_MEM_RULE[0] = 0;
    AHBSC->ROM_MEM_RULE[1] = 0;
    AHBSC->ROM_MEM_RULE[2] = 0;
    AHBSC->ROM_MEM_RULE[3] = 0;
    AHBSC->RAMX_MEM_RULE[0] = 0;
    AHBSC->RAMX_MEM_RULE[1] = 0;
    AHBSC->RAMX_MEM_RULE[2] = 0;
    AHBSC->RAMA_MEM_RULE = 0x33333333U;
    AHBSC->RAMB_MEM_RULE = 0;
    AHBSC->RAMC_MEM_RULE[0] = 0;
    AHBSC->RAMC_MEM_RULE[1] = 0;
    AHBSC->RAMD_MEM_RULE[0] = 0;
    AHBSC->RAMD_MEM_RULE[1] = 0;
    AHBSC->RAME_MEM_RULE[0] = 0;
    AHBSC->RAME_MEM_RULE[1] = 0;
    AHBSC->RAMF_MEM_RULE[0] = 0;
    AHBSC->RAMF_MEM_RULE[1] = 0x33330000U;
    AHBSC->RAMG_MEM_RULE[0] = 0x33333333U;
    AHBSC->RAMG_MEM_RULE[1] = 0x33333333U;
    AHBSC->RAMH_MEM_RULE = 0x33333333U;
    AHBSC->FLEXSPI0_REGION0_MEM_RULE[0] = 0;
    AHBSC->FLEXSPI0_REGION0_MEM_RULE[1] = 0;
    AHBSC->FLEXSPI0_REGION0_MEM_RULE[2] = 0;
    AHBSC->FLEXSPI0_REGION0_MEM_RULE[3] = 0;
    AHBSC->FLEXSPI0_REGION1_6_MEM_RULE[0].FLEXSPI0_REGION_MEM_RULE0 = 0;
    AHBSC->FLEXSPI0_REGION1_6_MEM_RULE[1].FLEXSPI0_REGION_MEM_RULE0 = 0;
    AHBSC->FLEXSPI0_REGION1_6_MEM_RULE[2].FLEXSPI0_REGION_MEM_RULE0 = 0;
    AHBSC->FLEXSPI0_REGION1_6_MEM_RULE[3].FLEXSPI0_REGION_MEM_RULE0 = 0;
    AHBSC->FLEXSPI0_REGION1_6_MEM_RULE[4].FLEXSPI0_REGION_MEM_RULE0 = 0;
    AHBSC->FLEXSPI0_REGION1_6_MEM_RULE[5].FLEXSPI0_REGION_MEM_RULE0 = 0;
    AHBSC->FLEXSPI0_REGION7_MEM_RULE[0] = 0;
    AHBSC->FLEXSPI0_REGION7_MEM_RULE[1] = 0;
    AHBSC->FLEXSPI0_REGION7_MEM_RULE[2] = 0;
    AHBSC->FLEXSPI0_REGION7_MEM_RULE[3] = 0;
    AHBSC->FLEXSPI0_REGION8_13_MEM_RULE[0].FLEXSPI0_REGION_MEM_RULE0 = 0;
    AHBSC->FLEXSPI0_REGION8_13_MEM_RULE[1].FLEXSPI0_REGION_MEM_RULE0 = 0;
    AHBSC->FLEXSPI0_REGION8_13_MEM_RULE[2].FLEXSPI0_REGION_MEM_RULE0 = 0;
    AHBSC->FLEXSPI0_REGION8_13_MEM_RULE[3].FLEXSPI0_REGION_MEM_RULE0 = 0;
    AHBSC->FLEXSPI0_REGION8_13_MEM_RULE[4].FLEXSPI0_REGION_MEM_RULE0 = 0;
    AHBSC->FLEXSPI0_REGION8_13_MEM_RULE[5].FLEXSPI0_REGION_MEM_RULE0 = 0;

    /* Security level configuration of PPC checker */
    AHBSC->APB_PERIPHERAL_GROUP0_MEM_RULE0 = 0x30303333U;
    AHBSC->APB_PERIPHERAL_GROUP0_MEM_RULE1 = 0x00003333U;
    AHBSC->APB_PERIPHERAL_GROUP0_MEM_RULE2 = 0x00300000U;
    AHBSC->APB_PERIPHERAL_GROUP0_MEM_RULE3 = 0x33330333U;
    AHBSC->APB_PERIPHERAL_GROUP1_MEM_RULE0 = 0x30033003U;
    AHBSC->APB_PERIPHERAL_GROUP1_MEM_RULE1 = 0x00000333U;
    AHBSC->APB_PERIPHERAL_GROUP1_MEM_RULE2 = 0x33303033U;
    AHBSC->AIPS_BRIDGE_GROUP0_MEM_RULE0 = 0;
    AHBSC->AIPS_BRIDGE_GROUP0_MEM_RULE1 = 0x33300033U;
    AHBSC->AIPS_BRIDGE_GROUP0_MEM_RULE2 = 0;
    AHBSC->AIPS_BRIDGE_GROUP0_MEM_RULE3 = 0x33000300U;
    AHBSC->AHB_PERIPHERAL0_SLAVE_PORT_P12_SLAVE_RULE0 = 0x00000003U;
    AHBSC->AHB_PERIPHERAL0_SLAVE_PORT_P12_SLAVE_RULE1 = 0;
    AHBSC->AHB_PERIPHERAL0_SLAVE_PORT_P12_SLAVE_RULE2 = 0x33333330U;
    AHBSC->AIPS_BRIDGE_GROUP1_MEM_RULE0 = 0;
    AHBSC->AIPS_BRIDGE_GROUP1_MEM_RULE1 = 0;
    AHBSC->AHB_PERIPHERAL1_SLAVE_PORT_P13_SLAVE_RULE0 = 0x00003003U;
    AHBSC->AHB_PERIPHERAL1_SLAVE_PORT_P13_SLAVE_RULE1 = 0;
    AHBSC->AHB_PERIPHERAL1_SLAVE_PORT_P13_SLAVE_RULE2 = 0x33333330U;
    AHBSC->AIPS_BRIDGE_GROUP2_MEM_RULE0 = 0;
    AHBSC->AIPS_BRIDGE_GROUP2_MEM_RULE1 = 0;
    AHBSC->AIPS_BRIDGE_GROUP3_MEM_RULE0 = 0x03033000U;
    AHBSC->AIPS_BRIDGE_GROUP3_MEM_RULE1 = 0x00300300U;
    AHBSC->AIPS_BRIDGE_GROUP3_MEM_RULE2 = 0x00003000U;
    AHBSC->AIPS_BRIDGE_GROUP3_MEM_RULE3 = 0x33000000U;
    AHBSC->AIPS_BRIDGE_GROUP4_MEM_RULE0 = 0x00000330U;
    AHBSC->AIPS_BRIDGE_GROUP4_MEM_RULE1 = 0;
    AHBSC->AIPS_BRIDGE_GROUP4_MEM_RULE2 = 0;
    AHBSC->AIPS_BRIDGE_GROUP4_MEM_RULE3 = 0x33333000U;
    AHBSC->AHB_SECURE_CTRL_PERIPHERAL_RULE0 = 0;

    /* Security level configuration of MBC checker */
    TRDC->MBC_INDEX[0].MBC_MEMN_GLBAC[0] = 0x00005555U;
    TRDC->MBC_INDEX[0].MBC_MEMN_GLBAC[1] = 0;
    TRDC->MBC_INDEX[0].MBC_MEMN_GLBAC[2] = 0;
    TRDC->MBC_INDEX[0].MBC_MEMN_GLBAC[3] = 0;
    TRDC->MBC_INDEX[0].MBC_MEMN_GLBAC[4] = 0;
    TRDC->MBC_INDEX[0].MBC_MEMN_GLBAC[5] = 0;
    TRDC->MBC_INDEX[0].MBC_MEMN_GLBAC[6] = 0;
    TRDC->MBC_INDEX[0].MBC_MEMN_GLBAC[7] = 0;
    TRDC->MBC_INDEX[0].MBC_DOM0_MEM0_BLK_CFG_W[0] = 0;
    TRDC->MBC_INDEX[0].MBC_DOM0_MEM0_BLK_CFG_W[1] = 0;
    TRDC->MBC_INDEX[0].MBC_DOM0_MEM0_BLK_CFG_W[2] = 0;
    TRDC->MBC_INDEX[0].MBC_DOM0_MEM0_BLK_CFG_W[3] = 0;
    TRDC->MBC_INDEX[0].MBC_DOM0_MEM0_BLK_CFG_W[4] = 0x88888888U;
    TRDC->MBC_INDEX[0].MBC_DOM0_MEM0_BLK_CFG_W[5] = 0x88888888U;
    TRDC->MBC_INDEX[0].MBC_DOM0_MEM0_BLK_CFG_W[6] = 0x88888888U;
    TRDC->MBC_INDEX[0].MBC_DOM0_MEM0_BLK_CFG_W[7] = 0x88888888U;
    TRDC->MBC_INDEX[0].MBC_DOM0_MEM1_BLK_CFG_W[0] = 0x88888888U;
    TRDC->MBC_INDEX[0].MBC_DOM0_MEM2_BLK_CFG_W[0] = 0x00008888U;

    /* Security level configuration of masters */
    AHBSC->MASTER_SEC_LEVEL = 0x8000003CU;
    AHBSC->MASTER_SEC_ANTI_POL_REG = 0xBFFFFFC3U;

    /*--------------------------------------------------------------------
     - Pins: Reading GPIO state
     -------------------------------------------------------------------*/
    /* Possible values for every pin:
     *  0b0    Deny
     *  0b1    Allow */
    AHBSC->SEC_GPIO_MASK[0] = 0xFFFFFFFFU;
    AHBSC->SEC_GPIO_MASK[1] = 0xFFFFFFFFU;

    /*--------------------------------------------------------------------
     - Pins: Access protection on IO pins and GPIO port IRQ/DMA requests
     -------------------------------------------------------------------*/
    /* Possible values for security control:
     * *-----------=----------=---------------------=---------------------*
     * | Bit-field |  Config  |   Security access   |  Privilege access   |
     * |   value   |  state   | control (PCNS/ICNS) | control (PCNP/ICNP) |
     * *-----------+----------+---------------------+---------------------*
     * |    0b00   |  S-Priv  |        Secure       |      Privilege      |
     * |    0b01   |  S-User  |        Secure       |    Non-Privilege    |
     * |    0b10   |  NS-Priv |      Non-Secure     |      Privilege      |
     * |    0b11   |  NS-User |      Non-Secure     |    Non-Privilege    |
     * *-----------=----------=---------------------=---------------------*
     * NOTE:
     * Pin Control Non-Secure (PCNS) & Non-Privilege (PCNP) configurable for every IO pin,
     * Interrupt Control Non-Secure (ICNS) & Non-Privilege (ICNP) for requests 0 a 1 only. */
    GPIO0->PCNS = 0;
    GPIO1->PCNS = 0;
    GPIO2->PCNS = 0;
    GPIO3->PCNS = 0;
    GPIO4->PCNS = 0;
    GPIO5->PCNS = 0;
    GPIO0->PCNP = 0;
    GPIO1->PCNP = 0;
    GPIO2->PCNP = 0;
    GPIO3->PCNP = 0;
    GPIO4->PCNP = 0;
    GPIO5->PCNP = 0;
    GPIO0->ICNS = 0;
    GPIO1->ICNS = 0;
    GPIO2->ICNS = 0;
    GPIO3->ICNS = 0;
    GPIO4->ICNS = 0;
    GPIO5->ICNS = 0;
    GPIO0->ICNP = 0;
    GPIO1->ICNP = 0;
    GPIO2->ICNP = 0;
    GPIO3->ICNP = 0;
    GPIO4->ICNP = 0;
    GPIO5->ICNP = 0;

    /*--------------------------------------------------------------------
     - Interrupts: Interrupt handling by Core1
     -------------------------------------------------------------------*/
    /* Possible values for every interrupt:
     *  0b0    Deny
     *  0b1    Allow */
    AHBSC->SEC_CPU1_INT_MASK0 = 0xFFFFFFFFU;
    AHBSC->SEC_CPU1_INT_MASK1 = 0xFFFFFFFFU;
    AHBSC->SEC_CPU1_INT_MASK2 = 0xFFFFFFFFU;
    AHBSC->SEC_CPU1_INT_MASK3 = 0xFFFFFFFFU;
    AHBSC->SEC_CPU1_INT_MASK4 = 0x0FFFFFFFU;

    /*--------------------------------------------------------------------
     - Interrupts: Interrupt security configuration
     -------------------------------------------------------------------*/
    /* Possible values for every interrupt:
     *  0b0    Secure
     *  0b1    Non-secure */
    NVIC->ITNS[0] = 0;
    NVIC->ITNS[1] = 0;
    NVIC->ITNS[2] = 0;
    NVIC->ITNS[3] = 0;
    NVIC->ITNS[4] = 0;

    /* Global Options */
    GPIO0->LOCK = 0;
    GPIO1->LOCK = 0;
    GPIO2->LOCK = 0;
    GPIO3->LOCK = 0;
    GPIO4->LOCK = 0;
    GPIO5->LOCK = 0;
    SCB->AIRCR = (SCB->AIRCR & 0x00009FF7U) | 0x05FA0000U;
    SCB->SCR &= 0xFFFFFFF7U;
    SCB->SHCSR &= 0xFFF7FFFFU;
    SCB->CPACR = 0x00F00000U;
    SCB->NSACR = 0x00000C03U;
    SCnSCB->CPPWR = 0;
    AHBSC->SEC_GP_REG_LOCK = 0xAAAAAAAAU;
    AHBSC->MASTER_SEC_LEVEL = (AHBSC->MASTER_SEC_LEVEL & 0x3FFFFFFFU) | 0x80000000U;
    AHBSC->MASTER_SEC_ANTI_POL_REG = (AHBSC->MASTER_SEC_ANTI_POL_REG & 0x3FFFFFFFU) | 0x80000000U;
    AHBSC->CPU0_LOCK_REG = 0x800002AAU;
    AHBSC->CPU1_LOCK_REG = 0x0000000AU;
    AHBSC->MISC_CTRL_REG = 0x000086A6U;
    AHBSC->MISC_CTRL_DP_REG = 0x000086A6U;
}

/***********************************************************************************************************************
 * BOARD_InitBootTEE function
 **********************************************************************************************************************/
void BOARD_InitBootTEE()
{
    BOARD_INITTEE_BOARD_InitTrustZone();
}
