#
# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

#select profile
CONFIG_MCUX_COMPONENT_middleware.tfm.profile_medium=y
CONFIG_MCUX_COMPONENT_middleware.tfm.profile_medium.additional_sha_algo=n
CONFIG_MCUX_COMPONENT_middleware.tfm.enable_crypto_cipher_module=y

#disable initial attest partition.
CONFIG_MCUX_COMPONENT_middleware.tfm.partition_init_attest=n
CONFIG_MCUX_COMPONENT_middleware.tfm.s.protected_storage=n
CONFIG_MCUX_COMPONENT_middleware.tfm.s.platform_default_crypto_keys=n

#flash config
CONFIG_MCUX_COMPONENT_middleware.tfm.flash_dummy=y


#mbedtls configs
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.crypto=y
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.sgi=y
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.pkc=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.port.only_accelerator_config=y

#drivers
CONFIG_MCUX_COMPONENT_middleware.tfm.lpuart=y
CONFIG_MCUX_COMPONENT_driver.lptmr=y
#CONFIG_MCUX_COMPONENT_component.lptmr_time_stamp_adapter=y
CONFIG_MCUX_COMPONENT_driver.trng=y
CONFIG_MCUX_COMPONENT_driver.trdc_1=y
CONFIG_MCUX_COMPONENT_driver.trdc_soc=y
CONFIG_MCUX_COMPONENT_driver.glikey=y
CONFIG_MCUX_COMPONENT_driver.cdog=y

#include pin_mux board component
CONFIG_MCUX_PRJSEG_project.hw_app_project_core_folder=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=y