CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_COMPONENT_driver.cmsis_enet=n
CONFIG_MCUX_COMPONENT_driver.enet=n
CONFIG_MCUX_COMPONENT_driver.sysmpu=n
CONFIG_MCUX_COMPONENT_driver.mcx_enet=y
CONFIG_MCUX_COMPONENT_component.phytenbaset=y
CONFIG_MCUX_COMPONENT_component.silicon_id=y
