/*
 * Copyright 2026 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*! @name LPSPI1_PCS0 (number 46), FLASH_CS
  @{ */
/* @} */

/*! @name LPSPI1_SIN (number 47), FLASH_SIN
  @{ */
/* @} */

/*! @name LPSPI1_SOUT (number 1), FLASH_SOUT
  @{ */
/* @} */

/*! @name LPSPI1_SCK (number 48), FLASH_SCK
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPSPI1_InitPins(void);

/*! @name PTB0 (number 46), FLASH_CS
  @{ */

/* Symbols to be used with GPIO driver */
#define LPSPI1_DEINITPINS_FLASH_CS_GPIO GPIO_B              /*!<@brief GPIO peripheral base pointer */
#define LPSPI1_DEINITPINS_FLASH_CS_GPIO_PIN_MASK (1U << 0U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LPSPI1_DEINITPINS_FLASH_CS_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LPSPI1_DEINITPINS_FLASH_CS_PIN 0U                   /*!<@brief PORT pin number */
#define LPSPI1_DEINITPINS_FLASH_CS_PIN_MASK (1U << 0U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name PTB1 (number 47), FLASH_SIN
  @{ */

/* Symbols to be used with GPIO driver */
#define LPSPI1_DEINITPINS_FLASH_SIN_GPIO GPIO_B              /*!<@brief GPIO peripheral base pointer */
#define LPSPI1_DEINITPINS_FLASH_SIN_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LPSPI1_DEINITPINS_FLASH_SIN_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LPSPI1_DEINITPINS_FLASH_SIN_PIN 1U                   /*!<@brief PORT pin number */
#define LPSPI1_DEINITPINS_FLASH_SIN_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PTB3 (number 1), FLASH_SOUT
  @{ */

/* Symbols to be used with GPIO driver */
#define LPSPI1_DEINITPINS_FLASH_SOUT_GPIO GPIO_B              /*!<@brief GPIO peripheral base pointer */
#define LPSPI1_DEINITPINS_FLASH_SOUT_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LPSPI1_DEINITPINS_FLASH_SOUT_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LPSPI1_DEINITPINS_FLASH_SOUT_PIN 3U                   /*!<@brief PORT pin number */
#define LPSPI1_DEINITPINS_FLASH_SOUT_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                              /* @} */

/*! @name PTB2 (number 48), FLASH_SCK
  @{ */

/* Symbols to be used with GPIO driver */
#define LPSPI1_DEINITPINS_FLASH_SCK_GPIO GPIO_B              /*!<@brief GPIO peripheral base pointer */
#define LPSPI1_DEINITPINS_FLASH_SCK_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define LPSPI1_DEINITPINS_FLASH_SCK_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define LPSPI1_DEINITPINS_FLASH_SCK_PIN 2U                   /*!<@brief PORT pin number */
#define LPSPI1_DEINITPINS_FLASH_SCK_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void LPSPI1_DeinitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
