
CONFIG_MCUX_COMPONENT_component.rt_gpio_adapter=y
CONFIG_MCUX_COMPONENT_driver.flexcomm_i2c=y
CONFIG_MCUX_COMPONENT_driver.inputmux=y
CONFIG_MCUX_COMPONENT_driver.lpc_dma=y
CONFIG_MCUX_COMPONENT_driver.power=y
CONFIG_MCUX_PRJSEG_project.hw_app_project_folder=y
#The PSRAM size is 8M, not enough for three 720*1280 XRGB8888 buffers.
CONFIG_APP_FB_NUM=2