
CONFIG_MCUX_PRJSEG_module.board.suite=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_folder=n
CONFIG_MCUX_PRJSEG_module.board.boardfile=n
CONFIG_MCUX_COMPONENT_device.boot_header=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_COMPONENT_device.CMSIS=y
CONFIG_MCUX_COMPONENT_driver.clock=y
COMFIG_MCUX_COMPONENT_driver.igpio=y
CONFIG_MCUX_COMPONENT_driver.lpuart=y
CONFIG_MCUX_COMPONENT_driver.iomuxc=y
CONFIG_MCUX_COMPONENT_driver.pmu_1=y
CONFIG_MCUX_COMPONENT_driver.puf=y
CONFIG_MCUX_COMPONENT_driver.lpspi=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.MIMXRT1152_startup=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.src_bm_usb_hid=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.bootsources=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.mem_sdmmc=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.MIMXRT1152_sources=y
CONFIG_MCUX_COMPONENT_middleware.baremetal=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.usb.device.common_header=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.usb.phy=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.usb.device.controller.driver=y
CONFIG_MCUX_COMPONENT_component.lists=y
CONFIG_MCUX_COMPONENT_platform.drivers.memory=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.drv_semc_nand=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.src_startup=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.drv_microseconds_pit=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.mem_flexspi_nor=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.drv_flexspi_nand=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.mem_spi_nand=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.drv_ocotp=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.mem_spi_nor_eeprom=y
CONFIG_MCUX_PRJSEG_frdmimxrt1150_kboot_options=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.usb.device.hid=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.usb.device.stack=y
CONFIG_MCUX_PRJSEG_middleware.mcu-boot.MIMXRT1152_ram_flashloader_linker=y