/*
** ###################################################################
**     Processors:          MCXL255VDF_cm33
**                          MCXL255VLL_cm33
**
**     Compiler:            GNU C Compiler
**     Reference manual:    MCXL25xRM DraftF
**     Version:             rev. 1.0, 2023-01-09
**     Build:               b241211
**
**     Abstract:
**         Linker file for the GNU C Compiler
**
**     Copyright 2016 Freescale Semiconductor, Inc.
**     Copyright 2016-2025 NXP
**     SPDX-License-Identifier: BSD-3-Clause
**
**     http:                 www.nxp.com
**     mail:                 support@nxp.com
**
** ###################################################################
*/

Placeholder, will be fixed when L20 gets support for GCC.
