# Copyright 2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

# Board project basic segments
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_folder=n
CONFIG_MCUX_PRJSEG_project.hw_app_project_folder=y
# end of Board project basic segments
CONFIG_MCUX_COMPONENT_driver.xbar_1=y
CONFIG_MCUX_COMPONENT_driver.pwm=y
CONFIG_MCUX_COMPONENT_driver.endat2p2=y
