#
# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_core_folder=y
CONFIG_MCUX_PRJSEG_module.core1_support=y
CONFIG_MCUX_PRJSEG_module.incbin_for_core=y
CONFIG_MCUX_PRJSEG_module.incbin=n
CONFIG_MCUX_COMPONENT_utility.incbin=y
