# Disable unneeded components
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.lowpower=n # No need for low power in this app
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.platform.lowpower=n
CONFIG_MCUX_PRJSEG_module.board.wireless.board.lowpower=n
CONFIG_MCUX_COMPONENT_component.power_manager_framework=n

CONFIG_MCUX_COMPONENT_middleware.wireless.controller_api=n # CONFIG_MCUX_COMPONENT_middleware.wireless.snps_ll_controller_api used instead

CONFIG_MCUX_COMPONENT_utility.assert=n # Automatically selects debug_console but we want debug_console_lite
CONFIG_MCUX_COMPONENT_utility.debug_console=n
