CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=y
CONFIG_MCUX_COMPONENT_component.lptmr_adapter=y
CONFIG_MCUX_COMPONENT_component.gpio_adapter=y
CONFIG_MCUX_COMPONENT_component.lpi2c_adapter=y
