# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_core_folder=y
CONFIG_MCUX_PRJSEG_module.ezhv_support=y
CONFIG_MCUX_PRJSEG_module.incbin.ezhv=y
CONFIG_MCUX_COMPONENT_driver.ezhv=y