/*
 * Copyright 2025-2026 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/*${header:start}*/
#include "pin_mux.h"
#include "board.h"
#include "app.h"
#include "mcmgr.h"
#include "tzm_config.h"
/*${header:end}*/

/*******************************************************************************
 * Definitions
 ******************************************************************************/
#ifdef BOARD_TZM_SG_IN_SRAM
#if defined(__GNUC__) && !defined(__clang__) && !defined(__ARMCC_VERSION)
/*
 * Secure gateway RAM function and CMSE veneer copy symbols.
 * These symbols are generated by the GCC linker script.
 */
extern uint32_t __sg_ramfunc_load_start__[];
extern uint32_t __sg_ramfunc_start__[];
extern uint32_t __sg_ramfunc_end__[];

extern uint32_t __sgstubs_load_start__[];
extern uint32_t __sgstubs_ram_start__[];
extern uint32_t __sgstubs_ram_end__[];
#endif
#endif /* BOARD_TZM_SG_IN_SRAM */

/*${function:start}*/
void BOARD_InitHardware(void)
{
    BOARD_InitBootPins();
    BOARD_InitBootClocks();

    BOARD_InitDebugConsole();

    BOARD_InitAHBSC();

    /* Powerup all the SRAM partitions. */
    PMC0->PDRUNCFG2 &= ~0x3FFC0000;
    PMC0->PDRUNCFG3 &= ~0x3FFC0000;

    POWER_DisablePD(kPDRUNCFG_SHUT_SENSEP_MAINCLK);
    POWER_ApplyPD();
}

#ifdef BOARD_TZM_SG_IN_SRAM
void BOARD_SystemInitHook(void)
{

#if defined(__GNUC__) && !defined(__clang__) && !defined(__ARMCC_VERSION)
uint32_t *pDataSrc, *pDataDest;


     /* 
     * For TrustZone secure project:
     *
     * 1. .sg_ramfunc:
     *    Real cmse_nonsecure_entry function bodies.
     *    Runtime location: secure SRAM, e.g. 0x1000F000.
     *
     * 2. .gnu.sgstubs:
     *    GCC-generated CMSE SG veneer stubs.
     *    Runtime location: NSC SRAM, e.g. 0x1000FC00.
     *
     * 3. .data:
     *    Normal initialized RAM data.
     *
     * Copy secure entry function bodies from flash LMA to secure SRAM VMA.
     *
     * Linker map example:
     *   .sg_ramfunc VMA 0x1000F000, LMA 0x3800BDA0
     */
    pDataSrc  = (uint32_t *)__sg_ramfunc_load_start__;
    pDataDest = (uint32_t *)__sg_ramfunc_start__;

    while (pDataDest < __sg_ramfunc_end__)
    {
        *pDataDest++ = *pDataSrc++;
    }

    /*
     * Copy GCC CMSE secure gateway stubs from flash LMA to NSC SRAM VMA.
     *
     * Linker map example:
     *   .gnu.sgstubs VMA 0x1000FC00, LMA 0x3800BF40
     */
    pDataSrc  = (uint32_t *)__sgstubs_load_start__;
    pDataDest = (uint32_t *)__sgstubs_ram_start__;

    while (pDataDest < __sgstubs_ram_end__)
    {
        *pDataDest++ = *pDataSrc++;
    }

    /*
     * Ensure copied instructions are visible before any branch/call to them.
     */
    __asm volatile("dsb");
    __asm volatile("isb");
#endif
}
#endif /* BOARD_TZM_SG_IN_SRAM */

#ifdef CORE1_IMAGE_COPY_TO_RAM
uint32_t get_core1_image_size(void)
{
    uint32_t image_size;
#if defined(__CC_ARM) || defined(__ARMCC_VERSION)
    image_size = (uint32_t)&Image$$CORE1_REGION$$Length;
#elif defined(__ICCARM__)
    image_size = (uint32_t)__section_end("__core1_image") - (uint32_t)__section_begin("__core1_image");
#elif defined(__GNUC__)
    image_size = (uint32_t)core1_image_size;
#endif
    return image_size;
}
uint32_t get_core1_ns_image_size(void)
{
    uint32_t image_size;
#if defined(__CC_ARM) || defined(__ARMCC_VERSION)
    image_size = (uint32_t)&Image$$CORE1_NS_REGION$$Length;
#elif defined(__ICCARM__)
    image_size = (uint32_t)__section_end("__core1_ns_image") - (uint32_t)__section_begin("__core1_ns_image");
#elif defined(__GNUC__)
    image_size = (uint32_t)core1_ns_image_size;
#endif
    return image_size;
}
#endif /* CORE1_IMAGE_COPY_TO_RAM */

#ifdef APP_INVALIDATE_CACHE_FOR_SECONDARY_CORE_IMAGE_MEMORY
void invalidate_cache_for_core1_image_memory(uint32_t address, uint32_t size_byte)
{
    XCACHE_CleanInvalidateCacheByRange(address, size_byte);
}
#endif /* APP_INVALIDATE_CACHE_FOR_SECONDARY_CORE_IMAGE_MEMORY */

/*!
 * @brief Application-specific implementation of the SystemInitHook() weak function.
 */
void SystemInitHook(void)
{
    /* The TrustZone should be configured as early as possible after RESET.
       Therefore it is called from SystemInit() during startup. The SystemInitHook()
       weak function overloading is used for this purpose. */
    BOARD_InitBootTEE();

    /* If Veneer is placed in SRAM, then provide board sys_inithook to do the copy function call */
#ifdef BOARD_TZM_SG_IN_SRAM
    BOARD_SystemInitHook();
#endif /*BOARD_TZM_SG_IN_SRAM*/
}
/*${function:end}*/
