/*
 * Copyright 2026 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _LFS_DEFINES_H_
#define _LFS_DEFINES_H_

#include <stddef.h>
#include "FreeRTOS.h"

#define LFS_MALLOC(sz) pvPortMalloc(sz)
#define LFS_FREE(p) vPortFree(p)

#endif /* _LFS_DEFINES_H_ */
