# Copyright 2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_COMPONENT_component.phyyt8521=y
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.ele_s4xx_psa=y
CONFIG_MCUX_COMPONENT_driver.msgintr=y
CONFIG_MCUX_COMPONENT_driver.netc=y
CONFIG_MCUX_COMPONENT_middleware.lwip.netc_ethernetif=y
CONFIG_NETC_PSI="kNETC_ENETC1PSI0"
CONFIG_NETC_MII_MODE="kNETC_RgmiiMode"
CONFIG_NETC_MII_SPEED="kNETC_MiiSpeed1000M"
CONFIG_NETC_USE_SWT=y
CONFIG_NETC_SWT_MAX_PORT_NUM=4
CONFIG_NETC_SWT_USED_PORT_BITMAP=5
CONFIG_NETC_SWT_PSEUDO_PORT=4
