# Copyright 2024-2025 NXP
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

# Board project basic segments
CONFIG_MCUX_HW_DEVICE_PART_MC56F82748VLH=y

CONFIG_MCUX_PRJSEG_module.board.pinmux_project_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_project_folder=y
CONFIG_MCUX_PRJSEG_module.board.clock_board_folder=y

CONFIG_MCUX_HAS_PRJSEG_module.board.peripheral_sel=y
CONFIG_MCUX_PRJSEG_module.use_board_peripheral=y

CONFIG_MCUX_COMPONENT_utility.assert=n
CONFIG_MCUX_COMPONENT_utility.assert_lite=n
CONFIG_MCUX_COMPONENT_utility.assert_lite_min=y

# end of Board project basic segments
