/*
    * Copyright 2024 NXP
    *
    * SPDX-License-Identifier: BSD-3-Clause
*/

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MC56F84789
package_id: MC56F84789VLL
mcu_data: ksdk2_0
processor_version: 0.2412.50
pin_labels:
- {pin_num: '34', pin_signal: GPIOB1/ANB1/CMPB_IN0, label: I_A_adc_b, identifier: I_A_adc_b}
- {pin_num: '36', pin_signal: GPIOB2/ANB2/VREFHB/CMPC_IN3, label: I_C_adc_b, identifier: I_C_adc_b}
- {pin_num: '22', pin_signal: GPIOA0/ANA0/CMPA_IN3/CMPC_O, label: I_A_adc_a, identifier: I_A_adc_a}
- {pin_num: '23', pin_signal: GPIOA1/ANA1/CMPA_IN0, label: I_B_adc_a, identifier: I_B_adc_a}
- {pin_num: '33', pin_signal: GPIOB0/ANB0/CMPB_IN3, label: U_DCbus, identifier: U_DCbus}
- {pin_num: '98', pin_signal: TDO/GPIOD1, label: LED_USER, identifier: LED_G;LED_USER}
- {pin_num: '69', pin_signal: GPIOE1/PWMA_0A, label: PWM_AT, identifier: PWM_AT}
- {pin_num: '68', pin_signal: GPIOE0/PWMA_0B, label: PWM_AB, identifier: PWM_AB}
- {pin_num: '75', pin_signal: GPIOE3/PWMA_1A, label: PWM_BT, identifier: PWM_BT}
- {pin_num: '74', pin_signal: GPIOE2/PWMA_1B, label: PWM_BB, identifier: PWM_BB}
- {pin_num: '83', pin_signal: GPIOE5/PWMA_2A/XB_IN3, label: PWM_CT, identifier: PWM_CT}
- {pin_num: '82', pin_signal: GPIOE4/PWMA_2B/XB_IN2, label: PWM_CB, identifier: PWM_CB}
- {pin_num: '50', pin_signal: GPIOC7/SS0_B/TXD0, label: DRV_SS, identifier: DRV_SS}
- {pin_num: '55', pin_signal: GPIOF0/XB_IN6/TB2/SCLK1, label: DRV_EN, identifier: DRV_EN}
- {pin_num: '6', pin_signal: GPIOF8/RXD0/TB1/CMPD_O, label: DRV_INT, identifier: DRV_INT}
- {pin_num: '94', pin_signal: GPIOF6/TB2/PWMA_3X/PWMB_3X/XB_IN2, label: SW1, identifier: SW1}
- {pin_num: '30', pin_signal: GPIOB4/ANB4/ANC12/CMPC_IN1, label: LED_USER, identifier: LED_USER}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_sim.h"
#include "fsl_gpio.h"
#include "fsl_xbara.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    PWM_Pins();
    ADC_Pins();
    Misc_Pins();
    QDC_Pins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
PWM_Pins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '5', peripheral: PWMA, signal: 'FAULT, 0', pin_signal: GPIOC2/TXD0/TB0/XB_IN2/CLKO0}
  - {pin_num: '69', peripheral: PWMA, signal: 'A, 0', pin_signal: GPIOE1/PWMA_0A, direction: OUTPUT}
  - {pin_num: '68', peripheral: PWMA, signal: 'B, 0', pin_signal: GPIOE0/PWMA_0B, direction: OUTPUT}
  - {pin_num: '75', peripheral: PWMA, signal: 'A, 1', pin_signal: GPIOE3/PWMA_1A, direction: OUTPUT}
  - {pin_num: '74', peripheral: PWMA, signal: 'B, 1', pin_signal: GPIOE2/PWMA_1B, direction: OUTPUT}
  - {pin_num: '83', peripheral: PWMA, signal: 'A, 2', pin_signal: GPIOE5/PWMA_2A/XB_IN3, direction: OUTPUT}
  - {pin_num: '82', peripheral: PWMA, signal: 'B, 2', pin_signal: GPIOE4/PWMA_2B/XB_IN2, direction: OUTPUT}
  - {pin_num: '52', peripheral: QSPI0, signal: MISO, pin_signal: GPIOC8/MISO0/RXD0/XB_IN9}
  - {pin_num: '54', peripheral: QSPI0, signal: MOSI, pin_signal: GPIOC10/MOSI0/XB_IN5/MISO0}
  - {pin_num: '50', peripheral: QSPI0, signal: SS, pin_signal: GPIOC7/SS0_B/TXD0, direction: OUTPUT}
  - {pin_num: '53', peripheral: QSPI0, signal: SCLK, pin_signal: GPIOC9/SCLK0/XB_IN4}
  - {pin_num: '55', peripheral: GPIOF, signal: 'GPIO, 0', pin_signal: GPIOF0/XB_IN6/TB2/SCLK1, direction: OUTPUT, drive_strength: high}
  - {pin_num: '6', peripheral: GPIOF, signal: 'GPIO, 8', pin_signal: GPIOF8/RXD0/TB1/CMPD_O, direction: INPUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : PWM_Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void PWM_Pins(void)
{
    /* GPIOC IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOC);
    /* GPIOE IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOE);
    /* GPIOF IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOF);
    /* Enable peripheral functionality on pin GPIOC2 (pin 5) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin2, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC2 (pin 5) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C2_XB_IN2);
    /* Enable peripheral functionality on pin GPIOC7 (pin 50) */
    GPIO_PinSetPeripheralMode(PWM_PINS_DRV_SS_GPIO, PWM_PINS_DRV_SS_PIN_MASK, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC7 (pin 50) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C7_SS0_B);
    /* Enable peripheral functionality on pin GPIOC8 (pin 52) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin8, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC8 (pin 52) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C8_MISO0);
    /* Enable peripheral functionality on pin GPIOC9 (pin 53) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin9, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC9 (pin 53) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C9_SCLK0);
    /* Enable peripheral functionality on pin GPIOC10 (pin 54) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin10, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC10 (pin 54) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C10_MOSI0);
    /* Enable peripheral functionality on pin GPIOE0 (pin 68) */
    GPIO_PinSetPeripheralMode(PWM_PINS_PWM_AB_GPIO, PWM_PINS_PWM_AB_PIN_MASK, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOE1 (pin 69) */
    GPIO_PinSetPeripheralMode(PWM_PINS_PWM_AT_GPIO, PWM_PINS_PWM_AT_PIN_MASK, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOE2 (pin 74) */
    GPIO_PinSetPeripheralMode(PWM_PINS_PWM_BB_GPIO, PWM_PINS_PWM_BB_PIN_MASK, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOE3 (pin 75) */
    GPIO_PinSetPeripheralMode(PWM_PINS_PWM_BT_GPIO, PWM_PINS_PWM_BT_PIN_MASK, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOE4 (pin 82) */
    GPIO_PinSetPeripheralMode(PWM_PINS_PWM_CB_GPIO, PWM_PINS_PWM_CB_PIN_MASK, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE4 (pin 82) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E4_PWMA_2B);
    /* Enable peripheral functionality on pin GPIOE5 (pin 83) */
    GPIO_PinSetPeripheralMode(PWM_PINS_PWM_CT_GPIO, PWM_PINS_PWM_CT_PIN_MASK, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE5 (pin 83) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E5_PWMA_2A);
    /* GPIO functionality on pin GPIOF0 (pin 55) */
    GPIO_PinSetPeripheralMode(PWM_PINS_DRV_EN_GPIO, PWM_PINS_DRV_EN_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOF8 (pin 6) */
    GPIO_PinSetPeripheralMode(PWM_PINS_DRV_INT_GPIO, PWM_PINS_DRV_INT_PIN_MASK, kGPIO_ModeGpio);

    /* Initialize GPIO functionality on pin GPIOF8 (pin 6)  */
    GPIO_PinSetDirection(PWM_PINS_DRV_INT_GPIO, PWM_PINS_DRV_INT_PIN_MASK, kGPIO_DigitalInput);

    /* Pin configuration on GPIOF0 (pin 55) */
    /* Strength control configuration: High drive strength is configured */
    GPIO_PinSetDriveStrength(PWM_PINS_DRV_EN_GPIO, PWM_PINS_DRV_EN_PIN_MASK, kGPIO_DriveStrengthHigh);

    /* Initialize GPIO functionality on pin GPIOF0 (pin 55)  */
    GPIO_PinWrite(PWM_PINS_DRV_EN_GPIO, PWM_PINS_DRV_EN_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(PWM_PINS_DRV_EN_GPIO, PWM_PINS_DRV_EN_PIN_MASK, kGPIO_DigitalOutput);

    /* Internal Peripheral Select */
    /* Select PWMA Fault 0 Input.: Select PWMA Fault 0 Input, XB_OUT29. */
    SIM_SetInternalPeriInput(SIM, kSIM_PWMAFault0InputIndex, kSIM_PWMAFault0Input_XB_OUT29);

    /* XB_IN2 output assigned to XBARA_IN2 input is connected
     * to XBARA_OUT29 output assigned to PWMA_PWMB_FAULT0 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputXbIn2, kXBARA_OutputPwmaPwmbFault0);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
ADC_Pins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '34', peripheral: ADC, signal: 'ANB, 1', pin_signal: GPIOB1/ANB1/CMPB_IN0}
  - {pin_num: '36', peripheral: ADC, signal: 'ANB, 2', pin_signal: GPIOB2/ANB2/VREFHB/CMPC_IN3}
  - {pin_num: '22', peripheral: ADC, signal: 'ANA, 0', pin_signal: GPIOA0/ANA0/CMPA_IN3/CMPC_O}
  - {pin_num: '23', peripheral: ADC, signal: 'ANA, 1', pin_signal: GPIOA1/ANA1/CMPA_IN0}
  - {pin_num: '33', peripheral: ADC, signal: 'ANB, 0', pin_signal: GPIOB0/ANB0/CMPB_IN3}
  - {peripheral: ADC, signal: 'SYNC, A', pin_signal: PWMA0_OUT_TRIG0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : ADC_Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void ADC_Pins(void)
{
    /* GPIOA IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOA);
    /* GPIOB IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOB);
    /* Enable peripheral functionality on pin GPIOA0 (pin 22) */
    GPIO_PinSetPeripheralMode(ADC_PINS_I_A_adc_a_GPIO, ADC_PINS_I_A_adc_a_PIN_MASK, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOA0 (pin 22) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_A0_ANA0_and_CMPA_IN3);
    /* Enable peripheral functionality on pin GPIOA1 (pin 23) */
    GPIO_PinSetPeripheralMode(ADC_PINS_I_B_adc_a_GPIO, ADC_PINS_I_B_adc_a_PIN_MASK, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB0 (pin 33) */
    GPIO_PinSetPeripheralMode(ADC_PINS_U_DCbus_GPIO, ADC_PINS_U_DCbus_PIN_MASK, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB1 (pin 34) */
    GPIO_PinSetPeripheralMode(ADC_PINS_I_A_adc_b_GPIO, ADC_PINS_I_A_adc_b_PIN_MASK, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB2 (pin 36) */
    GPIO_PinSetPeripheralMode(ADC_PINS_I_C_adc_b_GPIO, ADC_PINS_I_C_adc_b_PIN_MASK, kGPIO_ModePeripheral);
    /* PWMA0_OUT_TRIG0 output assigned to XBARA_IN20 input is connected
     * to XBARA_OUT12 output assigned to ADCA_SYNC */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputPwma0OutTrig0, kXBARA_OutputAdcaSync);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
Misc_Pins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '62', peripheral: QSCI1, signal: TXD, pin_signal: GPIOF4/TXD1/XB_OUT8}
  - {pin_num: '63', peripheral: QSCI1, signal: RXD, pin_signal: GPIOF5/RXD1/XB_OUT9}
  - {pin_num: '94', peripheral: GPIOF, signal: 'GPIO, 6', pin_signal: GPIOF6/TB2/PWMA_3X/PWMB_3X/XB_IN2, direction: INPUT, gpio_interrupt: gpioIrqFallingEdge}
  - {pin_num: '30', peripheral: GPIOB, signal: 'GPIO, 4', pin_signal: GPIOB4/ANB4/ANC12/CMPC_IN1, direction: OUTPUT, gpio_init_state: 'true'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : Misc_Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void Misc_Pins(void)
{
    /* GPIOB IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOB);
    /* GPIOF IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOF);
    /* GPIO functionality on pin GPIOB4 (pin 30) */
    GPIO_PinSetPeripheralMode(MISC_PINS_LED_USER_GPIO, MISC_PINS_LED_USER_PIN_MASK, kGPIO_ModeGpio);
    /* Enable peripheral functionality on pin GPIOF4 (pin 62) */
    GPIO_PinSetPeripheralMode(GPIOF, kGPIO_Pin4, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOF4 (pin 62) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_F4_TXD1);
    /* Enable peripheral functionality on pin GPIOF5 (pin 63) */
    GPIO_PinSetPeripheralMode(GPIOF, kGPIO_Pin5, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOF5 (pin 63) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_F5_RXD1);
    /* GPIO functionality on pin GPIOF6 (pin 94) */
    GPIO_PinSetPeripheralMode(MISC_PINS_SW1_GPIO, MISC_PINS_SW1_PIN_MASK, kGPIO_ModeGpio);

    /* Initialize GPIO functionality on pin GPIOF6 (pin 94)  */
    GPIO_PinSetDirection(MISC_PINS_SW1_GPIO, MISC_PINS_SW1_PIN_MASK, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOB4 (pin 30)  */
    GPIO_PinWrite(MISC_PINS_LED_USER_GPIO, MISC_PINS_LED_USER_PIN_MASK, kGPIO_OutputHigh);
    GPIO_PinSetDirection(MISC_PINS_LED_USER_GPIO, MISC_PINS_LED_USER_PIN_MASK, kGPIO_DigitalOutput);

    /* Interrupt configuration on GPIOF6 (pin 94): Interrupt on falling edge */
    GPIO_PinSetInterruptConfig(MISC_PINS_SW1_GPIO, MISC_PINS_SW1_PIN_MASK, kGPIO_InterruptFallingEdge);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
QDC_Pins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '12', peripheral: QDC, signal: 'PHASE, A', pin_signal: GPIOC4/TA1/CMPB_O/XB_IN8/EWM_OUT_B}
  - {pin_num: '76', peripheral: QDC, signal: 'PHASE, B', pin_signal: GPIOC13/TA3/XB_IN6/EWM_OUT_B}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : QDC_Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void QDC_Pins(void)
{
    /* GPIOC IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOC);
    /* Enable peripheral functionality on pin GPIOC4 (pin 12) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin4, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC4 (pin 12) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C4_XB_IN8);
    /* Enable peripheral functionality on pin GPIOC13 (pin 76) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin13, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC13 (pin 76) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C13_XB_IN6);
    /* XB_IN8 output assigned to XBARA_IN8 input is connected
     * to XBARA_OUT44 output assigned to QDC_PHA */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputXbIn8, kXBARA_OutputQdcPha);
    /* XB_IN6 output assigned to XBARA_IN6 input is connected
     * to XBARA_OUT45 output assigned to QDC_PHB */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputXbIn6, kXBARA_OutputQdcPhb);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
