CONFIG_MCUX_HW_DEVICE_PART_MIMXRT2663CVVAA=y

CONFIG_MCUX_PRJSEG_project.hw_app_project_folder=y

CONFIG_MCUX_COMPONENT_board.boot_header=y

CONFIG_MCUX_PRJSEG_module.board.clock_board_folder=y

#
# In bring up phase, using pinmux_customize_folder, which select 
#   - pin_mux_fpga implementation
#   - macro RT2660_PRESILICON_DEVELOPMENT = 1
# In post-silicon phase please switch back to the common pinmux_board_folder
# 
# CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=y
