# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=y
CONFIG_MCUX_ABSTRACT_COMPONENT_component_expander=y
CONFIG_MCUX_COMPONENT_driver.pca9555=y
CONFIG_MCUX_COMPONENT_driver.pcal6524=y
CONFIG_MCUX_COMPONENT_driver.st7796s=y
