# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_COMPONENT_component.power_manager_framework=y
CONFIG_MCUX_COMPONENT_driver.common=y
CONFIG_MCUX_COMPONENT_driver.lptmr=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=y
