CONFIG_MCUX_PRJSEG_module.board.clock_customize_folder=y
CONFIG_MCUX_PRJSEG_module.pmic_support=y
CONFIG_MCUX_PRJSEG_module.core1_support=y
CONFIG_MCUX_COMPONENT_driver.dsp=y
CONFIG_MCUX_COMPONENT_driver.lpflexcomm_lpi2c=y
CONFIG_MCUX_COMPONENT_driver.inputmux=y
CONFIG_MCUX_COMPONENT_driver.inputmux_connections=y
CONFIG_MCUX_COMPONENT_driver.pca9422=y
CONFIG_MCUX_COMPONENT_driver.power=y
CONFIG_MCUX_COMPONENT_driver.mu1=y
CONFIG_MCUX_COMPONENT_driver.sema42=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_core_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_project_core_folder=y
CONFIG_MCUX_COMPONENT_utility.incbin=y
CONFIG_MCUX_PRJSEG_module.incbin_for_core=y
CONFIG_MCUX_COMPONENT_driver.romapi=y
CONFIG_MCUX_COMPONENT_driver.pvts=y
CONFIG_MCUX_COMPONENT_driver.ostimer=y
CONFIG_MCUX_COMPONENT_driver.utick=y
CONFIG_MCUX_COMPONENT_driver.lpadc=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.heap_4=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.cm33_non_trustzone=y
CONFIG_configUSE_TICKLESS_IDLE=1
CONFIG_configTICK_RATE_HZ=1000
CONFIG_configOVERRIDE_DEFAULT_TICK_CONFIGURATION=1
CONFIG_configLPTMR_CLOCK_HZ=1000
CONFIG_configMINIMAL_STACK_SIZE=128
CONFIG_configTOTAL_HEAP_SIZE=15360
CONFIG_MCUX_COMPONENT_component.coremark=y