
CONFIG_MCUX_COMPONENT_driver.puf=y
CONFIG_MCUX_COMPONENT_middleware.baremetal=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.MIMXRT1176_sources=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.MIMXRT1176_startup=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.bootsources=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.drv_flexspi_nand=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.drv_microseconds_pit=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.drv_ocotp=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.drv_semc_nand=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.mem_flexspi_nor=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.mem_sdmmc=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.mem_spi_nand=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.mem_spi_nor_eeprom=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.src_bm_usb_hid=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.src_startup=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.usb.device.controller.driver=y
CONFIG_MCUX_COMPONENT_middleware.usb.device.common_header=y
CONFIG_MCUX_COMPONENT_middleware.usb.phy=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y