#
# Copyright 2024 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

mcux_add_xtensa_configuration(
    CC "-DXA_MP3_DECODER=1 -DXA_AAC_DECODER=1 -DXA_VORBIS_DECODER=1 -DXA_OPUS_ENCODER=1 -DXA_OPUS_DECODER=1 -DXA_SBC_ENCODER=1 -DXA_SBC_DECODER=1 -DXA_PCM_GAIN=1 -DXA_SRC_PP_FX=1 -DXA_RENDERER=1 -DSDK_DEBUGCONSOLE=1 -DXOS_CLOCK_FREQ=198000000 -DXF_CORE_ID=0 -DXF_CFG_CORES_NUM=1 -DRENDERER_I2S"
)