CONFIG_FLASH_DEFAULT_APP_OFFSET=0x24000
CONFIG_I2C_RETRY_TIMES=0x10
CONFIG_LV_ATTRIBUTE_MEM_ALIGN="__attribute__((aligned(LV_ATTRIBUTE_MEM_ALIGN_SIZE)))"
CONFIG_LV_ATTRIBUTE_LARGE_CONST="__attribute__((section(\"DataQuickAccess\")))"

