CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=y
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.sgi=y
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.pkc=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.port.psa_crypto_config=y