CONFIG_LV_USE_CLIB_STRING=y
CONFIG_LV_MEM_SIZE_KILOBYTES=384
CONFIG_LV_MEM_POOL_EXPAND_SIZE_KILOBYTES=4096
CONFIG_MCUX_COMPONENT_middleware.vglite=y
CONFIG_MCUX_COMPONENT_driver.fbdev=y
CONFIG_MCUX_PRJSEG_module.board.vglite_support=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.config=y
CONFIG_configTOTAL_HEAP_SIZE=102400
CONFIG_configTICK_RATE_HZ=1000
CONFIG_configMAX_PRIORITIES=18
CONFIG_configUSE_TICK_HOOK=y
CONFIG_LV_DRAW_LAYER_SIMPLE_BUF_SIZE=24576
CONFIG_LV_ATTRIBUTE_MEM_ALIGN="__attribute__((aligned(LV_ATTRIBUTE_MEM_ALIGN_SIZE)))"
CONFIG_LV_USE_SYSMON=y
CONFIG_LV_SYSMON_GET_IDLE="getIdleTaskPct"
CONFIG_LV_VG_LITE_USE_GPU_INIT=y
CONFIG_LV_VG_LITE_GRAD_CACHE_CNT=8
CONFIG_LV_VG_LITE_STROKE_CACHE_CNT=32
CONFIG_LV_VG_LITE_DISABLE_VLC_OP_CLOSE=y
CONFIG_LV_VG_LITE_DISABLE_LINEAR_GRADIENT_EXT=y
CONFIG_LV_USE_VECTOR_GRAPHIC=y
CONFIG_LV_CACHE_DEF_SIZE=1048576
CONFIG_LV_IMAGE_HEADER_CACHE_DEF_CNT=128
CONFIG_LV_GRADIENT_MAX_STOPS=2
CONFIG_LV_COLOR_MIX_ROUND_OFS=0
CONFIG_LV_USE_FLOAT=y
CONFIG_LV_USE_MATRIX=y
CONFIG_LV_BIN_DECODER_RAM_LOAD=y
CONFIG_LV_USE_SNAPSHOT=y
CONFIG_LV_USE_PERF_MONITOR_LOG_MODE=y
CONFIG_LV_DEMO_BENCHMARK_ALIGNED_FONTS=y
CONFIG_LV_OBJ_STYLE_CACHE=y
