CONFIG_MCUX_COMPONENT_driver.ecat=y
CONFIG_MCUX_COMPONENT_driver.lpi2c=y
CONFIG_MCUX_COMPONENT_driver.xbar_1=y
CONFIG_MCUX_COMPONENT_driver.romapi=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_core_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_project_folder=y