test_image_display
test_image_convert_display
test_image_ultraface
test_image_mobilenet
test_image_persondetect
test_image_switch_model
test_image_nanodet
test_image_switch_convert_display
test_image_jpeg_convert_display
test_camera_convert_label_rect_display
test_virtual_dual_camera_view --sysbuild
test_mc_image_convert_display --sysbuild
