# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

# enable HDI to configure radio mode
CONFIG_MCUX_COMPONENT_middleware.wireless.framework_private=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework_private.hdi=y
