/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MIMXRT798S
package_id: MIMXRT798SGVKB
mcu_data: ksdk2_0
processor_version: 0.0.0
pin_labels:
- {pin_num: H7, pin_signal: PIO3_7, label: WL_RST, identifier: WL_RST}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_iopctl.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPinsWifi
 * Description   : Configures Wi-Fi module pin routing (USDHC1 + WL_RST).
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 (Core #0) */
void BOARD_InitPinsWifi(void)
{
    /* Reset IOPCTL0 module */
    RESET_ClearPeripheralReset(kIOPCTL0_RST_SHIFT_RSTn);
    /* Reset IOPCTL2 module */
    RESET_ClearPeripheralReset(kIOPCTL2_RST_SHIFT_RSTn);

    /* Configure WL_RST (PIO3_7) as GPIO output, init LOW */
    GPIO3->PDDR = ((GPIO3->PDDR &
                    (~(GPIO_PDDR_PDD7_MASK)))
                   | GPIO_PDDR_PDD7(PDDR_PDD7_pdd1));

    GPIO3->PDOR = ((GPIO3->PDOR &
                    (~(GPIO_PDOR_PDO7_MASK)))
                   | GPIO_PDOR_PDO7(PDOR_PDO7_pdo0));

    const uint32_t WL_RST = (/* Pin is configured as GPIO3_IO7 */
                             IOPCTL_PIO_FUNC0 |
                             IOPCTL_PIO_PUPD_DI |
                             IOPCTL_PIO_PULLDOWN_EN |
                             IOPCTL_PIO_INBUF_DI |
                             IOPCTL_PIO_PSEDRAIN_DI |
                             IOPCTL_PIO_INV_DI |
                             IOPCTL_PIO_DRIVE_100OHM);
    /* PORT3 PIN7 (coords: H7) is configured as GPIO3_IO7 */
    IOPCTL_PinMuxSet(BOARD_INITPINSWIFI_WL_RST_PORT, BOARD_INITPINSWIFI_WL_RST_PIN, WL_RST);

    const uint32_t port7_pin17_config = (/* Pin is configured as USDHC1_CLK */
                                         IOPCTL_PIO_FUNC1 |
                                         IOPCTL_PIO_PUPD_EN |
                                         IOPCTL_PIO_PULLUP_EN |
                                         IOPCTL_PIO_INBUF_EN |
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         IOPCTL_PIO_INV_DI |
                                         IOPCTL_PIO_DRIVE_33OHM);
    /* PORT7 PIN17 (coords: L17) is configured as USDHC1_CLK */
    IOPCTL_PinMuxSet(7U, 17U, port7_pin17_config);

    const uint32_t port7_pin18_config = (/* Pin is configured as USDHC1_CMD */
                                         IOPCTL_PIO_FUNC1 |
                                         IOPCTL_PIO_PUPD_EN |
                                         IOPCTL_PIO_PULLUP_EN |
                                         IOPCTL_PIO_INBUF_EN |
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         IOPCTL_PIO_INV_DI |
                                         IOPCTL_PIO_DRIVE_33OHM);
    /* PORT7 PIN18 (coords: L16) is configured as USDHC1_CMD */
    IOPCTL_PinMuxSet(7U, 18U, port7_pin18_config);

    const uint32_t port7_pin19_config = (/* Pin is configured as USDHC1_DATA0 */
                                         IOPCTL_PIO_FUNC1 |
                                         IOPCTL_PIO_PUPD_EN |
                                         IOPCTL_PIO_PULLUP_EN |
                                         IOPCTL_PIO_INBUF_EN |
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         IOPCTL_PIO_INV_DI |
                                         IOPCTL_PIO_DRIVE_33OHM);
    /* PORT7 PIN19 (coords: M17) is configured as USDHC1_DATA0 */
    IOPCTL_PinMuxSet(7U, 19U, port7_pin19_config);

    const uint32_t port7_pin20_config = (/* Pin is configured as USDHC1_DATA1 */
                                         IOPCTL_PIO_FUNC1 |
                                         IOPCTL_PIO_PUPD_EN |
                                         IOPCTL_PIO_PULLUP_EN |
                                         IOPCTL_PIO_INBUF_EN |
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         IOPCTL_PIO_INV_DI |
                                         IOPCTL_PIO_DRIVE_33OHM);
    /* PORT7 PIN20 (coords: M18) is configured as USDHC1_DATA1 */
    IOPCTL_PinMuxSet(7U, 20U, port7_pin20_config);

    const uint32_t port7_pin21_config = (/* Pin is configured as USDHC1_DATA2 */
                                         IOPCTL_PIO_FUNC1 |
                                         IOPCTL_PIO_PUPD_EN |
                                         IOPCTL_PIO_PULLUP_EN |
                                         IOPCTL_PIO_INBUF_EN |
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         IOPCTL_PIO_INV_DI |
                                         IOPCTL_PIO_DRIVE_33OHM);
    /* PORT7 PIN21 (coords: K18) is configured as USDHC1_DATA2 */
    IOPCTL_PinMuxSet(7U, 21U, port7_pin21_config);

    const uint32_t port7_pin22_config = (/* Pin is configured as USDHC1_DATA3 */
                                         IOPCTL_PIO_FUNC1 |
                                         IOPCTL_PIO_PUPD_EN |
                                         IOPCTL_PIO_PULLUP_EN |
                                         IOPCTL_PIO_INBUF_EN |
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         IOPCTL_PIO_INV_DI |
                                         IOPCTL_PIO_DRIVE_33OHM);
    /* PORT7 PIN22 (coords: K17) is configured as USDHC1_DATA3 */
    IOPCTL_PinMuxSet(7U, 22U, port7_pin22_config);

}
