/*
 * Copyright 2025 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define PCR_DSE1_dse10 0x00u /*!<@brief Drive Strength Enable: Normal */
#define PCR_IBE_ibe0 0x00u   /*!<@brief Input Buffer Enable: Disables */
#define PCR_INV_inv0 0x00u   /*!<@brief Invert Input: Does not invert */
#define PCR_ODE_ode0 0x00u   /*!<@brief Open Drain Enable: Disables */
#define PCR_PE_pe0 0x00u     /*!<@brief Pull Enable: Disables */
#define PCR_PFE_pfe0 0x00u   /*!<@brief Passive Filter Enable: Disables */
#define PCR_PV_pv0 0x00u     /*!<@brief Pull Value: Low */
#define PCR_SRE_sre0 0x00u   /*!<@brief Slew Rate Enable: Fast */


/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
