

CONFIG_MCUX_COMPONENT_middleware.freertos-kernel=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.extension=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.config=y
CONFIG_MCUX_PRJSEG_middleware.freertos-kernel.generated_config=y
CONFIG_configRECORD_STACK_HIGH_ADDRESS=y
CONFIG_configSUPPORT_STATIC_ALLOCATION=y
CONFIG_configKERNEL_PROVIDED_STATIC_MEMORY=y
CONFIG_configCHECK_FOR_STACK_OVERFLOW=y
CONFIG_configGENERATE_RUN_TIME_STATS=n
CONFIG_FREERTOS_USE_CUSTOM_CONFIG_FRAGMENT=y

CONFIG_MCUX_MISC_middleware.ispsdk=y
CONFIG_ISP_SDK_CAMERA_COUNT=1

CONFIG_MCUX_COMPONENT_middleware.ispsdk.cca.ccfselection.neo_control=y
#CONFIG_MCUX_COMPONENT_middleware.ispsdk.cca.ccfselection.ccf_custom=y

#CONFIG_MCUX_COMPONENT_middleware.ispsdk.ccf.lt=y
#To activate Ethernet you need to reconfigure system with prj_eth.conf overlay (add -DISPSDK_ENABLE_ETH=1 to west build command)
#CONFIG_MCUX_COMPONENT_middleware.ispsdk.ccf.lt.transport.eth=y
#CONFIG_MCUX_COMPONENT_middleware.ispsdk.ccf.lt.transport.usb=y

#CONFIG_MCUX_COMPONENT_middleware.ispsdk.stdout.usb=y

CONFIG_MCUX_COMPONENT_middleware.ispsdk.display_task=y
CONFIG_MCUX_COMPONENT_middleware.ispsdk.camera_task=y
CONFIG_MCUX_MISC_middleware.ispsdk.example.camera_selection.ovx3c=y
CONFIG_MCUX_COMPONENT_middleware.ispsdk.isp_initial_cfg=y
CONFIG_MCUX_COMPONENT_middleware.ispsdk.neo_control.tuning_database=y

CONFIG_MCUX_COMPONENT_component.rgpio_adapter=y
CONFIG_MCUX_COMPONENT_driver.camera_csr=y
CONFIG_MCUX_COMPONENT_driver.mipi_csi2rx_dwc=y
CONFIG_MCUX_COMPONENT_driver.camera-device-ap1302=y
CONFIG_MCUX_COMPONENT_driver.camera-receiver-isi=y

CONFIG_MCUX_PRJSEG_config.arm.suppress.warn_as_error=y