# wpa_supplicant
CONFIG_MCUX_COMPONENT_component.els_pkc=y
CONFIG_MCUX_COMPONENT_component.els_pkc.rsa=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls.port.els=y
CONFIG_MCUX_DEPENDENCY_COMPONENT_middleware.mbedtls_DEPEND_ANYOF_2_OPTION_5=y

CONFIG_MBEDTLS_USER_CONFIG_FILE="\"wpa_supp_els_pkc_mbedtls_config.h\""