# Copyright 2024-2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_COMPONENT_component.phyksz8081=y
CONFIG_MCUX_COMPONENT_driver.enet=y
CONFIG_MCUX_COMPONENT_middleware.lwip.kinetis_ethernetif=y
CONFIG_MCUX_COMPONENT_utility.assert=y
CONFIG_MCUX_PRJSEG_project.hw_app_project_folder=y
CONFIG_ENET_RXBUFF_NUM="10"
CONFIG_ENET_RXBD_NUM=5
CONFIG_TCP_WND="5840"
CONFIG_PBUF_POOL_SIZE=4
