CONFIG_MCUX_COMPONENT_driver.enet=y
CONFIG_MCUX_COMPONENT_component.phyyt8521=y
CONFIG_MCUX_COMPONENT_middleware.lwip.kinetis_ethernetif=y
CONFIG_ENET_RXBUFF_NUM="14"
CONFIG_ENET_RXBD_NUM=9
CONFIG_CHECKSUM_GEN_UDP=n
CONFIG_CHECKSUM_GEN_TCP=n
CONFIG_CHECKSUM_GEN_ICMP=n
CONFIG_CHECKSUM_CHECK_UDP=n
CONFIG_CHECKSUM_CHECK_TCP=n
CONFIG_CHECKSUM_CHECK_ICMP=n
