# Supported Wi-Fi boards (modules):
CONFIG_MCUX_COMPONENT_component.wifi_bt_module.IW61X=y
CONFIG_MCUX_COMPONENT_component.wifi_bt_module.board_murata_2ll_m2=y
#CONFIG_MCUX_COMPONENT_component.wifi_bt_module.board_murata_2el_m2=y

#CONFIG_MCUX_COMPONENT_component.wifi_bt_module.88W8987=y
#CONFIG_MCUX_COMPONENT_component.wifi_bt_module.board_murata_1zm_m2=y

#CONFIG_MCUX_COMPONENT_component.wifi_bt_module.IW416=y
#CONFIG_MCUX_COMPONENT_component.wifi_bt_module.board_murata_1xk_m2=y

# firmware download
CONFIG_MCUX_COMPONENT_component.wifi_bt_module.wifi_fw=y
CONFIG_MCUX_COMPONENT_component.wifi_bt_module.bt_only_fw=y
CONFIG_BT_BYPASS_DOWNLOAD=y

# freertos
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.heap_4=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.extension=y
CONFIG_MCUX_PRJSEG_middleware.freertos-kernel.generated_config=y

CONFIG_configTICK_RATE_HZ=1000
CONFIG_configMAX_PRIORITIES=14
CONFIG_configMINIMAL_STACK_SIZE=320
CONFIG_configRECORD_STACK_HIGH_ADDRESS=y
CONFIG_configTIMER_TASK_STACK_DEPTH="(configMINIMAL_STACK_SIZE*8)"
CONFIG_configTIMER_QUEUE_LENGTH=10
CONFIG_configTOTAL_HEAP_SIZE=200704
CONFIG_configSUPPORT_STATIC_ALLOCATION=y
CONFIG_configUSE_IDLE_HOOK=y
CONFIG_configUSE_TICK_HOOK=y
CONFIG_configUSE_STATS_FORMATTING_FUNCTIONS=y
CONFIG_configUSE_APPLICATION_TASK_TAG=y
CONFIG_configENABLE_MPU=y
CONFIG_configENABLE_FPU=n
CONFIG_configUSE_APPLICATION_TASK_TAG=y

# wifi config
CONFIG_MCUX_PRJSEG_module.board.console_lite=n
CONFIG_MCUX_PRJSEG_module.board.console=y
CONFIG_MCUX_COMPONENT_middleware.lwip=y
CONFIG_MCUX_COMPONENT_middleware.lwip.apps.lwiperf=y
CONFIG_MCUX_COMPONENT_middleware.wifi.osa_free_rtos=y
CONFIG_MCUX_COMPONENT_middleware.wireless.wpa_supplicant.rtos=y

CONFIG_MCUX_COMPONENT_component.igpio_adapter=y
# CONFIG_MCUX_COMPONENT_component.silicon_id=y
CONFIG_MCUX_COMPONENT_component.wifi_bt_module.config=y
CONFIG_MCUX_COMPONENT_driver.flexspi=y
CONFIG_MCUX_COMPONENT_middleware.sdmmc.host.usdhc=y
CONFIG_MCUX_COMPONENT_middleware.sdmmc.host.usdhc.non_blocking=y
CONFIG_MCUX_COMPONENT_middleware.sdmmc.sdio=y
CONFIG_MCUX_COMPONENT_middleware.wifi=y
CONFIG_MCUX_COMPONENT_middleware.wifi.cli=y
CONFIG_MCUX_COMPONENT_middleware.wifi.sdio=y
CONFIG_MCUX_COMPONENT_middleware.wifi.wifidriver=y
CONFIG_MCUX_COMPONENT_middleware.wifi.net_free_rtos=y
CONFIG_MCUX_COMPONENT_middleware.fatfs=y
CONFIG_MCUX_COMPONENT_middleware.fatfs.ram=y
CONFIG_MCUX_COMPONENT_driver.enet=y

# component
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x=y
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.dcp=y
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.mbedtls_thread_alt=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.port.config=y
CONFIG_MCUX_DEPENDENCY_COMPONENT_middleware.wifi.template_DEPEND_ANYOF_OPTION_2=y

# config
CONFIG_BT_AUTO_DATA_LEN_UPDATE=y
CONFIG_BT_DATA_LEN_UPDATE=y
CONFIG_BT_PHY_UPDATE=y


CONFIG_MCUX_PRJSEG_middleware.fatfs.generated_config=y
CONFIG_NUM_PREEMPT_PRIORITIES=12
