# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_HW_DEVICE_PART_MIMX94398AVKM=y

CONFIG_MCUX_COMPONENT_middleware.freertos-kernel=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.heap_4=y

CONFIG_MCUX_PRJSEG_module.board.boardfile=n
CONFIG_MCUX_PRJSEG_module.board.board_core_file=n
CONFIG_MCUX_PRJSEG_module.board.clock=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_core_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_project_folder=n
CONFIG_MCUX_PRJSEG_project.hw_app_project_core_folder=y

CONFIG_MCUX_COMPONENT_device.system=y
CONFIG_MCUX_COMPONENT_device.startup=y

CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.config=n
CONFIG_MCUX_COMPONENT_utility.assert=y

CONFIG_MCUX_COMPONENT_driver.irqsteer_1=n
CONFIG_MCUX_COMPONENT_driver.reset=n
CONFIG_MCUX_COMPONENT_driver.elec_spec=n
CONFIG_MCUX_COMPONENT_driver.trdc_soc=n
CONFIG_MCUX_COMPONENT_driver.supply=n
CONFIG_MCUX_COMPONENT_driver.cpu=n
CONFIG_MCUX_COMPONENT_driver.power=n
CONFIG_MCUX_COMPONENT_driver.ccm=n
CONFIG_MCUX_COMPONENT_driver.src1=n
CONFIG_MCUX_COMPONENT_driver.fro=n
