CONFIG_MCUX_COMPONENT_middleware.freertos-kernel=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.heap_4=y
CONFIG_LV_OS_FREERTOS=y
CONFIG_LV_USE_SYSMON=y
CONFIG_LV_USE_OBSERVER=y
CONFIG_LV_USE_PERF_MONITOR=n
CONFIG_LV_SYSMON_GET_IDLE="getIdleTaskPct"
CONFIG_FREERTOS_USE_CUSTOM_CONFIG_FRAGMENT=y
CONFIG_LV_VG_LITE_USE_ASSERT=n
CONFIG_LV_USE_ASSERT_NULL=n
CONFIG_LV_USE_ASSERT_MALLOC=n
CONFIG_LV_USE_LOG=y
CONFIG_LV_LOG_LEVEL_ERROR=y
CONFIG_LV_CONF_MINIMAL=y
CONFIG_LV_USE_LABEL=y
CONFIG_LV_USE_THEME_DEFAULT=y
CONFIG_MCUX_COMPONENT_middleware.lvgl.src.libs.thorvg=y
