/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#include "clock_config.h"

/*******************************************************************************
 * Definitions
 ******************************************************************************/
const fxosc_config_t fxoscConfig = 
    {
      .freqHz = BOARD_XTAL_CLK_HZ,
      .workMode = kFXOSC_ModeCrystal,
      .startupDelay = 49U,  
      .overdriveProtect = 12U, 
    };

/* PLL in integer mode, VcoFreq = FXOSC(16MHz) / 2 * 120 / 2 = 480MHz. */
const pll_config_t pllConfig = 
    {
      .workMode = kPLL_ModeInteger,
      .preDiv = 2U,  
      .postDiv = 2U, 
      .multiplier = 120U, 
      .outDiv[0] = 3U,
      .outDiv[1] = 3U,
    };

/*******************************************************************************
 * Variables
 ******************************************************************************/

/*******************************************************************************
 ************************ BOARD_InitBootClocks function ************************
 ******************************************************************************/
void BOARD_InitBootClocks(void)
{
    BOARD_BootClockRUN();
}

void BOARD_BootClockRUN()
{
    CLOCK_SelectSafeClock(kFIRC_CLK_to_MUX0); /* Switch MUX0 to FIRC for safe reconfig. */

    /* CLOCK_InitSxosc(true, 2U); */ /* Enable SXOSC in application when used. */
    CLOCK_InitFxosc(&fxoscConfig);
    
    CLOCK_InitPll(&pllConfig);
 
    /* Switch MUX0 to PLL 160MHz. */
    CLOCK_SetClkMux0DivTriggerType(KCLOCK_CommonTriggerUpdate);
    CLOCK_SetClkDiv(kCLOCK_DivCoreClk, 1U);
    CLOCK_SetClkDiv(kCLOCK_DivAipsPlatClk, 2U);
    CLOCK_SetClkDiv(kCLOCK_DivAipsSlowClk, 4U);
    CLOCK_SetClkDiv(kCLOCK_DivHseClk, 2U);
    CLOCK_SetClkDiv(kCLOCK_DivDcmClk, 4U);
    CLOCK_SetClkDiv(kCLOCK_DivLbistClk, 4U);
    CLOCK_SetClkDiv(kCLOCK_DivQspiClk, 1U);
    CLOCK_CommonTriggerClkMux0DivUpdate();
    CLOCK_AttachClk(kPLL_PHI0_CLK_to_MUX0);
    
    SystemCoreClockUpdate();
}
