#
# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

#select profile
CONFIG_MCUX_COMPONENT_middleware.tfm.profile_medium=y
CONFIG_MCUX_COMPONENT_middleware.psatest.ns.disable_crypto_cipher_module=y

#include pin_mux board component
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=y

#drivers
CONFIG_MCUX_COMPONENT_middleware.tfm.lpuart=y
CONFIG_MCUX_COMPONENT_driver.ctimer=y

# enable west flash of tfm example
CONFIG_FLASH_BASE_ADDRESS=0x00030000
