#select profile
CONFIG_MCUX_COMPONENT_middleware.tfm.profile_medium=y

#mcxn236 romapi config
CONFIG_MCUX_COMPONENT_middleware.tfm.flash_mcxn=y

#drivers
CONFIG_MCUX_COMPONENT_middleware.tfm.lpuart=y
CONFIG_MCUX_COMPONENT_driver.ctimer=y

#include pin_mux board component
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=y
