mcux_add_macro(
    CC "OCOTP_NV_COUNTERS_RAM_EMULATION=1\
        RW61X_IPED_ITS_ROLLBACK_PROTECTION_ENABLE=0\
        PSA_WANT_ALG_SHA_1\
        TFM_WIFI_FLASH_REGION"
)

mcux_set_list(
    TFM_LINKER_DEFINES_MQTT "-D__ARM_ARCH_8M_MAIN__ -DCONFIG_TFM_USE_TRUSTZONE -DCONFIG_TFM_PARTITION_META -DENABLE_HEAP -DTFM_WIFI_FLASH_REGION"
)