# Component
CONFIG_MCUX_COMPONENT_component.igpio_adapter=y
CONFIG_MCUX_COMPONENT_component.silicon_id=y
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.caam=y
CONFIG_MCUX_COMPONENT_component.wifi_bt_module.IW61X=y
CONFIG_MCUX_COMPONENT_component.wifi_bt_module.board_ubx_maya_w276=y
CONFIG_MCUX_COMPONENT_driver.flexspi=y
CONFIG_MCUX_COMPONENT_driver.lpi2c=y
CONFIG_MCUX_COMPONENT_driver.pcal6524=y
CONFIG_MCUX_ABSTRACT_COMPONENT_component_expander=y
CONFIG_MCUX_COMPONENT_driver.wifi.libcsi=y
CONFIG_MCUX_COMPONENT_component.mflash_offchip=y
CONFIG_MCUX_COMPONENT_middleware.sdmmc.host.usdhc=y
CONFIG_MCUX_COMPONENT_middleware.sdmmc.host.usdhc.non_blocking=y
CONFIG_MCUX_COMPONENT_middleware.sdmmc.sdio=y

# Firmware download
CONFIG_MCUX_COMPONENT_component.wifi_bt_module.wifi_fw=y
CONFIG_MCUX_COMPONENT_component.wifi_bt_module.bt_only_fw=y
CONFIG_BT_BYPASS_DOWNLOAD=y

# BT config
CONFIG_BT_DATA_LEN_UPDATE=y
CONFIG_BT_PHY_UPDATE=y
CONFIG_NUM_PREEMPT_PRIORITIES=12

# FreeRTOS
CONFIG_MCUX_PRJSEG_middleware.freertos-kernel.generated_config=y
CONFIG_configTICK_RATE_HZ=1000
CONFIG_configMAX_PRIORITIES=14
CONFIG_configMINIMAL_STACK_SIZE=320
CONFIG_configRECORD_STACK_HIGH_ADDRESS=y
CONFIG_configTIMER_TASK_STACK_DEPTH="(configMINIMAL_STACK_SIZE*8)"
CONFIG_configTIMER_QUEUE_LENGTH=10
CONFIG_configTOTAL_HEAP_SIZE=184320
CONFIG_configSUPPORT_STATIC_ALLOCATION=y
CONFIG_configUSE_IDLE_HOOK=y
CONFIG_configUSE_TICK_HOOK=y
CONFIG_configUSE_STATS_FORMATTING_FUNCTIONS=y
CONFIG_configUSE_APPLICATION_TASK_TAG=y
CONFIG_configENABLE_MPU=y
CONFIG_configENABLE_FPU=n

# Wi-Fi config
CONFIG_MCUX_DEPENDENCY_COMPONENT_middleware.wifi.template_DEPEND_ANYOF_OPTION_2=y
CONFIG_MCUX_COMPONENT_middleware.wifi.sdio=y

# Misc
CONFIG_MCUX_PRJSEG_module.board.console_lite=n
CONFIG_MCUX_PRJSEG_module.board.console=y
CONFIG_DEBUG_CONSOLE_SYNCHRONIZATION_MODE=1
CONFIG_FSL_OSA_MAIN_FUNC_ENABLE=n
