# Copyright 2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_PRJSEG_module.board.pinmux_project_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_project_folder=y
CONFIG_MCUX_COMPONENT_component.mflash_offchip=y
CONFIG_MCUX_COMPONENT_component.debug_coredump_backend.mflash=y
CONFIG_MFLASH_COREDUMP_REGION_START_ADDR=0x3000000
CONFIG_MFLASH_COREDUMP_REGION_SIZE=0x1000
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.cm33_non_trustzone=y
