
CONFIG_MCUX_COMPONENT_component.phyrtl8201=y
CONFIG_MCUX_COMPONENT_component.phyrtl8211f=y
CONFIG_MCUX_COMPONENT_driver.cache_xcache=y
CONFIG_MCUX_COMPONENT_driver.misc_soc=y
CONFIG_MCUX_COMPONENT_driver.msgintr=y
CONFIG_MCUX_COMPONENT_driver.netc=y
CONFIG_MCUX_COMPONENT_driver.ecat=y
CONFIG_MCUX_COMPONENT_driver.lpi2c=y
CONFIG_MCUX_COMPONENT_driver.xbar_1=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_core_folder=n
CONFIG_MCUX_PRJSEG_project.hw_app_project_folder=y