/*
 * Copyright 2025 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include "pin_mux.h"
#include "fsl_common.h"

/*
 * Pin multiplexing for the mimxrt2660evk PMSM encoder example.
 *
 * The actual pin mux register writes for PWM1, EQDC1, ADC1/ADC2,
 * LPUART1, and the user LED/button GPIOs are generated by the
 * MCUXpresso Config Tools pin mux configuration and placed in the
 * board-level common/pin_mux/pin_mux.c.  This file includes that
 * shared configuration via the board project segment mechanism;
 * no additional pin configuration is required here.
 */
void BOARD_InitBootPins(void)
{
    extern void BOARD_InitPins(void);
    BOARD_InitPins();
}
