#
# Copyright 2024 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

mcux_add_xtensa_configuration(
    CC "-DXA_PCM_GAIN=1 -DXA_CAPTURER=1 -DXA_RENDERER=1 -DSDK_DEBUGCONSOLE=1 -DXOS_CLOCK_FREQ=230000000 -DXF_CORE_ID=0 -DXF_CFG_CORES_NUM=1 -DRENDERER_SAI -DCAPTURER_PDM"
)
