# Wi-Fi module
CONFIG_MCUX_COMPONENT_component.wifi_bt_module.IW61X=y
CONFIG_MCUX_COMPONENT_component.wifi_bt_module.board_murata_2el_m2=y
CONFIG_MCUX_COMPONENT_component.wifi_bt_module.wifi_bt_combo_fw=y
CONFIG_MCUX_COMPONENT_component.wifi_bt_module.config=y

# freertos
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.heap_4=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.extension=y
CONFIG_MCUX_PRJSEG_middleware.freertos-kernel.generated_config=y

CONFIG_configTICK_RATE_HZ=1000
CONFIG_configMAX_PRIORITIES=10
CONFIG_configMINIMAL_STACK_SIZE=320
CONFIG_configRECORD_STACK_HIGH_ADDRESS=y
CONFIG_configTIMER_TASK_STACK_DEPTH="(configMINIMAL_STACK_SIZE*8)"
CONFIG_configTIMER_QUEUE_LENGTH=10
CONFIG_configTOTAL_HEAP_SIZE=184320
CONFIG_configSUPPORT_STATIC_ALLOCATION=y
CONFIG_configUSE_IDLE_HOOK=y
CONFIG_configUSE_TICK_HOOK=y
CONFIG_configUSE_STATS_FORMATTING_FUNCTIONS=y
CONFIG_configUSE_APPLICATION_TASK_TAG=y
CONFIG_configENABLE_MPU=y
CONFIG_configENABLE_FPU=n

# wifi
CONFIG_MCUX_PRJSEG_module.board.console_lite=n
CONFIG_MCUX_PRJSEG_module.board.console=y
CONFIG_MCUX_COMPONENT_middleware.lwip=y
CONFIG_MCUX_COMPONENT_middleware.lwip.apps.lwiperf=y
CONFIG_MCUX_COMPONENT_middleware.wifi.osa_free_rtos=y
CONFIG_MCUX_COMPONENT_component.igpio_adapter=y
CONFIG_MCUX_COMPONENT_driver.flexspi=y
CONFIG_MCUX_COMPONENT_middleware.sdmmc.host.usdhc=y
CONFIG_MCUX_COMPONENT_middleware.sdmmc.host.usdhc.non_blocking=y
CONFIG_MCUX_COMPONENT_middleware.sdmmc.sdio=y
CONFIG_MCUX_COMPONENT_middleware.wifi=y
CONFIG_MCUX_COMPONENT_middleware.wifi.cli=y
CONFIG_MCUX_COMPONENT_middleware.wifi.sdio=y
CONFIG_MCUX_COMPONENT_middleware.wifi.wifidriver=y
CONFIG_MCUX_COMPONENT_middleware.wifi.net_free_rtos=y
CONFIG_MCUX_COMPONENT_utility.assert_lite=n
CONFIG_MCUX_COMPONENT_utility.debug_console_lite=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y

# BT board config (from edgefast_open unicast_media_sender board prj.conf)
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.port.config=y
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.caam=y
CONFIG_MCUX_DEPENDENCY_COMPONENT_middleware.wifi.template_DEPEND_ANYOF_OPTION_2=y

# config
CONFIG_USB_HOST_CONFIG_EHCI=2
CONFIG_BT_BYPASS_DOWNLOAD=y
CONFIG_WORK_QUEUE_TASK_STACK_SIZE=4096
