/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
    BOARD_InitDEBUG_UARTPins();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    const  siul2_pin_settings_t pin_pta31_config =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 31u,
        .mux                         = kPORT_MUX_ALT3,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         152u
                                       },
        .inputMux                    = { 
                                         kPORT_INPUT_MUX_ALT6,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u,
    };
  
    SIUL2_PinInit(&pin_pta31_config);
  
    const  siul2_pin_settings_t pin_ptb18_config =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 50u,
        .mux                         = kPORT_MUX_ALT3,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         153u
                                       },
        .inputMux                    = { 
                                         kPORT_INPUT_MUX_ALT6,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u,
    };
  
    SIUL2_PinInit(&pin_ptb18_config);

    const  siul2_pin_settings_t pin_ptb19_config =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 51u,
        .mux                         = kPORT_MUX_ALT3,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         154u
                                       },
        .inputMux                    = { 
                                         kPORT_INPUT_MUX_ALT5,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u,
    };
  
    SIUL2_PinInit(&pin_ptb19_config);
  
    const  siul2_pin_settings_t pin_ptb20_config =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 52u,
        .mux                         = kPORT_MUX_ALT3,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .pullKeep                    = kPORT_PULL_KEEP_ENABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         155u
                                       },
        .inputMux                    = { 
                                         kPORT_INPUT_MUX_ALT5,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u,
    };
  
    SIUL2_PinInit(&pin_ptb20_config);
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDEBUG_UARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitDEBUG_UARTPins(void)
{
   const siul2_pin_settings_t pin_pte3_config =
   {
        .base                        = SIUL2,
        .pinPortIdx                  = 131u,
        .mux                         = kPORT_MUX_AS_GPIO,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_DISABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         192u
                                       },
        .inputMux                    = {
                                         kPORT_INPUT_MUX_ALT1,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u
    };
   SIUL2_PinInit(&pin_pte3_config);


   const siul2_pin_settings_t pin_pte14_config =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 142u,
        .mux                         = kPORT_MUX_ALT4,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_NOT_AVAILABLE,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_DISABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .initValue                   = 2u
    };
    SIUL2_PinInit(&pin_pte14_config);
}

void BOARD_InitSPIPins(void)
{
    const  siul2_pin_settings_t pin_pte0_config =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 128u,
        .mux                         = kPORT_MUX_ALT2,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_DISABLED,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         230u
                                       },
        .inputMux                    = {
                                         kPORT_INPUT_MUX_ALT1,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u,
    };

    SIUL2_PinInit(&pin_pte0_config);

    const  siul2_pin_settings_t pin_pte1_config =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 129u,
        .mux                         = kPORT_MUX_ALT2,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_DISABLED,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         229u
                                       },
        .inputMux                    = {
                                         kPORT_INPUT_MUX_ALT2,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u,
    };

    SIUL2_PinInit(&pin_pte1_config);

    const  siul2_pin_settings_t pin_pte2_config =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 130u,
        .mux                         = kPORT_MUX_ALT2,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_DISABLED,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         231u
                                       },
        .inputMux                    = {
                                         kPORT_INPUT_MUX_ALT1,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u,
    };

    SIUL2_PinInit(&pin_pte2_config);

    const  siul2_pin_settings_t pin_pte6_config =
    {
        .base                        = SIUL2,
        .pinPortIdx                  = 134u,
        .mux                         = kPORT_MUX_ALT2,
        .safeMode                    = kPORT_SAFE_MODE_DISABLED,
        .inputFilter                 = kPORT_INPUT_FILTER_DISABLED,
        .driveStrength               = kPORT_DRIVE_STRENTGTH_DISABLED,
        .pullConfig                  = kPORT_INTERNAL_PULL_NOT_ENABLED,
        .pullKeep                    = kPORT_PULL_KEEP_DISABLED,
        .invert                      = kPORT_INVERT_DISABLED,
        .inputBuffer                 = kPORT_INPUT_BUFFER_ENABLED,
        .outputBuffer                = kPORT_OUTPUT_BUFFER_ENABLED,
        .adcInterleaves              = { kMUX_MODE_NOT_AVAILABLE, kMUX_MODE_NOT_AVAILABLE },
        .inputMuxReg                 = {
                                         223u
                                       },
        .inputMux                    = {
                                         kPORT_INPUT_MUX_ALT1,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT,
                                         kPORT_INPUT_MUX_NO_INIT
                                       },
        .initValue                   = 2u,
    };

    SIUL2_PinInit(&pin_pte6_config);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
