#select profile
CONFIG_MCUX_COMPONENT_middleware.tfm.profile_medium=y

#mcxw23 tfm flash config
CONFIG_MCUX_COMPONENT_middleware.tfm.flash_mcxw23=y

#mbedtls configs
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.crypto=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.port.only_accelerator_config=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.port.only_entropy=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.port.hw_init=y

#drivers
CONFIG_MCUX_COMPONENT_middleware.tfm.usart=y
CONFIG_MCUX_COMPONENT_driver.flexcomm=y
CONFIG_MCUX_COMPONENT_driver.ctimer=y
CONFIG_MCUX_COMPONENT_driver.trng=y

#include pin_mux board component
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=y
