#
# Copyright 2024 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_PRJSEG_module.incbin_for_core=y
CONFIG_MCUX_PRJSEG_module.incbin=n
CONFIG_MCUX_PRJSEG_module.pmic_support=y
CONFIG_MCUX_PRJSEG_module.dsp_support=n
CONFIG_MCUX_COMPONENT_driver.dsp=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_core_folder=y
