
CONFIG_MCUX_COMPONENT_component.lists=y
CONFIG_MCUX_COMPONENT_component.lpuart_adapter=y
CONFIG_MCUX_COMPONENT_driver.flexspi=y
CONFIG_MCUX_COMPONENT_driver.lpuart=y
CONFIG_EXAMPLE_I3C_OD_BAUDRATE=1500000
