# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_HW_DEVICE_PART_MIMX9111CVXXJ=y

CONFIG_MCUX_COMPONENT_middleware.freertos-kernel=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.heap_4=y

CONFIG_MCUX_PRJSEG_module.board.boardfile=y
CONFIG_MCUX_PRJSEG_module.board.clock=y
CONFIG_MCUX_PRJSEG_module.board.suite=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_project_folder=y

CONFIG_MCUX_COMPONENT_device.system=y
CONFIG_MCUX_COMPONENT_device.startup=y

CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.config=n
CONFIG_MCUX_COMPONENT_utility.assert=y
