CONFIG_MCUX_COMPONENT_driver.clock=y
CONFIG_MCUX_COMPONENT_component.osa_bm=y
CONFIG_MCUX_COMPONENT_driver.crc=y
CONFIG_MCUX_COMPONENT_driver.lpuart=y
CONFIG_MCUX_COMPONENT_driver.flash=y
CONFIG_MCUX_COMPONENT_driver.lpi2c=y
CONFIG_MCUX_COMPONENT_driver.lpspi=y
CONFIG_MCUX_COMPONENT_driver.gpio=y
CONFIG_MCUX_COMPONENT_driver.port=y
CONFIG_MCUX_COMPONENT_driver.smc=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.MKE17Z7_sources=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.MKE17Z7_startup=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.bootsources=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.bootsources_kinetis=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.drv_microseconds=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.src_startup=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_folder=n
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_COMPONENT_device.CMSIS=y
CONFIG_MCUX_PRJSEG_module.board.suite=n
CONFIG_MCUX_PRJSEG_middleware.mcu-boot.MKE17Z7_application_0x0000_linker=y
CONFIG_MCUX_PRJSEG_frdmke17z_kboot_options=y
CONFIG_MCUX_PRJSEG_module.board.use_board_clock=n
CONFIG_MCUX_COMPONENT_utility.assert=n
CONFIG_MCUX_COMPONENT_utility.assert_lite=n
