# board+application specific cmake

mcux_add_macro(
    CC "-DconfigGENERATE_RUN_TIME_STATS=1 \
    -DDEBUG_CONSOLE_RX_ENABLE=0 \
    -DDEBUG_CONSOLE_TRANSFER_NON_BLOCKING \
    -DSDK_DEBUGCONSOLE=1"
    
    CXX "-DconfigGENERATE_RUN_TIME_STATS=1 \
    -DDEBUG_CONSOLE_RX_ENABLE=0 \
    -DDEBUG_CONSOLE_TRANSFER_NON_BLOCKING \
    -DSDK_DEBUGCONSOLE=1"
)
