# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_COMPONENT_component.phyyt8521=y

# ENET_QOS has no TX checksum offload; do all checksums in software.
CONFIG_CHECKSUM_GEN_IP=y
CONFIG_CHECKSUM_GEN_UDP=y
CONFIG_CHECKSUM_GEN_TCP=y
CONFIG_CHECKSUM_GEN_ICMP=y
CONFIG_CHECKSUM_GEN_ICMP6=y

CONFIG_ENET_RXBUFF_NUM="14"
CONFIG_ENET_RXBD_NUM=9
