CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=y
CONFIG_MCUX_COMPONENT_component.phyyt8521=y
CONFIG_MCUX_COMPONENT_driver.msgintr=y
CONFIG_MCUX_COMPONENT_driver.netc=y