CONFIG_MCUX_COMPONENT_middleware.eiq.tensorflow_lite_micro.library=y
CONFIG_MCUX_COMPONENT_middleware.eiq.tensorflow_lite_micro.cmsis_nn=y
CONFIG_MCUX_PRJSEG_module.board.boardfile=n
CONFIG_MCUX_PRJSEG_module.board.console_lite=n
CONFIG_MCUX_PRJSEG_module.board.suite=n
CONFIG_MCUX_COMPONENT_board.boot_header=n
CONFIG_MCUX_COMPONENT_device.boot_header=n
CONFIG_MCUX_PRJSEG_module.board.use_board_clock=n
CONFIG_MCUX_PRJSEG_module.board.clock=n
CONFIG_MCUX_HAS_PRJSEG_module.board.pinmux_sel=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_core_folder=n
CONFIG_MCUX_HAS_PRJSEG_project.use_hw_app=n
CONFIG_MCUX_PRJSEG_project.hw_app_project_core_folder=n
CONFIG_MCUX_COMPONENT_device.CMSIS=n
CONFIG_MCUX_COMPONENT_device.system=n
CONFIG_MCUX_COMPONENT_device.startup=n
CONFIG_MCUX_COMPONENT_driver.clock=n
CONFIG_MCUX_COMPONENT_driver.iopctl_soc=n
CONFIG_MCUX_COMPONENT_driver.power=n
CONFIG_MCUX_COMPONENT_driver.reset=n
CONFIG_MCUX_COMPONENT_driver.cache_xcache=n
CONFIG_MCUX_COMPONENT_driver.common=n
CONFIG_MCUX_COMPONENT_driver.glikey=n
CONFIG_MCUX_COMPONENT_driver.gpio=n
CONFIG_MCUX_COMPONENT_driver.igpio=n
CONFIG_MCUX_COMPONENT_driver.lpflexcomm=n
CONFIG_MCUX_COMPONENT_driver.lpflexcomm_lpuart=n
CONFIG_MCUX_COMPONENT_driver.xspi=n
CONFIG_MCUX_COMPONENT_utility.assert_lite=n
CONFIG_MCUX_COMPONENT_driver.flash_config=n
CONFIG_MCUX_COMPONENT_utilities.misc_utilities=n
CONFIG_MCUX_COMPONENT_utility.str=n
CONFIG_MCUX_COMPONENT_utility.debug_console_lite=n
CONFIG_MCUX_COMPONENT_component.lpuart_adapter=n

CONFIG_MCUX_COMPONENT_driver.dcdc_2=n
CONFIG_MCUX_COMPONENT_driver.src_2=n
CONFIG_MCUX_COMPONENT_driver.pgmc=n
CONFIG_MCUX_COMPONENT_driver.anadig_pmu=n
CONFIG_MCUX_COMPONENT_driver.mu=n
CONFIG_MCUX_COMPONENT_driver.anatop_ai=n
CONFIG_MCUX_COMPONENT_driver.cache_armv7_m7=n
CONFIG_MCUX_COMPONENT_driver.gpc_xxx_ctrl=n
CONFIG_MCUX_COMPONENT_driver.iomuxc=n
CONFIG_MCUX_COMPONENT_driver.pgmc=n
CONFIG_MCUX_COMPONENT_driver.memory=n

CONFIG_MCUX_COMPONENT_driver.lpc_gpio=n
CONFIG_MCUX_COMPONENT_driver.dsp=n
CONFIG_MCUX_COMPONENT_driver.flexspi=n
CONFIG_MCUX_COMPONENT_driver.i2s_bridge=n
CONFIG_MCUX_COMPONENT_driver.flexcomm=n
CONFIG_MCUX_COMPONENT_driver.flexcomm_usart=n
CONFIG_MCUX_COMPONENT_driver.mipi_dsi_soc=n
CONFIG_MCUX_COMPONENT_driver.iap=n
CONFIG_MCUX_COMPONENT_driver.iap1=n
CONFIG_MCUX_COMPONENT_driver.iap3=n
CONFIG_MCUX_COMPONENT_driver.lpc_iopctl=n
CONFIG_MCUX_COMPONENT_driver.cache_cache64=n
CONFIG_MCUX_COMPONENT_driver.dcdc_1=n
CONFIG_MCUX_COMPONENT_driver.gpc_1=n
CONFIG_MCUX_COMPONENT_driver.pmu=n
CONFIG_MCUX_COMPONENT_driver.src=n
CONFIG_MCUX_COMPONENT_driver.dcdc_3=n
CONFIG_MCUX_COMPONENT_driver.ele_base_api=n
CONFIG_MCUX_COMPONENT_driver.gpc_3=n
CONFIG_MCUX_COMPONENT_driver.anadig_pmu_1=n
CONFIG_MCUX_COMPONENT_driver.s3mu=n
CONFIG_MCUX_COMPONENT_driver.src_3=n
CONFIG_MCUX_COMPONENT_driver.rgpio=n
CONFIG_MCUX_COMPONENT_driver.misc=n
CONFIG_MCUX_COMPONENT_driver.trdc=n
CONFIG_MCUX_COMPONENT_component.silicon_id=n

CONFIG_MCUX_COMPONENT_driver.mcx_spc=n
CONFIG_MCUX_COMPONENT_driver.inputmux=n
CONFIG_MCUX_COMPONENT_driver.port=n
CONFIG_MCUX_COMPONENT_driver.inputmux_connections=n

CONFIG_MCUX_COMPONENT_driver.cache_llc=n
CONFIG_MCUX_COMPONENT_driver.modcon=n
CONFIG_MCUX_COMPONENT_driver.trdc_1=n
CONFIG_MCUX_COMPONENT_driver.trdc_soc=n
