# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

# Enable mbedtls3x
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.crypto=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.x509=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.ssl.no_psa=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.port.config=y

# Enable secure storage usage.   
CONFIG_MCUX_COMPONENT_middleware.SECURE_STORAGE=y
CONFIG_MCUX_COMPONENT_middleware.SECURE_STORAGE_ITS_IMPLEMENTATION_WITH_ONLY_STORE=y
CONFIG_MCUX_COMPONENT_middleware.SECURE_STORAGE_ITS_STORE_IMPLEMENTATION_LITTLEFS=y 

# Configure the ITS MAX data size in secure storage
CONFIG_SECURE_STORAGE_ITS_MAX_DATA_SIZE=2208

# Configure 64-bit UIDs for backward compatibility
CONFIG_SECURE_STORAGE_64_BIT_UID=y

# Enable littlefs to be used by SECURE_STORAGE
CONFIG_MCUX_COMPONENT_middleware.littlefs=y
CONFIG_MCUX_COMPONENT_middleware.littlefs_mflash=y

# Enable builtin CRC driver module 
CONFIG_MCUX_COMPONENT_driver.crc=y