CONFIG_MCUX_PRJSEG_project.hw_app_project_core_folder=n
CONFIG_MCUX_COMPONENT_driver.slcd_engine=y
CONFIG_MCUX_COMPONENT_driver.slcd_ftp12557=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_core_folder=y
