CONFIG_MCUX_COMPONENT_driver.edma_soc=n
CONFIG_MCUX_COMPONENT_driver.lpi2c=y
CONFIG_MCUX_COMPONENT_driver.display-it6263=y
CONFIG_MCUX_COMPONENT_driver.display-waveshare-dsi2dpi=y
CONFIG_MCUX_COMPONENT_driver.ldb_1=y
CONFIG_MCUX_COMPONENT_driver.rgpio=y
CONFIG_MCUX_COMPONENT_driver.pca6416a=y
CONFIG_MCUX_ABSTRACT_COMPONENT_component_expander=y
CONFIG_MCUX_COMPONENT_driver.dpu_1=y
CONFIG_MCUX_COMPONENT_driver.mipi_dsi2_dwc=y
CONFIG_MCUX_PRJSEG_module.board.display_support=y
