CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_project_folder=y
CONFIG_IFLASH_EXPLICIT_DEVICE_CONFIG_VALUES=y
CONFIG_IFLASH_DEPART_CODE=0x04
CONFIG_IFLASH_EEESIZE_CODE=0x02
