/*
 * Copyright 2024-2026 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v14.0
processor: MIMXRT798S
package_id: MIMXRT798SGVKB
mcu_data: ksdk2_0
processor_version: 0.0.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_iopctl.h"
#include "fsl_reset.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
    BOARD_InitCameraPins();
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures UART debug console pins (LP_FLEXCOMM0).
 *                 PIO0_31 = FC0_RXD, PIO1_0 = FC0_TXD
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void)
{
    RESET_ClearPeripheralReset(kIOPCTL0_RST_SHIFT_RSTn);

    /* PIO0_31: FC0_RXD_SDA_MOSI_DATA */
    const uint32_t port0_pin31_config = (IOPCTL_PIO_FUNC1 |
                                         IOPCTL_PIO_PUPD_DI |
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         IOPCTL_PIO_INBUF_EN |
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         IOPCTL_PIO_DRIVE_100OHM |
                                         IOPCTL_PIO_ANAMUX_DI |
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         IOPCTL_PIO_INV_DI);
    IOPCTL_PinMuxSet(0U, 31U, port0_pin31_config);

    /* PIO1_0: FC0_TXD_SCL_MISO_WS */
    const uint32_t port1_pin0_config = (IOPCTL_PIO_FUNC1 |
                                        IOPCTL_PIO_PUPD_DI |
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        IOPCTL_PIO_INBUF_DI |
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        IOPCTL_PIO_DRIVE_100OHM |
                                        IOPCTL_PIO_ANAMUX_DI |
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        IOPCTL_PIO_INV_DI);
    IOPCTL_PinMuxSet(1U, 0U, port1_pin0_config);
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitMipiPanelPins
 * Description   : Configures MIPI DSI panel pins for FRDM-IMXRT700.
 *                 RST: GPIO3_4, POWER: GPIO1_10, BL: GPIO1_14, TE: GPIO3_5
 *                 Touch I2C: LPI2C8 (PIO4_x)
 *
 * END ****************************************************************************************************************/
void BOARD_InitMipiPanelPins(void)
{
    /* MIPI RST: GPIO3_4 */
    const uint32_t mipi_rst_config = (IOPCTL_PIO_FUNC0 |
                                      IOPCTL_PIO_PUPD_DI |
                                      IOPCTL_PIO_PULLDOWN_EN |
                                      IOPCTL_PIO_INBUF_DI |
                                      IOPCTL_PIO_SLEW_RATE_NORMAL |
                                      IOPCTL_PIO_DRIVE_100OHM |
                                      IOPCTL_PIO_ANAMUX_DI |
                                      IOPCTL_PIO_PSEDRAIN_DI |
                                      IOPCTL_PIO_INV_DI);
    IOPCTL_PinMuxSet(3U, 4U, mipi_rst_config);

    /* MIPI POWER: GPIO1_10 */
    const uint32_t mipi_pwr_config = (IOPCTL_PIO_FUNC0 |
                                      IOPCTL_PIO_PUPD_DI |
                                      IOPCTL_PIO_PULLDOWN_EN |
                                      IOPCTL_PIO_INBUF_DI |
                                      IOPCTL_PIO_SLEW_RATE_NORMAL |
                                      IOPCTL_PIO_DRIVE_100OHM |
                                      IOPCTL_PIO_ANAMUX_DI |
                                      IOPCTL_PIO_PSEDRAIN_DI |
                                      IOPCTL_PIO_INV_DI);
    IOPCTL_PinMuxSet(1U, 10U, mipi_pwr_config);

    /* MIPI BL: GPIO1_14 */
    const uint32_t mipi_bl_config = (IOPCTL_PIO_FUNC0 |
                                     IOPCTL_PIO_PUPD_DI |
                                     IOPCTL_PIO_PULLDOWN_EN |
                                     IOPCTL_PIO_INBUF_DI |
                                     IOPCTL_PIO_SLEW_RATE_NORMAL |
                                     IOPCTL_PIO_DRIVE_100OHM |
                                     IOPCTL_PIO_ANAMUX_DI |
                                     IOPCTL_PIO_PSEDRAIN_DI |
                                     IOPCTL_PIO_INV_DI);
    IOPCTL_PinMuxSet(1U, 14U, mipi_bl_config);

    /* MIPI TE: GPIO3_5 (input) */
    const uint32_t mipi_te_config = (IOPCTL_PIO_FUNC0 |
                                     IOPCTL_PIO_PUPD_DI |
                                     IOPCTL_PIO_PULLDOWN_EN |
                                     IOPCTL_PIO_INBUF_EN |
                                     IOPCTL_PIO_SLEW_RATE_NORMAL |
                                     IOPCTL_PIO_DRIVE_100OHM |
                                     IOPCTL_PIO_ANAMUX_DI |
                                     IOPCTL_PIO_PSEDRAIN_DI |
                                     IOPCTL_PIO_INV_DI);
    IOPCTL_PinMuxSet(3U, 5U, mipi_te_config);
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitFlexIOPanelPins
 * Description   : Configures FlexIO 8-bit LCD data bus pins for SSD1963 panel.
 *                 Data: PIO2_2..PIO2_9, PCLK: PIO2_10, HREF: PIO2_11
 *
 * END ****************************************************************************************************************/
void BOARD_InitFlexIOPanelPins(void)
{
    const uint32_t flexio_pin_config = (IOPCTL_PIO_FUNC5 |
                                        IOPCTL_PIO_PUPD_DI |
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        IOPCTL_PIO_INBUF_EN |
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        IOPCTL_PIO_DRIVE_66OHM |
                                        IOPCTL_PIO_ANAMUX_DI |
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        IOPCTL_PIO_INV_DI);

    /* PIO2_2 .. PIO2_9: FLEXIO_D6..D13 (8-bit data bus) */
    for (uint32_t pin = 2U; pin <= 9U; pin++)
    {
        IOPCTL_PinMuxSet(2U, pin, flexio_pin_config);
    }
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLcdDBIPanelPins
 * Description   : Configures LCD-DBI (LCDIF) pins for SSD1963 panel.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLcdDBIPanelPins(void)
{
    /* TODO: configure LCDIF DBI pins per board schematic */
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitCameraPins
 * Description   : Configures FlexIO camera pins for OV7670.
 *                 XCLK: FLEXIO_D1 (TIMER1), PCLK: FLEXIO_D15 (TIMER0)
 *                 Data: FLEXIO_D6..D13, XSYNC IRQ: GPIO2_5, RESET: GPIO2_0
 *
 * END ****************************************************************************************************************/
void BOARD_InitCameraPins(void)
{
    const uint32_t cam_data_config = (IOPCTL_PIO_FUNC5 |
                                      IOPCTL_PIO_PUPD_DI |
                                      IOPCTL_PIO_PULLDOWN_EN |
                                      IOPCTL_PIO_INBUF_EN |
                                      IOPCTL_PIO_SLEW_RATE_NORMAL |
                                      IOPCTL_PIO_DRIVE_66OHM |
                                      IOPCTL_PIO_ANAMUX_DI |
                                      IOPCTL_PIO_PSEDRAIN_DI |
                                      IOPCTL_PIO_INV_DI);

    /* Camera data pins: PIO2_2..PIO2_9 (FLEXIO_D6..D13) */
    for (uint32_t pin = 2U; pin <= 9U; pin++)
    {
        IOPCTL_PinMuxSet(2U, pin, cam_data_config);
    }

    /* PCLK: PIO2_15 (FLEXIO_D15/TIMER0) */
    IOPCTL_PinMuxSet(2U, 15U, cam_data_config);

    /* XCLK: PIO2_1 (FLEXIO_D1/TIMER1) */
    const uint32_t xclk_config = (IOPCTL_PIO_FUNC5 |
                                   IOPCTL_PIO_PUPD_DI |
                                   IOPCTL_PIO_PULLDOWN_EN |
                                   IOPCTL_PIO_INBUF_DI |
                                   IOPCTL_PIO_SLEW_RATE_NORMAL |
                                   IOPCTL_PIO_DRIVE_66OHM |
                                   IOPCTL_PIO_ANAMUX_DI |
                                   IOPCTL_PIO_PSEDRAIN_DI |
                                   IOPCTL_PIO_INV_DI);
    IOPCTL_PinMuxSet(2U, 1U, xclk_config);

    /* XSYNC IRQ: GPIO2_5 (input) */
    const uint32_t gpio_in_config = (IOPCTL_PIO_FUNC0 |
                                     IOPCTL_PIO_PUPD_DI |
                                     IOPCTL_PIO_PULLDOWN_EN |
                                     IOPCTL_PIO_INBUF_EN |
                                     IOPCTL_PIO_SLEW_RATE_NORMAL |
                                     IOPCTL_PIO_DRIVE_100OHM |
                                     IOPCTL_PIO_ANAMUX_DI |
                                     IOPCTL_PIO_PSEDRAIN_DI |
                                     IOPCTL_PIO_INV_DI);
    IOPCTL_PinMuxSet(2U, 5U, gpio_in_config);

    /* RESET: GPIO2_0 (output) */
    const uint32_t gpio_out_config = (IOPCTL_PIO_FUNC0 |
                                      IOPCTL_PIO_PUPD_DI |
                                      IOPCTL_PIO_PULLDOWN_EN |
                                      IOPCTL_PIO_INBUF_DI |
                                      IOPCTL_PIO_SLEW_RATE_NORMAL |
                                      IOPCTL_PIO_DRIVE_100OHM |
                                      IOPCTL_PIO_ANAMUX_DI |
                                      IOPCTL_PIO_PSEDRAIN_DI |
                                      IOPCTL_PIO_INV_DI);
    IOPCTL_PinMuxSet(2U, 0U, gpio_out_config);
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPsRamPins_Xspi2
 * Description   : Configures the XSPI2 16-bit HyperRAM pins (IOPCTL2 port4,
 *                 PIO4_0..PIO4_20, FUNC1) for the FRDM-IMXRT700 on-board
 *                 W958D6NMYA4I HyperRAM. Must run before BOARD_Init16bitsPsRam().
 *
 * END ****************************************************************************************************************/
void BOARD_InitPsRamPins_Xspi2(void)
{
    /* The FRDM-IMXRT700 has a 16-bit HyperRAM (Winbond W958D6NMYA4I) on XSPI2.
     * Its interface signals (XSPI2_DATA0..15, DQS0/DQS1, SCLK0, SS0_N) are all
     * routed to IOPCTL2 port4, functions PIO4_0..PIO4_20 (FUNC1) per the board
     * schematic (RT700_FRDM_SCH-96317_A).
     *
     * These pins MUST be muxed here, BEFORE BOARD_Init16bitsPsRam(XSPI2) runs.
     * BOARD_Init16bitsPsRam() only programs the XSPI controller (clocks, DLL,
     * calibration); it does NOT configure the IOPCTL pin mux. If the pins are
     * left unrouted, the XSPI DLL never locks and BOARD_Init16bitsPsRam() spins
     * forever in its "wait for SLVA_LOCK" loop. Because that call happens before
     * the FreeRTOS scheduler starts (and before the application prints anything),
     * the symptom is a completely silent debug console. */
    RESET_ClearPeripheralReset(kIOPCTL2_RST_SHIFT_RSTn);

    const uint32_t xspi2_pin_config = (IOPCTL_PIO_FUNC1 |
                                       IOPCTL_PIO_PUPD_DI |
                                       IOPCTL_PIO_PULLDOWN_EN |
                                       IOPCTL_PIO_INBUF_EN |
                                       IOPCTL_PIO_SLEW_RATE_NORMAL |
                                       IOPCTL_PIO_DRIVE_100OHM |
                                       IOPCTL_PIO_ANAMUX_DI |
                                       IOPCTL_PIO_PSEDRAIN_DI |
                                       IOPCTL_PIO_INV_DI);

    /* PIO4_0 .. PIO4_20: XSPI2 16-bit HyperRAM bus */
    for (uint32_t pin = 0U; pin <= 20U; pin++)
    {
        IOPCTL_PinMuxSet(4U, pin, xspi2_pin_config);
    }
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPmicPins
 * Description   : Configures dedicated PMIC I2C pins via IOPCTL1 registers.
 *                 PMIC_I2C_SCL and PMIC_I2C_SDA are special pins on MIMXRT798S
 *                 controlled through IOPCTL1->PMIC_I2C_SCL/SDA (not standard IOPCTL0).
 *                 Both pins need input buffer and open-drain mode enabled.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPmicPins(void)
{
    /* Reset IOPCTL1 module */
    RESET_ClearPeripheralReset(kIOPCTL1_RST_SHIFT_RSTn);

    /* PMIC_I2C_SCL: enable input buffer + open-drain */
    IOPCTL1->PMIC_I2C_SCL = ((IOPCTL1->PMIC_I2C_SCL &
                              (~(IOPCTL1_PMIC_I2C_SCL_IBENA_MASK | IOPCTL1_PMIC_I2C_SCL_ODENA_MASK)))
                             | IOPCTL1_PMIC_I2C_SCL_IBENA(1U)
                             | IOPCTL1_PMIC_I2C_SCL_ODENA(1U));

    /* PMIC_I2C_SDA: enable input buffer + open-drain */
    IOPCTL1->PMIC_I2C_SDA = ((IOPCTL1->PMIC_I2C_SDA &
                              (~(IOPCTL1_PMIC_I2C_SDA_IBENA_MASK | IOPCTL1_PMIC_I2C_SDA_ODENA_MASK)))
                             | IOPCTL1_PMIC_I2C_SDA_IBENA(1U)
                             | IOPCTL1_PMIC_I2C_SDA_ODENA(1U));
}
