# Copyright 2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
CONFIG_CLOCK_CONTROL=y
CONFIG_FLASH=y
CONFIG_MCUX_COMPONENT_component.gen_hal=y
CONFIG_DEBUG_COREDUMP=y
CONFIG_DEBUG_COREDUMP_BACKEND_FLASH_PARTITION=y
