/*
 * Copyright 2026 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define BOARD_INITPINS_IOMUXC_GPR_GPR27_GPIO_MUX2_GPIO_SEL_MASK 0x10000140U /*!< GPIO2 and GPIO7 share same IO MUX function, GPIO_MUX2 selects one GPIO function: affected bits mask */

/* GPIO_B0_15 (coord D11), LCDIF_D11/J49[A8]/BT_CFG[11] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D11_PERIPHERAL                                 SAI1   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D11_SIGNAL                              sai_rx_bclk   /*!< Signal name */

/* GPIO_B0_14 (coord C11), LCDIF_D10/J49[A20]/BT_CFG[10] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D10_PERIPHERAL                                 SAI1   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D10_SIGNAL                              sai_rx_sync   /*!< Signal name */

/* GPIO_AD_B0_12 (coord J12), UART1_TXD/J13[2] */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_TXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_TXD_SIGNAL                                       TX   /*!< Signal name */

/* GPIO_AD_B0_13 (coord J11), UART1_RXD/J11[2] */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_RXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_RXD_SIGNAL                                       RX   /*!< Signal name */

/* GPIO_B0_13 (coord C10), LCDIF_D9/J49[A19]/BT_CFG[9] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D9_PERIPHERAL                                  SAI1   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D9_SIGNAL                                  sai_mclk   /*!< Signal name */

/* GPIO_B1_00 (coord A11), LCDIF_D12/J49[A9] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D12_PERIPHERAL                                 SAI1   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D12_SIGNAL                             sai_rx_data0   /*!< Signal name */

/* GPIO_B1_02 (coord E12), LCDIF_D14/J49[A11] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D14_PERIPHERAL                                 SAI1   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D14_SIGNAL                              sai_tx_bclk   /*!< Signal name */

/* GPIO_B1_01 (coord A12), LCDIF_D13/J49[A10] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D13_PERIPHERAL                                 SAI1   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D13_SIGNAL                             sai_tx_data0   /*!< Signal name */

/* GPIO_B1_03 (coord E10), LCDIF_D15/J49[A12] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D15_PERIPHERAL                                 SAI1   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D15_SIGNAL                              sai_tx_sync   /*!< Signal name */

/* GPIO_AD_B1_06 (coord H10), J33[5]/I2C3_SDA/J23[15]/J24[5]/U66[4] */
/* Routed pin properties */
#define BOARD_INITPINS_I2C3_SDA_PERIPHERAL                                LPI2C3   /*!< Peripheral name */
#define BOARD_INITPINS_I2C3_SDA_SIGNAL                                       SDA   /*!< Signal name */

/* GPIO_AD_B1_07 (coord J10), J33[6]/I2C3_SCL/J23[13]/J24[3]/U66[5] */
/* Routed pin properties */
#define BOARD_INITPINS_I2C3_SCL_PERIPHERAL                                LPI2C3   /*!< Peripheral name */
#define BOARD_INITPINS_I2C3_SCL_SIGNAL                                       SCL   /*!< Signal name */

/* GPIO_B0_06 (coord B8), LCDIF_D2/J49[A26]/BT_CFG[2] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D2_PERIPHERAL                                 GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D2_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D2_CHANNEL                                       6U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LCDIF_D2_GPIO                                       GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LCDIF_D2_GPIO_PIN                                      6U   /*!< GPIO pin number */
#define BOARD_INITPINS_LCDIF_D2_GPIO_PIN_MASK                         (1U << 6U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LCDIF_D2_PORT                                       GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LCDIF_D2_PIN                                           6U   /*!< PORT pin number */
#define BOARD_INITPINS_LCDIF_D2_PIN_MASK                              (1U << 6U)   /*!< PORT pin mask */

/* GPIO_B0_08 (coord A10), LCDIF_D4/J49[A28]/BT_CFG[4] */
/* Routed pin properties */
#define BOARD_INITPINS_LCDIF_D4_PERIPHERAL                                 GPIO7   /*!< Peripheral name */
#define BOARD_INITPINS_LCDIF_D4_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_LCDIF_D4_CHANNEL                                       8U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LCDIF_D4_GPIO                                       GPIO7   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_LCDIF_D4_GPIO_PIN                                      8U   /*!< GPIO pin number */
#define BOARD_INITPINS_LCDIF_D4_GPIO_PIN_MASK                         (1U << 8U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_LCDIF_D4_PORT                                       GPIO7   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_LCDIF_D4_PIN                                           8U   /*!< PORT pin number */
#define BOARD_INITPINS_LCDIF_D4_PIN_MASK                              (1U << 8U)   /*!< PORT pin mask */

/* GPIO_SD_B0_01 (coord K3), J17[3]/U63[7] */
/* Routed pin properties */
#define BOARD_INITPINS_GPIO_SD_B0_01_PERIPHERAL                           USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_GPIO_SD_B0_01_SIGNAL                            usdhc_clk   /*!< Signal name */

/* GPIO_SD_B0_00 (coord H3), J17[6]/U63[8] */
/* Routed pin properties */
#define BOARD_INITPINS_GPIO_SD_B0_00_PERIPHERAL                           USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_GPIO_SD_B0_00_SIGNAL                            usdhc_cmd   /*!< Signal name */

/* GPIO_SD_B0_02 (coord J3), J17[4]/U64[8] */
/* Routed pin properties */
#define BOARD_INITPINS_GPIO_SD_B0_02_PERIPHERAL                           USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_GPIO_SD_B0_02_SIGNAL                           usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_GPIO_SD_B0_02_CHANNEL                                  0U   /*!< Signal channel */

/* GPIO_SD_B0_03 (coord J2), J17[5]/U64[7] */
/* Routed pin properties */
#define BOARD_INITPINS_GPIO_SD_B0_03_PERIPHERAL                           USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_GPIO_SD_B0_03_SIGNAL                           usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_GPIO_SD_B0_03_CHANNEL                                  1U   /*!< Signal channel */

/* GPIO_SD_B0_04 (coord J4), U65[8] */
/* Routed pin properties */
#define BOARD_INITPINS_GPIO_SD_B0_04_PERIPHERAL                           USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_GPIO_SD_B0_04_SIGNAL                           usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_GPIO_SD_B0_04_CHANNEL                                  2U   /*!< Signal channel */

/* GPIO_SD_B0_05 (coord J1), U65[7] */
/* Routed pin properties */
#define BOARD_INITPINS_GPIO_SD_B0_05_PERIPHERAL                           USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_GPIO_SD_B0_05_SIGNAL                           usdhc_data   /*!< Signal name */
#define BOARD_INITPINS_GPIO_SD_B0_05_CHANNEL                                  3U   /*!< Signal channel */

/* GPIO_B1_14 (coord E13), SD0_VSELECT/J17[1] */
/* Routed pin properties */
#define BOARD_INITPINS_SD0_VSELECT_PERIPHERAL                             USDHC1   /*!< Peripheral name */
#define BOARD_INITPINS_SD0_VSELECT_SIGNAL                          usdhc_vselect   /*!< Signal name */

/* GPIO_B1_12 (coord F13), SD_CD_SW/J22[9] */
/* Routed pin properties */
#define BOARD_INITPINS_SD_CD_SW_PERIPHERAL                                 GPIO2   /*!< Peripheral name */
#define BOARD_INITPINS_SD_CD_SW_SIGNAL                                   gpio_io   /*!< Signal name */
#define BOARD_INITPINS_SD_CD_SW_CHANNEL                                      28U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SD_CD_SW_GPIO                                       GPIO2   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_SD_CD_SW_GPIO_PIN                                     28U   /*!< GPIO pin number */
#define BOARD_INITPINS_SD_CD_SW_GPIO_PIN_MASK                        (1U << 28U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_SD_CD_SW_PORT                                       GPIO2   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_SD_CD_SW_PIN                                          28U   /*!< PORT pin number */
#define BOARD_INITPINS_SD_CD_SW_PIN_MASK                             (1U << 28U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
