#
# Copyright 2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
CONFIG_RPMSG_M71_M33S=y
#CONFIG_RPMSG_M33S_M71=y
#CONFIG_RPMSG_M33S_M70=y
#CONFIG_RPMSG_M70_M71=y
#CONFIG_RPMSG_M70_M33S=y
#CONFIG_RPMSG_M71_M70=y

