/** @file key_cert.h
 *
 *  @brief This file provides CA certificate, own csertificate and own private key.
 *
 *  Copyright 2024 NXP
 *
 *  SPDX-License-Identifier: BSD-3-Clause
 *
 */

#include "ncp_tlv_adapter.h"

#define CONFIG_TLS_CIPHERSUITE  MBEDTLS_TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256

const char CA_CERT[] = 
"-----BEGIN CERTIFICATE-----\n\
MIICDjCCAbOgAwIBAgIUf556rYfAGUKR64LzlQPEWb50nIUwCgYIKoZIzj0EAwIw\n\
XDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAkNBMRAwDgYDVQQHDAdTQU5KT1NFMQww\n\
CgYDVQQKDANOWFAxDDAKBgNVBAsMA1dDUzESMBAGA1UEAwwJbG9jYWxob3N0MB4X\n\
DTI1MDEwMzA1NDUyOFoXDTI3MDkzMDA1NDUyOFowXDELMAkGA1UEBhMCVVMxCzAJ\n\
BgNVBAgMAkNBMRAwDgYDVQQHDAdTQU5KT1NFMQwwCgYDVQQKDANOWFAxDDAKBgNV\n\
BAsMA1dDUzESMBAGA1UEAwwJbG9jYWxob3N0MFkwEwYHKoZIzj0CAQYIKoZIzj0D\n\
AQcDQgAEvuG2utSVL65vcCk/39aSqiWY3ZVOuxyefyocgpv6f3GD7IadSkVF3ysC\n\
HDgGd8oDdXsYqDDH7vu/WUEfWfdwr6NTMFEwHQYDVR0OBBYEFA4jJyiex+sOVu3p\n\
+LxodG0NLfkBMB8GA1UdIwQYMBaAFA4jJyiex+sOVu3p+LxodG0NLfkBMA8GA1Ud\n\
EwEB/wQFMAMBAf8wCgYIKoZIzj0EAwIDSQAwRgIhAPs6Q7j1MWuX6n7U5OHVJr+L\n\
2AnzSxoviJ6SmC6ovhlrAiEA181gQp8aiYYfm8ahlKKlQPn/JdSBtgX4Aqpf9wPV\n\
UHY=\n\
-----END CERTIFICATE-----\n";

const char OWN_CERT[] = 
"-----BEGIN CERTIFICATE-----\n\
MIIBszCCAVkCFDZQY49dpUcg1ddHiduwkEkPKsaBMAoGCCqGSM49BAMCMFwxCzAJ\n\
BgNVBAYTAlVTMQswCQYDVQQIDAJDQTEQMA4GA1UEBwwHU0FOSk9TRTEMMAoGA1UE\n\
CgwDTlhQMQwwCgYDVQQLDANXQ1MxEjAQBgNVBAMMCWxvY2FsaG9zdDAeFw0yNTAx\n\
MDMwNTQ2MjlaFw0yNzA5MzAwNTQ2MjlaMFwxCzAJBgNVBAYTAlVTMQswCQYDVQQI\n\
DAJDQTEQMA4GA1UEBwwHU0FOSk9TRTEMMAoGA1UECgwDTlhQMQwwCgYDVQQLDANX\n\
Q1MxEjAQBgNVBAMMCWxvY2FsaG9zdDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA\n\
BCFajGqoUyBkQ+Tz8p9CreK731UDBFzeGraB1609pv5oN3buU/cODT+og+aNjJkH\n\
1fB5YPMgUqkg1Rh71wEpdDcwCgYIKoZIzj0EAwIDSAAwRQIgaSJpUSKJUQwHwwZE\n\
6QXJqoiP7jIxMlzLyYSWrk7Av0wCIQDcIGyrEv3FrUBfaxPN+vi+FnQMI90Hn35M\n\
AMq8X67aVg==\n\
-----END CERTIFICATE-----\n";


#if !CONFIG_NCP_IS_PVTKEY_ENCRYPTED

#define TLS_KEY_PASSWORD                 NULL
#define TLS_KEY_PASSWORD_LEN             0

const char OWN_PVTKEY[] = 
"-----BEGIN PRIVATE KEY-----\n\
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgLzOLmgz5dyJu5YaJ\n\
FQI0UBBHbKL4j8Ujk0+7GeJbkTqhRANCAAQhWoxqqFMgZEPk8/KfQq3iu99VAwRc\n\
3hq2gdetPab+aDd27lP3Dg0/qIPmjYyZB9XweWDzIFKpINUYe9cBKXQ3\n\
-----END PRIVATE KEY-----\n";

#else

#define TLS_KEY_PASSWORD                 "12345678"
#define TLS_KEY_PASSWORD_LEN             8

const char OWN_PVTKEY[] = 
"-----BEGIN ENCRYPTED PRIVATE KEY-----\n\
MIHjME4GCSqGSIb3DQEFDTBBMCkGCSqGSIb3DQEFDDAcBAj5kOfC3KnddwICCAAw\n\
DAYIKoZIhvcNAgkFADAUBggqhkiG9w0DBwQITh3OJYqI1AMEgZCsb5jU7vJmtt0Z\n\
PB2rIcm3bod5nB9FujUuZbe72gDTJA9/kne9VIro9xYIXNY9egp3Gx1QMtO4mnBd\n\
fn6R00yjdlCF9mDMtqsw+OD5AaGPWY56KiD2MBfkWJEXImyC6T0LV5ZeFP+qVA5S\n\
ySis0MUPmVdtwpKhNykGaRTFP923Yv43FxzkNebkR1dJ3DCqLFc=\n\
-----END ENCRYPTED PRIVATE KEY-----\n";

#endif
