
mcux_add_macro(
    CC "-DBOARD_DEBUG_UART_CLK_ROOT=kCLOCK_Root_Lpuart1112\
       -DBOARD_DEBUG_UART_BASEADDR=LPUART12\
       -DBOARD_DEBUG_UART_INSTANCE=12\
       -DBOARD_UART_IRQ=LPUART12_IRQn\
       -DBOARD_UART_IRQ_HANDLER=LPUART12_IRQHandler\
       -DMCMGR_HANDLE_EXCEPTIONS=1\
       -D__SEMIHOST_HARDFAULT_DISABLE=1"
)
