# Component
CONFIG_MCUX_COMPONENT_component.els_pkc=y
CONFIG_MCUX_COMPONENT_component.els_pkc.platform.rw61x=y
CONFIG_MCUX_COMPONENT_component.messaging=y
CONFIG_MCUX_COMPONENT_component.mflash_offchip=y
CONFIG_MCUX_COMPONENT_component.power_manager_framework=y
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.els_pkc=y
CONFIG_MCUX_DEPENDENCY_COMPONENT_component.psa_crypto_driver.els_pkc.osal_frtos=y
CONFIG_MCUX_COMPONENT_component.rng_adapter_interface=y
CONFIG_MCUX_COMPONENT_component.software_rng_adapter=y
CONFIG_MCUX_COMPONENT_component.usart_adapter=y
CONFIG_MCUX_COMPONENT_component.wifi_bt_module.RW61X=y
CONFIG_MCUX_COMPONENT_component.wireless_imu_adapter=y
CONFIG_MCUX_COMPONENT_driver.conn_fwloader=y
CONFIG_MCUX_COMPONENT_driver.flash_config=y
CONFIG_MCUX_COMPONENT_driver.flexcomm_i2c=y
CONFIG_MCUX_COMPONENT_driver.flexcomm_usart_freertos=y
CONFIG_MCUX_COMPONENT_driver.io_mux=y
CONFIG_MCUX_COMPONENT_driver.lpc_rtc=y
CONFIG_MCUX_COMPONENT_driver.reset=y
CONFIG_MCUX_COMPONENT_driver.trng=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.cm33_non_trustzone=y
CONFIG_MCUX_COMPONENT_middleware.littlefs=y
CONFIG_MCUX_COMPONENT_middleware.SECURE_STORAGE=y
CONFIG_MCUX_COMPONENT_middleware.SECURE_STORAGE_ITS_IMPLEMENTATION=y
CONFIG_MCUX_COMPONENT_middleware.SECURE_STORAGE_ITS_STORE_IMPLEMENTATION_LITTLEFS=y
CONFIG_MCUX_COMPONENT_middleware.usb.common_header=y
CONFIG_MCUX_COMPONENT_middleware.usb.host.common_header=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.file_system=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.function_lib=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.lowpower=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.platform.ble=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.platform.coex=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.platform.hdlc=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.platform.ot=y
CONFIG_MCUX_COMPONENT_utility.assert=y
CONFIG_MCUX_COMPONENT_utility.debug_console=y
CONFIG_MCUX_PRJSEG_middleware.freertos-kernel.generated_config=n
CONFIG_MCUX_PRJSEG_module.board.wireless.board.lowpower=y

# Wi-Fi config
CONFIG_MCUX_COMPONENT_middleware.wifi.imu=y
CONFIG_MCUX_DEPENDENCY_COMPONENT_middleware.wifi.wifidriver_DEPEND_ANYOF_OPTION_2=y

# BT config
CONFIG_BLE_ADV_REPORT_BUFFER_FILTER=y
CONFIG_BT_AUTO_PHY_UPDATE=y
CONFIG_BT_DATA_LEN_UPDATE=y

# OT support
# CONFIG_SETTINGS=y
# CONFIG_MCUX_COMPONENT_middleware.wireless.framework.zephyr_port.settings.redefine_api=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.seclib_rng=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.seclib_rng_port.psa=y

# Misc
CONFIG_DEBUG_CONSOLE_PRINTF_MAX_LOG_LEN=512
CONFIG_DEBUG_CONSOLE_TRANSMIT_BUFFER_LEN=4096
CONFIG_DEBUG_CONSOLE_TX_RELIABLE_ENABLE=y
CONFIG_SECURE_STORAGE_ITS_STORE_LITTLEFS_PREFIX="its"
CONFIG_SHELL_BUFFER_SIZE=512
