# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=y

CONFIG_LITTLEFS_START_ADDR=0x80000

CONFIG_LITTLEFS_BLOCK_SIZE=8192
CONFIG_LITTLEFS_BLOCK_COUNT=32
