/*
 * Copyright 2025 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

/*! @name PTE14 (number 26), dsa
  @{ */

/* Defined symbols */
#define BOARD_INITDEBUG_UARTPINS_dsa_PORT PTE                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_dsa_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_dsa_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);

/*! @name PTE3 (number 27), pin_pte3_config
  @{ */

/* Defined symbols */
#define BOARD_INITDEBUG_UARTPINS_DEINIT_pin_pte3_config_PORT PTE                 /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_DEINIT_pin_pte3_config_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_DEINIT_pin_pte3_config_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                                                 /* @} */

/*! @name PTE14 (number 26)
  @{ */

/* Defined symbols */
#define BOARD_INITDEBUG_UARTPINS_DEINIT_dsa_PORT PTE                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITDEBUG_UARTPINS_DEINIT_dsa_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITDEBUG_UARTPINS_DEINIT_dsa_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                                      /* @} */

/*!
 * @brief This is a de-initialization function for 'BOARD_InitDEBUG_UARTPins' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 */
void BOARD_InitDEBUG_UARTPins_deinit(void);

/*! @name PTC16 (number 66), LED1
  @{ */

/* Symbols to be used with SIUL2 driver */
#define BOARD_INITLEDSPINS_LED1_SIUL2_BASE SIUL2          /*!<@brief SIUL2 peripheral base pointer */
#define BOARD_INITLEDSPINS_LED1_GPIO kSIUL2_PTC           /*!<@brief GPIO peripheral port */
#define BOARD_INITLEDSPINS_LED1_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITLEDSPINS_LED1_GPIO_PIN_MASK (1U << 80U) /*!<@brief GPIO pin mask */

/* Defined symbols */
#define BOARD_INITLEDSPINS_LED1_PORT PTC                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED1_PIN 16U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED1_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PTC14 (number 71), LED2
  @{ */

/* Symbols to be used with SIUL2 driver */
#define BOARD_INITLEDSPINS_LED2_SIUL2_BASE SIUL2          /*!<@brief SIUL2 peripheral base pointer */
#define BOARD_INITLEDSPINS_LED2_GPIO kSIUL2_PTC           /*!<@brief GPIO peripheral port */
#define BOARD_INITLEDSPINS_LED2_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITLEDSPINS_LED2_GPIO_PIN_MASK (1U << 78U) /*!<@brief GPIO pin mask */

/* Defined symbols */
#define BOARD_INITLEDSPINS_LED2_PORT PTC                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED2_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED2_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PTB22 (number 67), LED3
  @{ */

/* Symbols to be used with SIUL2 driver */
#define BOARD_INITLEDSPINS_LED3_SIUL2_BASE SIUL2          /*!<@brief SIUL2 peripheral base pointer */
#define BOARD_INITLEDSPINS_LED3_GPIO kSIUL2_PTB           /*!<@brief GPIO peripheral port */
#define BOARD_INITLEDSPINS_LED3_INIT_GPIO_VALUE 1U        /*!<@brief GPIO output initial state */
#define BOARD_INITLEDSPINS_LED3_GPIO_PIN_MASK (1U << 54U) /*!<@brief GPIO pin mask */

/* Defined symbols */
#define BOARD_INITLEDSPINS_LED3_PORT PTB                  /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLEDSPINS_LED3_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITLEDSPINS_LED3_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void);

/*! @name PTD5 (number 53), BUTTON1
  @{ */

/* Defined symbols */
#define BOARD_INITBUTTONSPINS_BUTTON1_PORT PTD                 /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONSPINS_BUTTON1_PIN 5U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONSPINS_BUTTON1_PIN_MASK (1U << 5U)      /*!<@brief PORT pin mask */
                                                               /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_MC_LCU_init(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_MC_ADC_init(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_MC_ENC_Init(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
