CONFIG_MCUX_PRJSEG_module.board.pinmux_board_core_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_COMPONENT_driver.mipi_dsi=y
CONFIG_MCUX_COMPONENT_driver.display-rpi=y
CONFIG_MCUX_COMPONENT_driver.lpflexcomm_lpi2c=y