# Copyright 2024-2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_COMPONENT_middleware.mbedtls=y
CONFIG_MCUX_PRJSEG_module.board.console_lite=n
CONFIG_MCUX_PRJSEG_module.board.console=y

# lwIP configuration:
CONFIG_MCUX_COMPONENT_middleware.lwip=y
CONFIG_MCUX_PRJSEG_middleware.lwip.generated_config=y
CONFIG_LWIP_OPT_H_CODE_LINE_1="void sys_check_core_locking(void);"
CONFIG_NO_SYS=y
CONFIG_LWIP_NETCONN=n
CONFIG_LWIP_SOCKET=n
CONFIG_LWIP_ASSERT_CORE_LOCKED( )="sys_check_core_locking()"
CONFIG_MEM_ALIGNMENT=4
CONFIG_MEM_SIZE=22528
CONFIG_MEMP_NUM_PBUF=15
CONFIG_MEMP_NUM_UDP_PCB=6
CONFIG_MEMP_NUM_TCP_PCB=10
CONFIG_MEMP_NUM_TCP_PCB_LISTEN=6
CONFIG_MEMP_NUM_TCP_SEG=22
CONFIG_MEMP_NUM_SYS_TIMEOUT="12"
CONFIG_MEMP_NUM_REASSDATA=2
CONFIG_PBUF_POOL_SIZE=5
CONFIG_LWIP_NETIF_EXT_STATUS_CALLBACK=y
CONFIG_LWIP_TCP=y
CONFIG_TCP_TTL=255
CONFIG_TCP_QUEUE_OOSEQ=n
CONFIG_TCP_MSS=1460
CONFIG_TCP_SND_BUF="(6 * TCP_MSS)"
CONFIG_TCP_SND_QUEUELEN="((3 * TCP_SND_BUF) / TCP_MSS)"
CONFIG_TCP_WND="(2 * TCP_MSS)"
CONFIG_TCP_LISTEN_BACKLOG=y
CONFIG_LWIP_ICMP=y
CONFIG_LWIP_DHCP=y
CONFIG_LWIP_UDP=y
CONFIG_UDP_TTL=255
CONFIG_LWIP_STATS=n
CONFIG_LWIP_PROVIDE_ERRNO=y
CONFIG_LWIP_IPV6=y
CONFIG_DEFAULT_THREAD_STACKSIZE=3000
CONFIG_DEFAULT_THREAD_PRIO=3
CONFIG_LWIP_DEBUG=y
CONFIG_TCPIP_MBOX_SIZE=32
CONFIG_TCPIP_THREAD_STACKSIZE=1024
CONFIG_TCPIP_THREAD_PRIO=8
CONFIG_DEFAULT_RAW_RECVMBOX_SIZE=12
CONFIG_DEFAULT_UDP_RECVMBOX_SIZE=12
CONFIG_DEFAULT_TCP_RECVMBOX_SIZE=12
CONFIG_DEFAULT_ACCEPTMBOX_SIZE=12
CONFIG_IP_REASS_MAX_PBUFS=4
CONFIG_LWIP_SINGLE_NETIF=y
