#
# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause
#select profile
CONFIG_MCUX_COMPONENT_middleware.tfm.profile_medium=y

#include pin_mux board component
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_core_folder=y

#drivers
CONFIG_MCUX_COMPONENT_middleware.tfm.lpuart=y
CONFIG_MCUX_COMPONENT_driver.ctimer=y

CONFIG_FLASH_BASE_ADDRESS=0x00000000

# Temporary disablement, till the implementation is in TF-M mainline
CONFIG_MCUX_COMPONENT_middleware.tfm.ns.romapi=n

# Enable builtin CRC driver module 
CONFIG_MCUX_COMPONENT_driver.crc=y