
mcux_add_macro(
    CC "-DSDK_I2C_BASED_COMPONENT_USED=1\
       -DBOARD_USE_PCAL6524=1"
)
mcux_add_macro(
    TOOLCHAINS armgcc iar
    CC "-DPHY_STABILITY_DELAY_US=500000U\
       -DPHY_AUTONEGO_TIMEOUT_COUNT=600000U"
)
