CONFIG_MCUX_COMPONENT_component.osa=y
CONFIG_MCUX_COMPONENT_component.osa_free_rtos=y
CONFIG_MCUX_COMPONENT_component.lce=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.heap_4=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.cm33_non_trustzone=y
