
mcux_add_macro(
    CC "-DEXAMPLE_DHARA_GARBAGE_COLLECTION_RATIO=255\
       -DEXAMPLE_DHARA_NAND_LOG2_PAGE_SIZE=12\
       -DEXAMPLE_DHARA_NAND_LOG2_PAGE_PER_BLOCK=7\
       -DEXAMPLE_DHARA_NAND_BLOCKS_NUMBER=4096\
       -DPRINTF_FLOAT_ENABLE=1\
       -DEXAMPLE_DHARA_ENABLE_SOFTWARE_ECC"
)
