CONFIG_MCUX_COMPONENT_component.serial_manager=y
CONFIG_SERIAL_MANAGER_NON_BLOCKING_MODE=y

# BLE Host stack configuration
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_hci_transport_ipm=y

# SecLib on PSA
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.seclib_rng_port.psa=y
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.casper=y
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.hashcrypt=y

CONFIG_MCUX_PRJSEG_module.board.wireless.ble_app_mbedtls_psa_config=y
