CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_folder=n
CONFIG_MCUX_PRJSEG_module.board.suite=n
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.bootsources=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.MIMXRT1011_drivers=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.MIMXRT1011_sources=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.MIMXRT1011_startup=y
CONFIG_MCUX_COMPONENT_middleware.baremetal=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.src_bm_usb_hid=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.usb.device.common_header=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.usb.phy=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.usb.device.controller.driver=y
CONFIG_MCUX_COMPONENT_component.lists=y
CONFIG_MCUX_COMPONENT_platform.drivers.memory=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.CMSIS_cm7_headers=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.src_startup=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.drv_microseconds_pit=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.drv_ocotp=y
CONFIG_MCUX_PRJSEG_evkmimxrt1010_kboot_options=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.usb.device.hid=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.usb.device.stack=y
CONFIG_MCUX_PRJSEG_middleware.mcu-boot.MIMXRT1011_ram_flashloader_linker=y
CONFIG_MCUX_COMPONENT_device.CMSIS=y
CONFIG_MCUX_PRJSEG_module.board.boardfile=n
CONFIG_MCUX_PRJSEG_module.board.clock_board_folder=n
CONFIG_MCUX_PRJSEG_module.board.clock_board_core_folder=n
CONFIG_MCUX_COMPONENT_board.boot_header=n
CONFIG_MCUX_COMPONENT_component.lpuart_adapter=n
CONFIG_MCUX_COMPONENT_component.lpuart_dma_adapter=n
CONFIG_MCUX_COMPONENT_driver.cache_armv7_m7=n
CONFIG_MCUX_COMPONENT_driver.dcdc_1=n
CONFIG_MCUX_COMPONENT_utility.debug_console_lite=n
CONFIG_MCUX_COMPONENT_device.boot_header=n
CONFIG_MCUX_COMPONENT_driver.gpc_1=n
CONFIG_MCUX_COMPONENT_driver.pmu=n
CONFIG_MCUX_COMPONENT_driver.src=n
CONFIG_MCUX_COMPONENT_utility.str=n
MCUX_PRJSEG_module.board.clock=n
 