CONFIG_MCUX_COMPONENT_middleware.canopennode=y
CONFIG_MCUX_COMPONENT_middleware.canopennode.301=y
CONFIG_MCUX_COMPONENT_middleware.canopennode.303=y
CONFIG_MCUX_COMPONENT_middleware.canopennode.304=y
CONFIG_MCUX_COMPONENT_middleware.canopennode.305=y
CONFIG_MCUX_COMPONENT_middleware.canopennode.309=y
CONFIG_MCUX_COMPONENT_middleware.canopennode.extra=y
CONFIG_MCUX_COMPONENT_middleware.canopennode.storage=y
