# Copyright 2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_COMPONENT_component.phyrtl8211f=y
CONFIG_MCUX_COMPONENT_driver.enet=y
CONFIG_MCUX_COMPONENT_middleware.lwip.kinetis_ethernetif=y
CONFIG_MCUX_PRJSEG_project.hw_app_project_folder=y
CONFIG_LWIP_ENET_FLEXIBLE_CONFIGURATION=y
