
CONFIG_MCUX_COMPONENT_component.els_pkc=y
CONFIG_MCUX_COMPONENT_component.els_pkc.rsa=y
CONFIG_MCUX_COMPONENT_component.power_manager_framework=y
CONFIG_MCUX_COMPONENT_component.wireless_imu_adapter=y
CONFIG_MCUX_COMPONENT_driver.conn_fwloader=y
CONFIG_MCUX_COMPONENT_driver.flexcomm_usart_freertos=y
CONFIG_MCUX_COMPONENT_driver.lpc_rtc=y
CONFIG_MCUX_COMPONENT_driver.trng=y
CONFIG_MCUX_COMPONENT_middleware.fatfs=y
CONFIG_MCUX_COMPONENT_middleware.fatfs.usb=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.heap_4=y
CONFIG_MCUX_COMPONENT_middleware.lwip=y
CONFIG_MCUX_COMPONENT_middleware.lwip.apps.lwiperf=y
#CONFIG_MCUX_COMPONENT_middleware.usb.host.ehci=y
#CONFIG_MCUX_COMPONENT_middleware.usb.host.stack=y
CONFIG_MCUX_COMPONENT_middleware.wifi=y
CONFIG_MCUX_COMPONENT_middleware.wifi.cli=y
CONFIG_MCUX_COMPONENT_middleware.wifi.imu=y
CONFIG_MCUX_COMPONENT_middleware.wifi.osa_free_rtos=y
CONFIG_MCUX_COMPONENT_middleware.wifi.wifidriver=y
CONFIG_MCUX_COMPONENT_middleware.wireless.wpa_supplicant.rtos=y
CONFIG_MCUX_COMPONENT_utility.assert=y
CONFIG_MCUX_COMPONENT_utility.debug_console=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.cm33_non_trustzone=y
CONFIG_MCUX_COMPONENT_component.mflash_offchip=y
CONFIG_MCUX_DEPENDENCY_COMPONENT_middleware.wifi.wifidriver_DEPEND_ANYOF_OPTION_2=y
CONFIG_MCUX_COMPONENT_middleware.wifi.net_free_rtos=y
CONFIG_MCUX_COMPONENT_middleware.usb.host.common_header=y
CONFIG_MCUX_COMPONENT_middleware.usb.common_header=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.extension=y
CONFIG_MCUX_COMPONENT_component.wifi_bt_module.RW61X=y
CONFIG_MCUX_COMPONENT_driver.wifi.libcsi=n
CONFIG_MCUX_COMPONENT_middleware.wifi.wifidriver.softap=n
CONFIG_MCUX_COMPONENT_middleware.wireless.wpa_supplicant.rtos.hostapd=n
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.port.config=y
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.els_pkc=y
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.mbedtls_thread_alt=y
# Enable secure storage usage. 
CONFIG_MCUX_COMPONENT_component.mflash_offchip=y
CONFIG_MCUX_COMPONENT_driver.flexspi=y
CONFIG_MCUX_COMPONENT_middleware.littlefs=y
CONFIG_MCUX_COMPONENT_middleware.littlefs_mflash=y
CONFIG_MCUX_COMPONENT_middleware.SECURE_STORAGE=y
CONFIG_MCUX_COMPONENT_middleware.SECURE_STORAGE_ITS_IMPLEMENTATION_WITH_ONLY_STORE=y
CONFIG_MCUX_COMPONENT_middleware.SECURE_STORAGE_ITS_STORE_IMPLEMENTATION_LITTLEFS=y
CONFIG_SECURE_STORAGE_ITS_MAX_DATA_SIZE=2208
CONFIG_LITTLEFS_START_ADDR=0x03FF0000
CONFIG_LITTLEFS_READ_SIZE=16
CONFIG_LITTLEFS_BLOCK_SIZE=4096
CONFIG_LITTLEFS_BLOCK_COUNT=16
CONFIG_LITTLEFS_PROG_SIZE=256
CONFIG_LITTLEFS_BLOCK_CYCLES=500
CONFIG_LITTLEFS_CACHE_SIZE=256
CONFIG_LITTLEFS_LOOKAHEAD_SIZE=16
