# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

# IS25WP064A
# total size: 64Mbit -> 8MB -> 0x800000 B

# littlefs offset
CONFIG_LITTLEFS_START_ADDR=0x600000

# 0x800000 - 0x600000 = 0x200000, 2 MB
# block size = 4096 B = 0x1000 B = 4 kB
# 0x200000 / 0x1000 = 512 blocks = 2 MB
# 8MB - 6MB = 2MB

# reserved littlefs region 2 MB
CONFIG_LITTLEFS_BLOCK_SIZE=4096
CONFIG_LITTLEFS_BLOCK_COUNT=512
