# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

# W25Q128JW
# total size: 128Mbit -> 16MB -> 0x1000000 B

# littlefs offset
CONFIG_LITTLEFS_START_ADDR=0x600000

# 0x1000000 - 0x600000 = 0xA00000, 10 MB
# block size = 4096 B = 0x1000 B = 4 kB
# 0xA00000 / 0x1000 = 2560 blocks = 10 MB
# 16MB - 6MB = 10MB

# reserved littlefs region 2 MB
CONFIG_LITTLEFS_BLOCK_SIZE=4096
CONFIG_LITTLEFS_BLOCK_COUNT=512
