CONFIG_MCUX_COMPONENT_component.lpuart_adapter=y
CONFIG_MCUX_COMPONENT_component.serial_manager=y
CONFIG_MCUX_COMPONENT_component.serial_manager_uart=y
CONFIG_MCUX_COMPONENT_driver.misc_soc=y
CONFIG_MCUX_COMPONENT_driver.clock=y
CONFIG_MCUX_COMPONENT_driver.lpuart=y
CONFIG_MCUX_COMPONENT_driver.common=y
CONFIG_MCUX_COMPONENT_driver.cache_xcache=y
CONFIG_MCUX_COMPONENT_driver.misc_soc=y
CONFIG_MCUX_COMPONENT_driver.mu1=y
CONFIG_MCUX_COMPONENT_driver.src_soc=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_core_folder=n

