CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=y
CONFIG_MCUX_COMPONENT_driver.camera-device-ov5640=y
CONFIG_MCUX_ABSTRACT_COMPONENT_component_expander=y
CONFIG_MCUX_COMPONENT_driver.pca9555=y
CONFIG_MCUX_PRJSEG_module.board.display_support=y
CONFIG_RK055MHD091A0=y
