CONFIG_MCUX_COMPONENT_component.osa_free_rtos=y

#FreeRTOS
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel=y
CONFIG_gMainThreadStackSize_c=4096

CONFIG_MCUX_COMPONENT_component.serial_manager_uart=n
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.ota_support=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.platform.ot=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.lowpower=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.platform.lowpower_timer=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.pdm=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.pdum=y

CONFIG_MCUX_COMPONENT_middleware.wireless.zigbee=y
CONFIG_MCUX_COMPONENT_middleware.wireless.zigbee.router=y
CONFIG_ZB_ROUTER_TRACE_APP=n
CONFIG_MCUX_COMPONENT_middleware.wireless.zigbee.bdb_outofband=y

CONFIG_BT_AUTO_DATA_LEN_UPDATE=y
CONFIG_BT_AUTO_PHY_UPDATE=y
CONFIG_BT_DATA_LEN_UPDATE=y
CONFIG_BT_PHY_UPDATE=y
CONFIG_BT_RX_STACK_SIZE=2048
CONFIG_BT_DEVICE_NAME="\"NXP_ZIR\""
CONFIG_BT_DIS_MODEL="\"Wireless UART Demo\""
CONFIG_BT_GATT_CLIENT=y
CONFIG_BT_HOST_CRYPTO=y
CONFIG_BT_L2CAP_TX_BUF_COUNT=8
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_SMP=y
CONFIG_BT_SETTINGS=y
CONFIG_MCUX_COMPONENT_middleware.edgefast_bluetooth.ble.ethermind=y
CONFIG_MCUX_COMPONENT_middleware.edgefast_bluetooth.pal=y
CONFIG_MCUX_COMPONENT_middleware.edgefast_bluetooth.profile.dis=y
CONFIG_MCUX_COMPONENT_middleware.edgefast_bluetooth.profile.wu=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.platform.ble=y
CONFIG_MCUX_COMPONENT_middleware.wireless.framework.zephyr_port.settings.redefine_api=y
CONFIG_configSUPPORT_STATIC_ALLOCATION=y
CONFIG_MCUX_PRJSEG_middleware.fatfs.generated_config=n
CONFIG_MCUX_COMPONENT_component.rng_adapter_interface=y
CONFIG_MCUX_COMPONENT_component.software_rng_adapter=y
CONFIG_WORK_QUEUE_TASK_STACK_SIZE=4096
# Needed otherwise all the logs sent are fragmented to the default MTU value (20 payload)
# IoT Toolbox has an isse displaying the logs, since it often adds a new line
# after receiving and displaying a packet.
CONFIG_BT_L2CAP_TX_MTU=120
CONFIG_BT_BUF_ACL_RX_SIZE=124

CONFIG_MCUX_DEPENDENCY_COMPONENT_component.serial_manager_DEPEND_component.serial_manager_ble_wu=y
CONFIG_DEBUG_CONSOLE_TRANSMIT_BUFFER_LEN="4096U"
CONFIG_DEBUG_CONSOLE_TX_RELIABLE_ENABLE=n
CONFIG_MCUX_COMPONENT_utility.shell=y
CONFIG_DEBUG_CONSOLE_RX_ENABLE=n

CONFIG_FSL_OSA_MAIN_FUNC_ENABLE=n