CONFIG_MCUX_COMPONENT_driver.clock=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_folder=n
CONFIG_MCUX_PRJSEG_project.hw_app_customize_folder=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.loadersources=y
CONFIG_MCUX_COMPONENT_driver.uart=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.src_startup=y
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.MKE17Z9_startup=y
CONFIG_MCUX_COMPONENT_device.CMSIS=y
CONFIG_MCUX_PRJSEG_middleware.mcu-boot.MKE17Z9_flashloader_loader_linker=y
CONFIG_MCUX_PRJSEG_frdmke17z512_kboot_options=y
CONFIG_MCUX_PRJSEG_module.board.suite=n
CONFIG_MCUX_COMPONENT_middleware.mcu-boot.flashloader_loader_image=y
CONFIG_MCUX_COMPONENT_utility.assert=n
CONFIG_MCUX_COMPONENT_utility.assert_lite=n