#
# Copyright 2024-2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_COMPONENT_driver.mu=y
CONFIG_MCUX_COMPONENT_driver.sdma=y
CONFIG_MCUX_COMPONENT_driver.sai=y
CONFIG_MCUX_COMPONENT_driver.wm8524=y
