# Copyright 2024-2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_PRJSEG_middleware.freertos-kernel.generated_config=n
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.heap_3=y
CONFIG_MCUX_COMPONENT_middleware.freertos-kernel.extension=y
CONFIG_FSL_OSA_TASK_ENABLE=n
CONFIG_MCUX_COMPONENT_middleware.usb.common_header=y
CONFIG_MCUX_COMPONENT_middleware.usb.host.common_header=y
CONFIG_MCUX_COMPONENT_utility.debug_console=y
CONFIG_MCUX_COMPONENT_utility.assert=y
CONFIG_MCUX_PRJSEG_module.board.console_lite=n
CONFIG_USB_HOST_CONFIG_CDC=1
CONFIG_USB_HOST_CONFIG_CDC_RNDIS=1

# lwIP configuration:
CONFIG_MCUX_COMPONENT_middleware.lwip=y
CONFIG_MCUX_COMPONENT_middleware.lwip.contrib.ping=y
CONFIG_MCUX_COMPONENT_middleware.lwip.usb_ethernetif=y
CONFIG_MCUX_PRJSEG_middleware.lwip.generated_config=y
CONFIG_LWIP_OPT_H_CODE_LINE_1="void sys_lock_tcpip_core(void);"
CONFIG_LWIP_OPT_H_CODE_LINE_2="void sys_unlock_tcpip_core(void);"
CONFIG_LWIP_OPT_H_CODE_LINE_3="void sys_check_core_locking(void);"
CONFIG_LWIP_OPT_H_CODE_LINE_4="void sys_mark_tcpip_thread(void);"
CONFIG_SYS_LIGHTWEIGHT_PROT=y
CONFIG_NO_SYS=n
CONFIG_LWIP_NETIF_API=y
CONFIG_LWIP_NETCONN=y
CONFIG_LWIP_SOCKET=y
CONFIG_LWIP_DNS=y
CONFIG_LWIP_SO_RCVTIMEO=y
CONFIG_LWIP_TCPIP_CORE_LOCKING=n
#CONFIG_LOCK_TCPIP_CORE_CUSTOM( )="sys_lock_tcpip_core()"
#CONFIG_UNLOCK_TCPIP_CORE_CUSTOM( )="sys_unlock_tcpip_core()"
#CONFIG_LWIP_ASSERT_CORE_LOCKED( )="sys_check_core_locking()"
#CONFIG_LWIP_MARK_TCPIP_THREAD( )="sys_mark_tcpip_thread()"
CONFIG_MEM_ALIGNMENT=4
CONFIG_MEM_SIZE=22528
CONFIG_MEMP_NUM_PBUF=15
CONFIG_MEMP_NUM_UDP_PCB=6
CONFIG_MEMP_NUM_TCP_PCB=10
CONFIG_MEMP_NUM_TCP_PCB_LISTEN=6
CONFIG_MEMP_NUM_TCP_SEG=22
CONFIG_MEMP_NUM_SYS_TIMEOUT="10"
CONFIG_PBUF_POOL_SIZE=9
CONFIG_LWIP_TCP=y
CONFIG_TCP_TTL=255
CONFIG_TCP_QUEUE_OOSEQ=n
CONFIG_TCP_MSS=1460
CONFIG_TCP_SND_BUF="(6 * TCP_MSS)"
CONFIG_TCP_SND_QUEUELEN="((3 * TCP_SND_BUF) / TCP_MSS)"
CONFIG_TCP_WND="(2 * TCP_MSS)"
CONFIG_TCP_LISTEN_BACKLOG=y
CONFIG_LWIP_ICMP=y
CONFIG_LWIP_RAW=y
CONFIG_LWIP_DHCP=y
CONFIG_LWIP_UDP=y
CONFIG_UDP_TTL=255
CONFIG_LWIP_STATS=n
CONFIG_LWIP_PROVIDE_ERRNO=y
CONFIG_CHECKSUM_GEN_IP=y
CONFIG_CHECKSUM_GEN_UDP=y
CONFIG_CHECKSUM_GEN_TCP=y
CONFIG_CHECKSUM_CHECK_IP=y
CONFIG_CHECKSUM_CHECK_UDP=y
CONFIG_CHECKSUM_CHECK_TCP=y
CONFIG_DEFAULT_THREAD_STACKSIZE=1000
CONFIG_DEFAULT_THREAD_PRIO=4
CONFIG_LWIP_DEBUG=y
CONFIG_TCPIP_MBOX_SIZE=32
CONFIG_TCPIP_THREAD_STACKSIZE=1024
CONFIG_TCPIP_THREAD_PRIO=8
CONFIG_DEFAULT_RAW_RECVMBOX_SIZE=12
CONFIG_PING_USE_SOCKETS=n
CONFIG_DEFAULT_UDP_RECVMBOX_SIZE=12
CONFIG_DEFAULT_TCP_RECVMBOX_SIZE=12
CONFIG_DEFAULT_ACCEPTMBOX_SIZE=12
