CONFIG_MCUX_PRJSEG_project.hw_project_core_folder=y
CONFIG_MCUX_COMPONENT_middleware.g2d.cm7=y
CONFIG_MCUX_COMPONENT_driver.tstmr=y

# disable display support, since g2d_basic is an off-screen test
CONFIG_MCUX_PRJSEG_module.board.display_support=n
CONFIG_MCUX_COMPONENT_driver.mipi_dsi_imx=n
CONFIG_MCUX_COMPONENT_driver.lpi2c=n
CONFIG_MCUX_COMPONENT_driver.display-it6263=n
CONFIG_MCUX_COMPONENT_driver.display-rm692c9=n
CONFIG_MCUX_COMPONENT_driver.display-adv7535=n
CONFIG_MCUX_COMPONENT_driver.ldb_1=n
CONFIG_MCUX_COMPONENT_driver.rgpio=n
CONFIG_MCUX_COMPONENT_driver.adp5585=n
CONFIG_MCUX_ABSTRACT_COMPONENT_component_expander=n
CONFIG_MCUX_COMPONENT_driver.dpu_1=n