#select profile
CONFIG_MCUX_COMPONENT_middleware.tfm.profile_medium=y
CONFIG_MCUX_COMPONENT_middleware.psatest.ns.disable_crypto_cipher_module=y

#disable initial attest partition.
CONFIG_MCUX_COMPONENT_middleware.tfm.partition_init_attest=n
#cannot disable psa_initial-attest tests under above flag as its used with mbedtls3x psatest.
CONFIG_MCUX_COMPONENT_middleware.psatest.ns.initial_attestation=n
#include pin_mux board component
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_core_folder=y

#drivers
CONFIG_MCUX_COMPONENT_middleware.tfm.lpuart=y
CONFIG_MCUX_COMPONENT_driver.ctimer=y

# enable west flash of tfm example
CONFIG_FLASH_BASE_ADDRESS=0x00024000
