/*
 * Copyright (c) 2014-2016, Freescale Semiconductor, Inc.
 * Copyright 2016 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/*
 * Generated by erpcgen 1.13.0 on Thu Apr 18 09:37:38 2024.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_erpc_dac_adc_client_hpp_)
#define _erpc_dac_adc_client_hpp_

#include "erpc_dac_adc_interface.hpp"

#include "erpc_client_manager.h"

namespace erpcShim
{

class dac_adc_client: public dac_adc_interface
{
    public:
        dac_adc_client(erpc::ClientManager *manager);

        virtual ~dac_adc_client();

        virtual void adc_get_config(AdcConfig * config);

        virtual void convert_dac_adc(uint32_t numberToConvert, uint32_t * result);

        virtual void set_led(uint8_t whichLed);

        virtual void read_senzor_mag_accel(Vector * results);

        virtual void board_get_name(char * name);

    protected:
        erpc::ClientManager *m_clientManager;
};

} // erpcShim


#endif // _erpc_dac_adc_client_hpp_
