CONFIG_MCUX_COMPONENT_component.lpit_adapter=y
CONFIG_MCUX_COMPONENT_driver.lpit=y
CONFIG_USB_DEVICE_CONFIG_CHARGER_DETECT=y
CONFIG_USB_DEVICE_CONFIG_DETACH_ENABLE=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_customize_folder=n
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=y
CONFIG_USB_HSDCD_CLOCK_SPEED=24000000
CONFIG_configTOTAL_HEAP_SIZE=32768
