
CONFIG_MCUX_COMPONENT_component.psa_crypto_driver.caam=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.port.config=y
CONFIG_MCUX_COMPONENT_middleware.mbedtls3x.crypto_storage_ram=y

# Set the psa_key_location_t PSA value to primary secure element - CAAM (black blob) on this device.
# Please refer to the PSA API documentation for values of psa_key_location_t.
CONFIG_TEST_KEY_LOCATION=0x1