
CONFIG_MCUX_COMPONENT_component.silicon_id=y
CONFIG_MCUX_COMPONENT_component.silicon_id_rt1180=y
CONFIG_MCUX_COMPONENT_device.MIMXRT1189_mcux_scripts=y
CONFIG_MCUX_COMPONENT_component.lpuart_adapter=y
CONFIG_MCUX_COMPONENT_driver.uart=y
CONFIG_MCUX_COMPONENT_component.serial_manager=y
CONFIG_MCUX_COMPONENT_component.serial_manager_uart=y
CONFIG_MCUX_COMPONENT_device.MIMXRT1189_mcux_scripts=y
CONFIG_MCUX_COMPONENT_driver.memory=y
CONFIG_MCUX_COMPONENT_driver.cache_armv7_m7=y
CONFIG_MCUX_COMPONENT_driver.misc_soc=y
CONFIG_MCUX_COMPONENT_driver.gpt=y
CONFIG_MCUX_COMPONENT_driver.ecat=y
CONFIG_MCUX_COMPONENT_driver.lpi2c=y
CONFIG_MCUX_COMPONENT_driver.xbar_1=y
CONFIG_MCUX_COMPONENT_driver.sim=y
CONFIG_MCUX_COMPONENT_driver.port=y
CONFIG_MCUX_COMPONENT_driver.dmamux=y
CONFIG_MCUX_COMPONENT_driver.trgmux=y
CONFIG_MCUX_COMPONENT_driver.clock=y
CONFIG_MCUX_COMPONENT_driver.adc_etc=y
CONFIG_MCUX_COMPONENT_driver.lpadc=y
CONFIG_MCUX_COMPONENT_driver.lpuart=y
CONFIG_MCUX_COMPONENT_driver.common=y
CONFIG_MCUX_COMPONENT_driver.cache_xcache=y
CONFIG_MCUX_COMPONENT_driver.ele_base_api_soc=y
CONFIG_MCUX_COMPONENT_driver.misc_soc=y
CONFIG_MCUX_COMPONENT_driver.mu1=y
CONFIG_MCUX_COMPONENT_driver.src_soc=y
CONFIG_MCUX_COMPONENT_utility.incbin=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_core_folder=y
CONFIG_MCUX_PRJSEG_project.hw_app_project_core_folder=y
CONFIG_MCUX_PRJSEG_module.board.clock_customize_folder=y
