# Copyright 2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

# Drivers
CONFIG_MCUX_COMPONENT_driver.wwdt=y
CONFIG_MCUX_COMPONENT_driver.p3t1755=y

# OS (bm)
CONFIG_MCUX_COMPONENT_component.osa_bm=y

# MCXW23 power manager
CONFIG_MCUX_COMPONENT_component.power_manager.mcxw23=y

# BLE profiles
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_profiles_battery_service=y
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_profiles_device_info_service=y
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_profiles_health_thermometer=y
CONFIG_MCUX_COMPONENT_middleware.wireless.ble_profiles_time=y

CONFIG_MCUX_DEPENDENCY_COMPONENT_component.timer_manager_DEPEND_component.timer_manager_ostimer=y

# Link layer middleware
CONFIG_MCUX_COMPONENT_middleware.wireless.snps_ll=y
