# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

# Board project basic segments, delegate to <core_id>/prj.conf
CONFIG_MCUX_PRJSEG_module.board.pinmux_project_core_folder=y
# end of Board project basic segments
