/*
 * Copyright 2018, 2023 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/

/*! @brief Direction type  */
typedef enum _pin_mux_direction
{
  kPIN_MUX_DirectionInput = 0U,         /* Input direction */
  kPIN_MUX_DirectionOutput = 1U,        /* Output direction */
  kPIN_MUX_DirectionInputOrOutput = 2U  /* Input or output direction */
} pin_mux_direction_t;

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define BOARD_INITPINS_IOMUXC_GPR_GPR26_GPIO_MUX1_GPIO_SEL_MASK 0x0E00U /*!< GPIO1 and GPIO6 share same IO MUX function, GPIO_MUX1 selects one GPIO function: affected bits mask */

/* GPIO_AD_B0_13 (coord L14), UART1_RXD */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_RXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_RXD_SIGNAL                                       RX   /*!< Signal name */

/* GPIO_AD_B0_12 (coord K14), UART1_TXD */
/* Routed pin properties */
#define BOARD_INITPINS_UART1_TXD_PERIPHERAL                              LPUART1   /*!< Peripheral name */
#define BOARD_INITPINS_UART1_TXD_SIGNAL                                       TX   /*!< Signal name */

/* GPIO_AD_B0_11 (coord G10), JTAG_nTRST/J21[3]/INT2_COMBO/LCD_TOUCH_INT/J22[3]/U32[9] */
/* Routed pin properties */
#define BOARD_INITPINS_INT2_COMBO_PERIPHERAL                               GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_INT2_COMBO_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_INT2_COMBO_CHANNEL                                    11U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_INT2_COMBO_GPIO                                     GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_INT2_COMBO_GPIO_PIN                                   11U   /*!< GPIO pin number */
#define BOARD_INITPINS_INT2_COMBO_GPIO_PIN_MASK                      (1U << 11U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_INT2_COMBO_PORT                                     GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_INT2_COMBO_PIN                                        11U   /*!< PORT pin number */
#define BOARD_INITPINS_INT2_COMBO_PIN_MASK                           (1U << 11U)   /*!< PORT pin mask */

/* GPIO_AD_B0_10 (coord G13), JTAG_TDO/J21[13]/INT1_COMBO/ENET_INT/J22[6]/U32[11] */
/* Routed pin properties */
#define BOARD_INITPINS_INT1_COMBO_PERIPHERAL                               GPIO1   /*!< Peripheral name */
#define BOARD_INITPINS_INT1_COMBO_SIGNAL                                 gpio_io   /*!< Signal name */
#define BOARD_INITPINS_INT1_COMBO_CHANNEL                                    10U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_INT1_COMBO_GPIO                                     GPIO1   /*!< GPIO peripheral base pointer */
#define BOARD_INITPINS_INT1_COMBO_GPIO_PIN                                   10U   /*!< GPIO pin number */
#define BOARD_INITPINS_INT1_COMBO_GPIO_PIN_MASK                      (1U << 10U)   /*!< GPIO pin mask */
#define BOARD_INITPINS_INT1_COMBO_PORT                                     GPIO1   /*!< PORT peripheral base pointer */
#define BOARD_INITPINS_INT1_COMBO_PIN                                        10U   /*!< PORT pin number */
#define BOARD_INITPINS_INT1_COMBO_PIN_MASK                           (1U << 10U)   /*!< PORT pin mask */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
