mcux_remove_iar_linker_script(
  BASE_PATH
  ${SdkRootDirPath}
  TARGETS
  flash_debug
  flash_release
  LINKER
  ${device_root}/RT/RT700/MIMXRT798S/iar/MIMXRT798Sxxxx_cm33_core0_flash.icf)
mcux_remove_mdk_linker_script(
  BASE_PATH
  ${SdkRootDirPath}
  TARGETS
  flash_debug
  flash_release
  LINKER
  ${device_root}/RT/RT700/MIMXRT798S/arm/MIMXRT798Sxxxx_cm33_core0_flash.scf)
mcux_remove_armgcc_linker_script(
  BASE_PATH
  ${SdkRootDirPath}
  TARGETS
  flash_debug
  flash_release
  LINKER
  ${device_root}/RT/RT700/MIMXRT798S/gcc/MIMXRT798Sxxxx_cm33_core0_flash.ld)

# Add board-specific linker scripts that place flash-ops and XSPI driver objects
# in RAM.
mcux_add_iar_linker_script(
  BASE_PATH
  ${SdkRootDirPath}
  TARGETS
  flash_debug
  flash_release
  LINKER
  ${board_root}/${board}/driver_examples/xspi/quad/polling_transfer/${multicore_foldername}/iar/MIMXRT798Sxxxx_cm33_core0_flash.icf
)
mcux_add_mdk_linker_script(
  BASE_PATH
  ${SdkRootDirPath}
  TARGETS
  flash_debug
  flash_release
  LINKER
  ${board_root}/${board}/driver_examples/xspi/quad/polling_transfer/${multicore_foldername}/mdk/MIMXRT798Sxxxx_cm33_core0_flash.scf
)
mcux_add_armgcc_linker_script(
  BASE_PATH
  ${SdkRootDirPath}
  TARGETS
  flash_debug
  flash_release
  LINKER
  ${board_root}/${board}/driver_examples/xspi/quad/polling_transfer/${multicore_foldername}/armgcc/MIMXRT798Sxxxx_cm33_core0_flash.ld
)
