/*
 * Copyright 2026 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDEBUG_UARTPins(void);          /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDsPins(void);                /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitBUTTONsPins(void);             /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitI3CPins(void);                 /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_Init6524Pins(void);                /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPCA9555Pins(void);             /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSPIPins(void);                 /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPWMPins(void);                 /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCANPins(void);                 /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitFLEXIO_UARTPins(void);         /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitFLEXIO_I2CPins(void);          /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitFLEXIO_PININPUTPins(void);     /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitTenBaseT1S0Pins(void);         /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitTenBaseT1S1Pins(void);         /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitFLEXIO_PINOUTPUTPins(void);    /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitFLEXIO_PWMPins(void);          /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitFLEXIO_SPIPins(void);          /* Function assigned for the Cortex-M85 */

/* PIO3_0 (coord R2), DP4LANE */
/* Routed pin properties */
#define BOARD_INITDCIFDPIPINS_DP4LANE_PERIPHERAL                     MEDIA__DCIF   /*!< Peripheral name */
#define BOARD_INITDCIFDPIPINS_DP4LANE_SIGNAL                                DATA   /*!< Signal name */
#define BOARD_INITDCIFDPIPINS_DP4LANE_CHANNEL                                 0U   /*!< Signal channel */

/* PIO3_1 (coord R1), DP_HPD */
/* Routed pin properties */
#define BOARD_INITDCIFDPIPINS_DP_HPD_PERIPHERAL                      MEDIA__DCIF   /*!< Peripheral name */
#define BOARD_INITDCIFDPIPINS_DP_HPD_SIGNAL                                 DATA   /*!< Signal name */
#define BOARD_INITDCIFDPIPINS_DP_HPD_CHANNEL                                  1U   /*!< Signal channel */

/* PIO3_2 (coord R5), EXTRA_EN_SRCn */
/* Routed pin properties */
#define BOARD_INITDCIFDPIPINS_EXTRA_EN_SRCn_PERIPHERAL               MEDIA__DCIF   /*!< Peripheral name */
#define BOARD_INITDCIFDPIPINS_EXTRA_EN_SRCn_SIGNAL                          DATA   /*!< Signal name */
#define BOARD_INITDCIFDPIPINS_EXTRA_EN_SRCn_CHANNEL                           2U   /*!< Signal channel */

/* PIO3_3 (coord R4), PD_XSD */
/* Routed pin properties */
#define BOARD_INITDCIFDPIPINS_PD_XSD_PERIPHERAL                      MEDIA__DCIF   /*!< Peripheral name */
#define BOARD_INITDCIFDPIPINS_PD_XSD_SIGNAL                                 DATA   /*!< Signal name */
#define BOARD_INITDCIFDPIPINS_PD_XSD_CHANNEL                                  3U   /*!< Signal channel */

/* PIO3_4 (coord L2), DC_BARREL_PRES */
/* Routed pin properties */
#define BOARD_INITDCIFDPIPINS_DC_BARREL_PRES_PERIPHERAL              MEDIA__DCIF   /*!< Peripheral name */
#define BOARD_INITDCIFDPIPINS_DC_BARREL_PRES_SIGNAL                         DATA   /*!< Signal name */
#define BOARD_INITDCIFDPIPINS_DC_BARREL_PRES_CHANNEL                          4U   /*!< Signal channel */

/* PIO3_6 (coord T1), nALERT */
/* Routed pin properties */
#define BOARD_INITDCIFDPIPINS_nALERT_PERIPHERAL                      MEDIA__DCIF   /*!< Peripheral name */
#define BOARD_INITDCIFDPIPINS_nALERT_SIGNAL                                 DATA   /*!< Signal name */
#define BOARD_INITDCIFDPIPINS_nALERT_CHANNEL                                  6U   /*!< Signal channel */

/* PIO3_7 (coord T2), ORIENT */
/* Routed pin properties */
#define BOARD_INITDCIFDPIPINS_ORIENT_PERIPHERAL                      MEDIA__DCIF   /*!< Peripheral name */
#define BOARD_INITDCIFDPIPINS_ORIENT_SIGNAL                                 DATA   /*!< Signal name */
#define BOARD_INITDCIFDPIPINS_ORIENT_CHANNEL                                  7U   /*!< Signal channel */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDcifDpiPins(void);            /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCSIPins(void);                 /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitTouchPins(void);               /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitUSDHC0Pins(void);              /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitENETPins(void);                /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitENETQOSPins(void);             /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitXSPIPins(void);                /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitXSPI1PsRamPins(void);          /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitALT_UARTPins(void);            /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSAIPins(void);                 /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitCMPPins(void);                 /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitMIPIPanelPins(void);           /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitADCPin(void);                  /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitEQDCPins(void);                /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitEVTGPins(void);                /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitQTMRPins(void);                /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitSINCPins(void);                /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitI2CPins(void);                 /* Function assigned for the Cortex-M85 */

/* PIO3_7 (coord T2), ORIENT */
/* Routed pin properties */
#define BOARD_INITOM13790HOST_GPIOPINS_ORIENT_PERIPHERAL             HSP__GPIO_1   /*!< Peripheral name */
#define BOARD_INITOM13790HOST_GPIOPINS_ORIENT_SIGNAL                        GPIO   /*!< Signal name */
#define BOARD_INITOM13790HOST_GPIOPINS_ORIENT_CHANNEL                         7U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITOM13790HOST_GPIOPINS_ORIENT_GPIO                   HSP__GPIO_1   /*!< GPIO peripheral base pointer */
#define BOARD_INITOM13790HOST_GPIOPINS_ORIENT_INIT_GPIO_VALUE                 0U   /*!< GPIO output initial state */
#define BOARD_INITOM13790HOST_GPIOPINS_ORIENT_GPIO_PIN                        7U   /*!< GPIO pin number */
#define BOARD_INITOM13790HOST_GPIOPINS_ORIENT_GPIO_PIN_MASK           (1U << 7U)   /*!< GPIO pin mask */

/* PIO3_3 (coord R4), PD_XSD */
/* Routed pin properties */
#define BOARD_INITOM13790HOST_GPIOPINS_PD_XSD_PERIPHERAL             HSP__GPIO_1   /*!< Peripheral name */
#define BOARD_INITOM13790HOST_GPIOPINS_PD_XSD_SIGNAL                        GPIO   /*!< Signal name */
#define BOARD_INITOM13790HOST_GPIOPINS_PD_XSD_CHANNEL                         3U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITOM13790HOST_GPIOPINS_PD_XSD_GPIO                   HSP__GPIO_1   /*!< GPIO peripheral base pointer */
#define BOARD_INITOM13790HOST_GPIOPINS_PD_XSD_INIT_GPIO_VALUE                 0U   /*!< GPIO output initial state */
#define BOARD_INITOM13790HOST_GPIOPINS_PD_XSD_GPIO_PIN                        3U   /*!< GPIO pin number */
#define BOARD_INITOM13790HOST_GPIOPINS_PD_XSD_GPIO_PIN_MASK           (1U << 3U)   /*!< GPIO pin mask */

/* PIO3_0 (coord R2), DP4LANE */
/* Routed pin properties */
#define BOARD_INITOM13790HOST_GPIOPINS_DP4LANE_PERIPHERAL            HSP__GPIO_1   /*!< Peripheral name */
#define BOARD_INITOM13790HOST_GPIOPINS_DP4LANE_SIGNAL                       GPIO   /*!< Signal name */
#define BOARD_INITOM13790HOST_GPIOPINS_DP4LANE_CHANNEL                        0U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITOM13790HOST_GPIOPINS_DP4LANE_GPIO                  HSP__GPIO_1   /*!< GPIO peripheral base pointer */
#define BOARD_INITOM13790HOST_GPIOPINS_DP4LANE_INIT_GPIO_VALUE                0U   /*!< GPIO output initial state */
#define BOARD_INITOM13790HOST_GPIOPINS_DP4LANE_GPIO_PIN                       0U   /*!< GPIO pin number */
#define BOARD_INITOM13790HOST_GPIOPINS_DP4LANE_GPIO_PIN_MASK          (1U << 0U)   /*!< GPIO pin mask */

/* PIO3_1 (coord R1), DP_HPD */
/* Routed pin properties */
#define BOARD_INITOM13790HOST_GPIOPINS_DP_HPD_PERIPHERAL             HSP__GPIO_1   /*!< Peripheral name */
#define BOARD_INITOM13790HOST_GPIOPINS_DP_HPD_SIGNAL                        GPIO   /*!< Signal name */
#define BOARD_INITOM13790HOST_GPIOPINS_DP_HPD_CHANNEL                         1U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITOM13790HOST_GPIOPINS_DP_HPD_GPIO                   HSP__GPIO_1   /*!< GPIO peripheral base pointer */
#define BOARD_INITOM13790HOST_GPIOPINS_DP_HPD_INIT_GPIO_VALUE                 0U   /*!< GPIO output initial state */
#define BOARD_INITOM13790HOST_GPIOPINS_DP_HPD_GPIO_PIN                        1U   /*!< GPIO pin number */
#define BOARD_INITOM13790HOST_GPIOPINS_DP_HPD_GPIO_PIN_MASK           (1U << 1U)   /*!< GPIO pin mask */

/* PIO3_2 (coord R5), EXTRA_EN_SRCn */
/* Routed pin properties */
#define BOARD_INITOM13790HOST_GPIOPINS_EXTRA_EN_SRCn_PERIPHERAL      HSP__GPIO_1   /*!< Peripheral name */
#define BOARD_INITOM13790HOST_GPIOPINS_EXTRA_EN_SRCn_SIGNAL                 GPIO   /*!< Signal name */
#define BOARD_INITOM13790HOST_GPIOPINS_EXTRA_EN_SRCn_CHANNEL                  2U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITOM13790HOST_GPIOPINS_EXTRA_EN_SRCn_GPIO            HSP__GPIO_1   /*!< GPIO peripheral base pointer */
#define BOARD_INITOM13790HOST_GPIOPINS_EXTRA_EN_SRCn_INIT_GPIO_VALUE          0U   /*!< GPIO output initial state */
#define BOARD_INITOM13790HOST_GPIOPINS_EXTRA_EN_SRCn_GPIO_PIN                 2U   /*!< GPIO pin number */
#define BOARD_INITOM13790HOST_GPIOPINS_EXTRA_EN_SRCn_GPIO_PIN_MASK    (1U << 2U)   /*!< GPIO pin mask */

/* PIO3_4 (coord L2), DC_BARREL_PRES */
/* Routed pin properties */
#define BOARD_INITOM13790HOST_GPIOPINS_DC_BARREL_PRES_PERIPHERAL     HSP__GPIO_1   /*!< Peripheral name */
#define BOARD_INITOM13790HOST_GPIOPINS_DC_BARREL_PRES_SIGNAL                GPIO   /*!< Signal name */
#define BOARD_INITOM13790HOST_GPIOPINS_DC_BARREL_PRES_CHANNEL                 4U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITOM13790HOST_GPIOPINS_DC_BARREL_PRES_GPIO           HSP__GPIO_1   /*!< GPIO peripheral base pointer */
#define BOARD_INITOM13790HOST_GPIOPINS_DC_BARREL_PRES_GPIO_PIN                4U   /*!< GPIO pin number */
#define BOARD_INITOM13790HOST_GPIOPINS_DC_BARREL_PRES_GPIO_PIN_MASK   (1U << 4U)   /*!< GPIO pin mask */

/* PIO3_6 (coord T1), nALERT */
/* Routed pin properties */
#define BOARD_INITOM13790HOST_GPIOPINS_nALERT_PERIPHERAL             HSP__GPIO_1   /*!< Peripheral name */
#define BOARD_INITOM13790HOST_GPIOPINS_nALERT_SIGNAL                        GPIO   /*!< Signal name */
#define BOARD_INITOM13790HOST_GPIOPINS_nALERT_CHANNEL                         6U   /*!< Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITOM13790HOST_GPIOPINS_nALERT_GPIO                   HSP__GPIO_1   /*!< GPIO peripheral base pointer */
#define BOARD_INITOM13790HOST_GPIOPINS_nALERT_GPIO_PIN                        6U   /*!< GPIO pin number */
#define BOARD_INITOM13790HOST_GPIOPINS_nALERT_GPIO_PIN_MASK           (1U << 6U)   /*!< GPIO pin mask */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitOM13790HOST_GPIOPins(void);    /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitOM13790HOST_I2CPins(void);     /* Function assigned for the Cortex-M85 */

/*!
@brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitDcifDbiPins(void);            /* Function assigned for the Cortex-M85 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
