# Copyright 2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

# File system offset (after application code)
CONFIG_LITTLEFS_START_ADDR=0x600000

#W25Q512NW
CONFIG_LITTLEFS_BLOCK_SIZE=4096
CONFIG_LITTLEFS_BLOCK_COUNT=2048
