# Copyright 2025 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_COMPONENT_component.silicon_id=y
CONFIG_MCUX_COMPONENT_component.phylan8741=y
CONFIG_MCUX_PRJSEG_module.board.pinmux_board_folder=y
CONFIG_ETH_ENET_QOS_MII_MODE="kENET_QOS_RmiiMode"
CONFIG_ETH_USE_GPIO_ADAPTER=n
