/*
 * Copyright 2020-2021 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define GPIO_PUR_PU_10_MASK 0x0400u /*!<@brief Pull Resistor Enable Bits Mask for item 10. */
#define GPIO_PUR_PU_1_MASK 0x02u    /*!<@brief Pull Resistor Enable Bits Mask for item 1. */
#define PUR_PU_10_ENABLED 0x0400u   /*!<@brief Pull Resistor Enable Bits: Pull resistor is enabled */
#define PUR_PU_1_ENABLED 0x02u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is enabled */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
