/*
 * Copyright 2024 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v16.0
processor: MCIMX7U5xxxxx
package_id: MCIMX7U5DVP07
mcu_data: ksdk2_0
processor_version: 16.3.0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
    BOARD_InitDEBUG_UARTPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm4}
- pin_list: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {                                /*!< Function assigned for the core: Cortex-M4[cm4] */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDEBUG_UARTPins:
- options: {callFromInitBoot: 'true', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AB19, peripheral: LPUART0, signal: lpuart_rx, pin_signal: PTA19, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: AC19, peripheral: LPUART0, signal: lpuart_tx, pin_signal: PTA18, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDEBUG_UARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitDEBUG_UARTPins(void) {                      /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(IOMUXC_PTA18_LPUART0_TX, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA18_LPUART0_TX,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTA19_LPUART0_RX, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA19_LPUART0_RX,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitI2C3Pins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AC8, peripheral: LPI2C3, signal: lpi2c_scl, pin_signal: PTB12, ODE: ODE_1_Open_drain}
  - {pin_num: AD8, peripheral: LPI2C3, signal: lpi2c_sda, pin_signal: PTB13, ODE: ODE_1_Open_drain}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitI2C3Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitI2C3Pins(void) {                            /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(IOMUXC_PTB12_LPI2C3_SCL, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTB12_LPI2C3_SCL,
                        IOMUXC0_SW_MUX_CTL_PAD_ODE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTB13_LPI2C3_SDA, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTB13_LPI2C3_SDA,
                        IOMUXC0_SW_MUX_CTL_PAD_ODE_MASK);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLPSPI1Pins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AF18, peripheral: LPSPI1, signal: 'lpspi_pcs, 0', pin_signal: PTA15}
  - {pin_num: AF17, peripheral: LPSPI1, signal: lpspi_sck, pin_signal: PTA14}
  - {pin_num: AG16, peripheral: LPSPI1, signal: lpspi_sin, pin_signal: PTA12}
  - {pin_num: AF16, peripheral: LPSPI1, signal: lpspi_sout, pin_signal: PTA13}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLPSPI1Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLPSPI1Pins(void) {                          /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(IOMUXC_PTA12_LPSPI1_SIN, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTA13_LPSPI1_SOUT, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTA14_LPSPI1_SCK, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTA15_LPSPI1_PCS0, 0U);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitADCPins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AD16, peripheral: ADC1, signal: adc_ch6a, pin_signal: PTA10}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitADCPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitADCPins(void) {                             /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(IOMUXC_PTA10_ADC1_CH6A, 0U);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitI2SPins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AD15, peripheral: I2S0, signal: i2s_mclk, pin_signal: PTA4, OBE: OBE_1_Enabled, DSE: DSE_1_Hi_Drive}
  - {pin_num: AG14, peripheral: I2S0, signal: 'i2s_rxd, 0', pin_signal: PTA2}
  - {pin_num: AC15, peripheral: I2S0, signal: i2s_tx_bclk, pin_signal: PTA5, DSE: DSE_1_Hi_Drive}
  - {pin_num: AB15, peripheral: I2S0, signal: i2s_tx_fs, pin_signal: PTA6, DSE: DSE_1_Hi_Drive}
  - {pin_num: AD14, peripheral: I2S0, signal: 'i2s_txd, 0', pin_signal: PTA7, DSE: DSE_1_Hi_Drive}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitI2SPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitI2SPins(void) {                             /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(IOMUXC_PTA2_I2S0_RXD0, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTA4_I2S0_MCLK, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA4_I2S0_MCLK,
                        IOMUXC0_SW_MUX_CTL_PAD_OBE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_DSE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTA5_I2S0_TX_BCLK, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA5_I2S0_TX_BCLK,
                        IOMUXC0_SW_MUX_CTL_PAD_DSE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTA6_I2S0_TX_FS, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA6_I2S0_TX_FS,
                        IOMUXC0_SW_MUX_CTL_PAD_DSE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTA7_I2S0_TXD0, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA7_I2S0_TXD0,
                        IOMUXC0_SW_MUX_CTL_PAD_DSE_MASK);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitI2C0Pins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AG18, peripheral: LPI2C0, signal: lpi2c_scl, pin_signal: PTA16, ODE: ODE_1_Open_drain}
  - {pin_num: AD19, peripheral: LPI2C0, signal: lpi2c_sda, pin_signal: PTA17, ODE: ODE_1_Open_drain}
  - {pin_num: AC8, peripheral: LPI2C3, signal: lpi2c_scl, pin_signal: PTB12, ODE: ODE_1_Open_drain}
  - {pin_num: AD8, peripheral: LPI2C3, signal: lpi2c_sda, pin_signal: PTB13, ODE: ODE_1_Open_drain}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitI2C0Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitI2C0Pins(void) {                            /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(IOMUXC_PTA16_LPI2C0_SCL, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA16_LPI2C0_SCL,
                        IOMUXC0_SW_MUX_CTL_PAD_ODE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTA17_LPI2C0_SDA, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA17_LPI2C0_SDA,
                        IOMUXC0_SW_MUX_CTL_PAD_ODE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTB12_LPI2C3_SCL, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTB12_LPI2C3_SCL,
                        IOMUXC0_SW_MUX_CTL_PAD_ODE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTB13_LPI2C3_SDA, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTB13_LPI2C3_SDA,
                        IOMUXC0_SW_MUX_CTL_PAD_ODE_MASK);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitQSPIPins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AD10, peripheral: QSPIA, signal: 'qspia_data, 0', pin_signal: PTB19}
  - {pin_num: AG10, peripheral: QSPIA, signal: 'qspia_data, 1', pin_signal: PTB18}
  - {pin_num: AF10, peripheral: QSPIA, signal: 'qspia_data, 2', pin_signal: PTB17}
  - {pin_num: AF9, peripheral: QSPIA, signal: 'qspia_data, 3', pin_signal: PTB16}
  - {pin_num: AF8, peripheral: QSPIA, signal: qspia_sclk, pin_signal: PTB15}
  - {pin_num: AG6, peripheral: QSPIA, signal: 'qspia_ss_b, 0', pin_signal: PTB8}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitQSPIPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitQSPIPins(void) {                            /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(IOMUXC_PTB15_QSPIA_SCLK, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTB16_QSPIA_DATA3, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTB17_QSPIA_DATA2, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTB18_QSPIA_DATA1, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTB19_QSPIA_DATA0, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTB8_QSPIA_SS0_B, 0U);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitUART2Pins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AD18, peripheral: LPUART2, signal: lpuart_rx, pin_signal: PTA11, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: AD16, peripheral: LPUART2, signal: lpuart_tx, pin_signal: PTA10, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitUART2Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitUART2Pins(void) {                           /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(IOMUXC_PTA10_LPUART2_TX, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA10_LPUART2_TX,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTA11_LPUART2_RX, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA11_LPUART2_RX,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitRTCPins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AG8, peripheral: RTC, signal: rtc_clkout, pin_signal: PTB14, IBE: IBE_0_Disabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitRTCPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitRTCPins(void) {                             /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(IOMUXC_PTB14_RTC_CLKOUT, 0U);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitCMPPins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AD19, peripheral: CMP1, signal: 'cmp_in_3v, 6', pin_signal: PTA17}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitCMPPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitCMPPins(void) {                             /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(IOMUXC_PTA17_CMP1_IN6_3V, 0U);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitDACPins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AD11, peripheral: DAC0, signal: dac_out, pin_signal: DAC0_OUT}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitDACPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitDACPins(void) {                             /*!< Function assigned for the core: Cortex-M4[cm4] */
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitFLEXIOPins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AG18, peripheral: FXIO0, signal: 'fxio_d, 0', pin_signal: PTA16, ODE: ODE_0_Push_pull}
  - {pin_num: AD19, peripheral: FXIO0, signal: 'fxio_d, 1', pin_signal: PTA17, ODE: ODE_0_Push_pull}
  - {pin_num: AD20, peripheral: FXIO0, signal: 'fxio_d, 7', pin_signal: PTA23}
  - {pin_num: AD22, peripheral: FXIO0, signal: 'fxio_d, 4', pin_signal: PTA20}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitFLEXIOPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitFLEXIOPins(void) {                          /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(IOMUXC_PTA16_FXIO0_D0, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTA17_FXIO0_D1, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTA20_FXIO0_D4, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTA23_FXIO0_D7, 0U);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitSPIPins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AF18, peripheral: LPSPI1, signal: 'lpspi_pcs, 0', pin_signal: PTA15}
  - {pin_num: AF17, peripheral: LPSPI1, signal: lpspi_sck, pin_signal: PTA14}
  - {pin_num: AG16, peripheral: LPSPI1, signal: lpspi_sin, pin_signal: PTA12}
  - {pin_num: AF16, peripheral: LPSPI1, signal: lpspi_sout, pin_signal: PTA13}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitSPIPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitSPIPins(void) {                             /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(IOMUXC_PTA12_LPSPI1_SIN, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTA13_LPSPI1_SOUT, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTA14_LPSPI1_SCK, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTA15_LPSPI1_PCS0, 0U);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitGPIOAPins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AG20, peripheral: PTA, signal: 'port, 25', pin_signal: PTA25, OBE: OBE_1_Enabled}
  - {pin_num: AF14, peripheral: PTA, signal: 'port, 3', pin_signal: PTA3, IBE: IBE_1_Enabled}
  - {pin_num: AF16, peripheral: PTA, signal: 'port, 13', pin_signal: PTA13, IBE: IBE_1_Enabled}
  - {pin_num: AF17, peripheral: PTA, signal: 'port, 14', pin_signal: PTA14, OBE: OBE_1_Enabled}
  - {pin_num: AF18, peripheral: PTA, signal: 'port, 15', pin_signal: PTA15, OBE: OBE_1_Enabled}
  - {pin_num: AF24, peripheral: PTA, signal: 'port, 31', pin_signal: PTA31, IBE: IBE_1_Enabled, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: AB16, peripheral: PTA, signal: 'port, 8', pin_signal: PTA8}
  - {pin_num: AG18, peripheral: PTA, signal: 'port, 16', pin_signal: PTA16, OBE: OBE_1_Enabled}
  - {pin_num: AD19, peripheral: PTA, signal: 'port, 17', pin_signal: PTA17, OBE: OBE_1_Enabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitGPIOAPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitGPIOAPins(void) {                           /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(IOMUXC_PTA13_PTA13, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA13_PTA13,
                        IOMUXC0_SW_MUX_CTL_PAD_IBE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTA14_PTA14, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA14_PTA14,
                        IOMUXC0_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTA15_PTA15, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA15_PTA15,
                        IOMUXC0_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTA16_PTA16, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA16_PTA16,
                        IOMUXC0_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTA17_PTA17, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA17_PTA17,
                        IOMUXC0_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTA25_PTA25, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA25_PTA25,
                        IOMUXC0_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTA3_PTA3, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA3_PTA3,
                        IOMUXC0_SW_MUX_CTL_PAD_IBE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTA31_PTA31, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA31_PTA31,
                        IOMUXC0_SW_MUX_CTL_PAD_IBE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTA8_PTA8, 0U);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitGPIOBPins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AF2, peripheral: PTB, signal: 'port, 1', pin_signal: PTB1, PE: PE_1_pull_enabled}
  - {pin_num: AE3, peripheral: PTB, signal: 'port, 2', pin_signal: PTB2, PE: PE_1_pull_enabled}
  - {pin_num: AE4, peripheral: PTB, signal: 'port, 3', pin_signal: PTB3, PE: PE_1_pull_enabled}
  - {pin_num: AC7, peripheral: PTB, signal: 'port, 10', pin_signal: PTB10, PE: PE_1_pull_enabled}
  - {pin_num: AG4, peripheral: PTB, signal: 'port, 4', pin_signal: PTB4, PE: PE_1_pull_enabled}
  - {pin_num: AF4, peripheral: PTB, signal: 'port, 5', pin_signal: PTB5, PS: PS_1_pull_up}
  - {pin_num: AF5, peripheral: PTB, signal: 'port, 6', pin_signal: PTB6, OBE: OBE_1_Enabled}
  - {pin_num: AF6, peripheral: PTB, signal: 'port, 7', pin_signal: PTB7, IBE: IBE_1_Enabled, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: AD7, peripheral: PTB, signal: 'port, 9', pin_signal: PTB9, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: AB7, peripheral: PTB, signal: 'port, 11', pin_signal: PTB11, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitGPIOBPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitGPIOBPins(void) {                           /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(IOMUXC_PTB1_PTB1, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTB1_PTB1,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTB10_PTB10, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTB10_PTB10,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTB11_PTB11, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTB11_PTB11,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTB2_PTB2, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTB2_PTB2,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTB3_PTB3, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTB3_PTB3,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTB4_PTB4, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTB4_PTB4,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTB5_PTB5, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTB5_PTB5,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTB6_PTB6, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTB6_PTB6,
                        IOMUXC0_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTB7_PTB7, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTB7_PTB7,
                        IOMUXC0_SW_MUX_CTL_PAD_IBE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTB9_PTB9, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTB9_PTB9,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPF1550Pins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AG16, peripheral: PTA, signal: 'port, 12', pin_signal: PTA12, direction: OUTPUT, OBE: OBE_1_Enabled}
  - {pin_num: AB7, peripheral: PTB, signal: 'port, 11', pin_signal: PTB11, direction: INPUT, IBE: IBE_1_Enabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPF1550Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPF1550Pins(void) {                          /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(IOMUXC_PTA12_PTA12, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA12_PTA12,
                        IOMUXC0_SW_MUX_CTL_PAD_OBE_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTB11_PTB11, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTB11_PTB11,
                        IOMUXC0_SW_MUX_CTL_PAD_IBE_MASK);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitTPM0Pins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AD15, peripheral: TPM0, signal: 'tpm_ch, 3', pin_signal: PTA4}
  - {pin_num: AC15, peripheral: TPM0, signal: 'tpm_ch, 4', pin_signal: PTA5}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitTPM0Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitTPM0Pins(void) {                            /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(IOMUXC_PTA4_TPM0_CH3, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTA5_TPM0_CH4, 0U);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitLPSPI0Pins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AD20, peripheral: LPSPI0, signal: 'lpspi_pcs, 3', pin_signal: PTA23}
  - {pin_num: AD19, peripheral: LPSPI0, signal: lpspi_sck, pin_signal: PTA17}
  - {pin_num: AD22, peripheral: LPSPI0, signal: lpspi_sin, pin_signal: PTA20}
  - {pin_num: AG18, peripheral: LPSPI0, signal: lpspi_sout, pin_signal: PTA16}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitLPSPI0Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitLPSPI0Pins(void) {                          /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(IOMUXC_PTA16_LPSPI0_SOUT, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTA17_LPSPI0_SCK, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTA20_LPSPI0_SIN, 0U);
    IOMUXC_SetPinMux(IOMUXC_PTA23_LPSPI0_PCS3, 0U);
}


/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitTPM2Pins:
- options: {callFromInitBoot: 'false', prefix: BOARD_, coreID: cm4}
- pin_list:
  - {pin_num: AD18, peripheral: TPM2, signal: 'tpm_ch, 0', pin_signal: PTA11, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
  - {pin_num: AG2, peripheral: TPM2, signal: 'tpm_ch, 1', pin_signal: PTB0, PE: PE_1_pull_enabled, PS: PS_1_pull_up}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitTPM2Pins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitTPM2Pins(void) {                            /*!< Function assigned for the core: Cortex-M4[cm4] */
    IOMUXC_SetPinMux(IOMUXC_PTA11_TPM2_CH0, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTA11_TPM2_CH0,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
    IOMUXC_SetPinMux(IOMUXC_PTB0_TPM2_CH1, 0U);
    IOMUXC_SetPinConfig(IOMUXC_PTB0_TPM2_CH1,
                        IOMUXC0_SW_MUX_CTL_PAD_PE_MASK |
                        IOMUXC0_SW_MUX_CTL_PAD_PS_MASK);
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
