CONFIG_MCUX_COMPONENT_middleware.wireless.framework.seclib_rng_port.psa=y
CONFIG_MCUX_PRJSEG_module.board.wireless.ble_app_mbedtls_psa_config=y

# Allow fault detection on NBU
# NBU shall be using framework fault handlers module for this to be true
CONFIG_MCUX_PRJSEG_module.board.wireless.board.debug_nbu=y
